// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.scailo.proto

package com.scailo.sdk;

public interface AbridgedPurchaseReturnItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.AbridgedPurchaseReturnItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores the purchase return ID
   * </pre>
   *
   * <code>uint64 purchase_return_id = 10 [json_name = "purchaseReturnId"];</code>
   * @return The purchaseReturnId.
   */
  long getPurchaseReturnId();

  /**
   * <pre>
   * Stores the family ID
   * </pre>
   *
   * <code>uint64 family_id = 20 [json_name = "familyId"];</code>
   * @return The familyId.
   */
  long getFamilyId();

  /**
   * <pre>
   * The quantity of the item (in cents)
   * </pre>
   *
   * <code>int64 quantity = 30 [json_name = "quantity"];</code>
   * @return The quantity.
   */
  long getQuantity();
}
