// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activities_tags.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the base request payload of a filter search
 * </pre>
 *
 * Protobuf type {@code Scailo.ActivitiesTagsServiceFilterReq}
 */
public final class ActivitiesTagsServiceFilterReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Scailo.ActivitiesTagsServiceFilterReq)
    ActivitiesTagsServiceFilterReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActivitiesTagsServiceFilterReq.newBuilder() to construct.
  private ActivitiesTagsServiceFilterReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActivitiesTagsServiceFilterReq() {
    isActive_ = 0;
    sortOrder_ = 0;
    sortKey_ = 0;
    entityUuid_ = "";
    status_ = 0;
    name_ = "";
    code_ = "";
    fgColor_ = "";
    bgColor_ = "";
    isLeaf_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActivitiesTagsServiceFilterReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scailo.sdk.ActivitiesTagsScailoProto.internal_static_Scailo_ActivitiesTagsServiceFilterReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scailo.sdk.ActivitiesTagsScailoProto.internal_static_Scailo_ActivitiesTagsServiceFilterReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scailo.sdk.ActivitiesTagsServiceFilterReq.class, com.scailo.sdk.ActivitiesTagsServiceFilterReq.Builder.class);
  }

  public static final int IS_ACTIVE_FIELD_NUMBER = 1;
  private int isActive_ = 0;
  /**
   * <pre>
   * If true, then returns only active records. If false, then returns only inactive records
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
   * @return The enum numeric value on the wire for isActive.
   */
  @java.lang.Override public int getIsActiveValue() {
    return isActive_;
  }
  /**
   * <pre>
   * If true, then returns only active records. If false, then returns only inactive records
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
   * @return The isActive.
   */
  @java.lang.Override public com.scailo.sdk.BOOL_FILTER getIsActive() {
    com.scailo.sdk.BOOL_FILTER result = com.scailo.sdk.BOOL_FILTER.forNumber(isActive_);
    return result == null ? com.scailo.sdk.BOOL_FILTER.UNRECOGNIZED : result;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private long count_ = 0L;
  /**
   * <pre>
   * The number of records that need to be sent in the response. Returns all records if it is set to -1
   * </pre>
   *
   * <code>int64 count = 2 [json_name = "count", (.buf.validate.field) = { ... }</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }

  public static final int OFFSET_FIELD_NUMBER = 3;
  private long offset_ = 0L;
  /**
   * <pre>
   * The number that need to be offset by before fetching the records
   * </pre>
   *
   * <code>uint64 offset = 3 [json_name = "offset", (.buf.validate.field) = { ... }</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int SORT_ORDER_FIELD_NUMBER = 4;
  private int sortOrder_ = 0;
  /**
   * <pre>
   * The sort order that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
   * @return The enum numeric value on the wire for sortOrder.
   */
  @java.lang.Override public int getSortOrderValue() {
    return sortOrder_;
  }
  /**
   * <pre>
   * The sort order that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
   * @return The sortOrder.
   */
  @java.lang.Override public com.scailo.sdk.SORT_ORDER getSortOrder() {
    com.scailo.sdk.SORT_ORDER result = com.scailo.sdk.SORT_ORDER.forNumber(sortOrder_);
    return result == null ? com.scailo.sdk.SORT_ORDER.UNRECOGNIZED : result;
  }

  public static final int SORT_KEY_FIELD_NUMBER = 5;
  private int sortKey_ = 0;
  /**
   * <pre>
   * The sort key that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
   * @return The enum numeric value on the wire for sortKey.
   */
  @java.lang.Override public int getSortKeyValue() {
    return sortKey_;
  }
  /**
   * <pre>
   * The sort key that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
   * @return The sortKey.
   */
  @java.lang.Override public com.scailo.sdk.ACTIVITY_TAG_SORT_KEY getSortKey() {
    com.scailo.sdk.ACTIVITY_TAG_SORT_KEY result = com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.forNumber(sortKey_);
    return result == null ? com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.UNRECOGNIZED : result;
  }

  public static final int CREATION_TIMESTAMP_START_FIELD_NUMBER = 101;
  private long creationTimestampStart_ = 0L;
  /**
   * <pre>
   * The minimum timestamp that needs to be considered to filter by creation
   * </pre>
   *
   * <code>uint64 creation_timestamp_start = 101 [json_name = "creationTimestampStart"];</code>
   * @return The creationTimestampStart.
   */
  @java.lang.Override
  public long getCreationTimestampStart() {
    return creationTimestampStart_;
  }

  public static final int CREATION_TIMESTAMP_END_FIELD_NUMBER = 102;
  private long creationTimestampEnd_ = 0L;
  /**
   * <pre>
   * The maximum timestamp that needs to be considered to filter by creation
   * </pre>
   *
   * <code>uint64 creation_timestamp_end = 102 [json_name = "creationTimestampEnd"];</code>
   * @return The creationTimestampEnd.
   */
  @java.lang.Override
  public long getCreationTimestampEnd() {
    return creationTimestampEnd_;
  }

  public static final int MODIFICATION_TIMESTAMP_START_FIELD_NUMBER = 103;
  private long modificationTimestampStart_ = 0L;
  /**
   * <pre>
   * The minimum timestamp that needs to be considered to filter by modification
   * </pre>
   *
   * <code>uint64 modification_timestamp_start = 103 [json_name = "modificationTimestampStart"];</code>
   * @return The modificationTimestampStart.
   */
  @java.lang.Override
  public long getModificationTimestampStart() {
    return modificationTimestampStart_;
  }

  public static final int MODIFICATION_TIMESTAMP_END_FIELD_NUMBER = 104;
  private long modificationTimestampEnd_ = 0L;
  /**
   * <pre>
   * The maximum timestamp that needs to be considered to filter by modification
   * </pre>
   *
   * <code>uint64 modification_timestamp_end = 104 [json_name = "modificationTimestampEnd"];</code>
   * @return The modificationTimestampEnd.
   */
  @java.lang.Override
  public long getModificationTimestampEnd() {
    return modificationTimestampEnd_;
  }

  public static final int ENTITY_UUID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entityUuid_ = "";
  /**
   * <pre>
   * The entity UUID that is to be used to filter records
   * </pre>
   *
   * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
   * @return The entityUuid.
   */
  @java.lang.Override
  public java.lang.String getEntityUuid() {
    java.lang.Object ref = entityUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The entity UUID that is to be used to filter records
   * </pre>
   *
   * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
   * @return The bytes for entityUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityUuidBytes() {
    java.lang.Object ref = entityUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 10;
  private int status_ = 0;
  /**
   * <pre>
   * The status of this activity tag
   * </pre>
   *
   * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * The status of this activity tag
   * </pre>
   *
   * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.scailo.sdk.STANDARD_LIFECYCLE_STATUS getStatus() {
    com.scailo.sdk.STANDARD_LIFECYCLE_STATUS result = com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.forNumber(status_);
    return result == null ? com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.UNRECOGNIZED : result;
  }

  public static final int APPROVED_ON_START_FIELD_NUMBER = 11;
  private long approvedOnStart_ = 0L;
  /**
   * <pre>
   * The start range of approved timestamp
   * </pre>
   *
   * <code>uint64 approved_on_start = 11 [json_name = "approvedOnStart"];</code>
   * @return The approvedOnStart.
   */
  @java.lang.Override
  public long getApprovedOnStart() {
    return approvedOnStart_;
  }

  public static final int APPROVED_ON_END_FIELD_NUMBER = 12;
  private long approvedOnEnd_ = 0L;
  /**
   * <pre>
   * The end range of approved timestamp
   * </pre>
   *
   * <code>uint64 approved_on_end = 12 [json_name = "approvedOnEnd"];</code>
   * @return The approvedOnEnd.
   */
  @java.lang.Override
  public long getApprovedOnEnd() {
    return approvedOnEnd_;
  }

  public static final int APPROVED_BY_USER_ID_FIELD_NUMBER = 13;
  private long approvedByUserId_ = 0L;
  /**
   * <pre>
   * The ID of the approver
   * </pre>
   *
   * <code>uint64 approved_by_user_id = 13 [json_name = "approvedByUserId"];</code>
   * @return The approvedByUserId.
   */
  @java.lang.Override
  public long getApprovedByUserId() {
    return approvedByUserId_;
  }

  public static final int APPROVER_ROLE_ID_FIELD_NUMBER = 14;
  private long approverRoleId_ = 0L;
  /**
   * <pre>
   * The role ID of the approver
   * </pre>
   *
   * <code>uint64 approver_role_id = 14 [json_name = "approverRoleId"];</code>
   * @return The approverRoleId.
   */
  @java.lang.Override
  public long getApproverRoleId() {
    return approverRoleId_;
  }

  public static final int NAME_FIELD_NUMBER = 20;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The name of the activity tag
   * </pre>
   *
   * <code>string name = 20 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the activity tag
   * </pre>
   *
   * <code>string name = 20 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 21;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * The unique code by which the activity tag is classified
   * </pre>
   *
   * <code>string code = 21 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique code by which the activity tag is classified
   * </pre>
   *
   * <code>string code = 21 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FG_COLOR_FIELD_NUMBER = 22;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fgColor_ = "";
  /**
   * <pre>
   * The color of the text that is displayed for easy recognition
   * </pre>
   *
   * <code>string fg_color = 22 [json_name = "fgColor"];</code>
   * @return The fgColor.
   */
  @java.lang.Override
  public java.lang.String getFgColor() {
    java.lang.Object ref = fgColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fgColor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The color of the text that is displayed for easy recognition
   * </pre>
   *
   * <code>string fg_color = 22 [json_name = "fgColor"];</code>
   * @return The bytes for fgColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFgColorBytes() {
    java.lang.Object ref = fgColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fgColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BG_COLOR_FIELD_NUMBER = 23;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bgColor_ = "";
  /**
   * <pre>
   * The background color that is displayed for easy recognition
   * </pre>
   *
   * <code>string bg_color = 23 [json_name = "bgColor"];</code>
   * @return The bgColor.
   */
  @java.lang.Override
  public java.lang.String getBgColor() {
    java.lang.Object ref = bgColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bgColor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The background color that is displayed for easy recognition
   * </pre>
   *
   * <code>string bg_color = 23 [json_name = "bgColor"];</code>
   * @return The bytes for bgColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBgColorBytes() {
    java.lang.Object ref = bgColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bgColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_ACTIVITY_TAG_ID_FIELD_NUMBER = 26;
  private long parentActivityTagId_ = 0L;
  /**
   * <pre>
   * The ID of the associated non-leaf parent activity tag (0, if the first activity tag that is being created is a leaf activity tag)
   * </pre>
   *
   * <code>uint64 parent_activity_tag_id = 26 [json_name = "parentActivityTagId"];</code>
   * @return The parentActivityTagId.
   */
  @java.lang.Override
  public long getParentActivityTagId() {
    return parentActivityTagId_;
  }

  public static final int IS_LEAF_FIELD_NUMBER = 27;
  private int isLeaf_ = 0;
  /**
   * <pre>
   * Filter with the given leaf property
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
   * @return The enum numeric value on the wire for isLeaf.
   */
  @java.lang.Override public int getIsLeafValue() {
    return isLeaf_;
  }
  /**
   * <pre>
   * Filter with the given leaf property
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
   * @return The isLeaf.
   */
  @java.lang.Override public com.scailo.sdk.BOOL_FILTER getIsLeaf() {
    com.scailo.sdk.BOOL_FILTER result = com.scailo.sdk.BOOL_FILTER.forNumber(isLeaf_);
    return result == null ? com.scailo.sdk.BOOL_FILTER.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isActive_ != com.scailo.sdk.BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, isActive_);
    }
    if (count_ != 0L) {
      output.writeInt64(2, count_);
    }
    if (offset_ != 0L) {
      output.writeUInt64(3, offset_);
    }
    if (sortOrder_ != com.scailo.sdk.SORT_ORDER.ASCENDING_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, sortOrder_);
    }
    if (sortKey_ != com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.ACTIVITY_TAG_SORT_KEY_ID_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, sortKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityUuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, entityUuid_);
    }
    if (status_ != com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.ANY_UNSPECIFIED.getNumber()) {
      output.writeEnum(10, status_);
    }
    if (approvedOnStart_ != 0L) {
      output.writeUInt64(11, approvedOnStart_);
    }
    if (approvedOnEnd_ != 0L) {
      output.writeUInt64(12, approvedOnEnd_);
    }
    if (approvedByUserId_ != 0L) {
      output.writeUInt64(13, approvedByUserId_);
    }
    if (approverRoleId_ != 0L) {
      output.writeUInt64(14, approverRoleId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 21, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fgColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 22, fgColor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bgColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 23, bgColor_);
    }
    if (parentActivityTagId_ != 0L) {
      output.writeUInt64(26, parentActivityTagId_);
    }
    if (isLeaf_ != com.scailo.sdk.BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED.getNumber()) {
      output.writeEnum(27, isLeaf_);
    }
    if (creationTimestampStart_ != 0L) {
      output.writeUInt64(101, creationTimestampStart_);
    }
    if (creationTimestampEnd_ != 0L) {
      output.writeUInt64(102, creationTimestampEnd_);
    }
    if (modificationTimestampStart_ != 0L) {
      output.writeUInt64(103, modificationTimestampStart_);
    }
    if (modificationTimestampEnd_ != 0L) {
      output.writeUInt64(104, modificationTimestampEnd_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isActive_ != com.scailo.sdk.BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, isActive_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, count_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, offset_);
    }
    if (sortOrder_ != com.scailo.sdk.SORT_ORDER.ASCENDING_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, sortOrder_);
    }
    if (sortKey_ != com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.ACTIVITY_TAG_SORT_KEY_ID_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, sortKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityUuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, entityUuid_);
    }
    if (status_ != com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.ANY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, status_);
    }
    if (approvedOnStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(11, approvedOnStart_);
    }
    if (approvedOnEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(12, approvedOnEnd_);
    }
    if (approvedByUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, approvedByUserId_);
    }
    if (approverRoleId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, approverRoleId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fgColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, fgColor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bgColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, bgColor_);
    }
    if (parentActivityTagId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(26, parentActivityTagId_);
    }
    if (isLeaf_ != com.scailo.sdk.BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(27, isLeaf_);
    }
    if (creationTimestampStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(101, creationTimestampStart_);
    }
    if (creationTimestampEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(102, creationTimestampEnd_);
    }
    if (modificationTimestampStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(103, modificationTimestampStart_);
    }
    if (modificationTimestampEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(104, modificationTimestampEnd_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scailo.sdk.ActivitiesTagsServiceFilterReq)) {
      return super.equals(obj);
    }
    com.scailo.sdk.ActivitiesTagsServiceFilterReq other = (com.scailo.sdk.ActivitiesTagsServiceFilterReq) obj;

    if (isActive_ != other.isActive_) return false;
    if (getCount()
        != other.getCount()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (sortOrder_ != other.sortOrder_) return false;
    if (sortKey_ != other.sortKey_) return false;
    if (getCreationTimestampStart()
        != other.getCreationTimestampStart()) return false;
    if (getCreationTimestampEnd()
        != other.getCreationTimestampEnd()) return false;
    if (getModificationTimestampStart()
        != other.getModificationTimestampStart()) return false;
    if (getModificationTimestampEnd()
        != other.getModificationTimestampEnd()) return false;
    if (!getEntityUuid()
        .equals(other.getEntityUuid())) return false;
    if (status_ != other.status_) return false;
    if (getApprovedOnStart()
        != other.getApprovedOnStart()) return false;
    if (getApprovedOnEnd()
        != other.getApprovedOnEnd()) return false;
    if (getApprovedByUserId()
        != other.getApprovedByUserId()) return false;
    if (getApproverRoleId()
        != other.getApproverRoleId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getFgColor()
        .equals(other.getFgColor())) return false;
    if (!getBgColor()
        .equals(other.getBgColor())) return false;
    if (getParentActivityTagId()
        != other.getParentActivityTagId()) return false;
    if (isLeaf_ != other.isLeaf_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + isActive_;
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + SORT_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + sortOrder_;
    hash = (37 * hash) + SORT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + sortKey_;
    hash = (37 * hash) + CREATION_TIMESTAMP_START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreationTimestampStart());
    hash = (37 * hash) + CREATION_TIMESTAMP_END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreationTimestampEnd());
    hash = (37 * hash) + MODIFICATION_TIMESTAMP_START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getModificationTimestampStart());
    hash = (37 * hash) + MODIFICATION_TIMESTAMP_END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getModificationTimestampEnd());
    hash = (37 * hash) + ENTITY_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getEntityUuid().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + APPROVED_ON_START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApprovedOnStart());
    hash = (37 * hash) + APPROVED_ON_END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApprovedOnEnd());
    hash = (37 * hash) + APPROVED_BY_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApprovedByUserId());
    hash = (37 * hash) + APPROVER_ROLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApproverRoleId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + FG_COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getFgColor().hashCode();
    hash = (37 * hash) + BG_COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getBgColor().hashCode();
    hash = (37 * hash) + PARENT_ACTIVITY_TAG_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentActivityTagId());
    hash = (37 * hash) + IS_LEAF_FIELD_NUMBER;
    hash = (53 * hash) + isLeaf_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scailo.sdk.ActivitiesTagsServiceFilterReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Describes the base request payload of a filter search
   * </pre>
   *
   * Protobuf type {@code Scailo.ActivitiesTagsServiceFilterReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Scailo.ActivitiesTagsServiceFilterReq)
      com.scailo.sdk.ActivitiesTagsServiceFilterReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scailo.sdk.ActivitiesTagsScailoProto.internal_static_Scailo_ActivitiesTagsServiceFilterReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scailo.sdk.ActivitiesTagsScailoProto.internal_static_Scailo_ActivitiesTagsServiceFilterReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scailo.sdk.ActivitiesTagsServiceFilterReq.class, com.scailo.sdk.ActivitiesTagsServiceFilterReq.Builder.class);
    }

    // Construct using com.scailo.sdk.ActivitiesTagsServiceFilterReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isActive_ = 0;
      count_ = 0L;
      offset_ = 0L;
      sortOrder_ = 0;
      sortKey_ = 0;
      creationTimestampStart_ = 0L;
      creationTimestampEnd_ = 0L;
      modificationTimestampStart_ = 0L;
      modificationTimestampEnd_ = 0L;
      entityUuid_ = "";
      status_ = 0;
      approvedOnStart_ = 0L;
      approvedOnEnd_ = 0L;
      approvedByUserId_ = 0L;
      approverRoleId_ = 0L;
      name_ = "";
      code_ = "";
      fgColor_ = "";
      bgColor_ = "";
      parentActivityTagId_ = 0L;
      isLeaf_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scailo.sdk.ActivitiesTagsScailoProto.internal_static_Scailo_ActivitiesTagsServiceFilterReq_descriptor;
    }

    @java.lang.Override
    public com.scailo.sdk.ActivitiesTagsServiceFilterReq getDefaultInstanceForType() {
      return com.scailo.sdk.ActivitiesTagsServiceFilterReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.scailo.sdk.ActivitiesTagsServiceFilterReq build() {
      com.scailo.sdk.ActivitiesTagsServiceFilterReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scailo.sdk.ActivitiesTagsServiceFilterReq buildPartial() {
      com.scailo.sdk.ActivitiesTagsServiceFilterReq result = new com.scailo.sdk.ActivitiesTagsServiceFilterReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scailo.sdk.ActivitiesTagsServiceFilterReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isActive_ = isActive_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.count_ = count_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.offset_ = offset_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sortOrder_ = sortOrder_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sortKey_ = sortKey_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.creationTimestampStart_ = creationTimestampStart_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.creationTimestampEnd_ = creationTimestampEnd_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.modificationTimestampStart_ = modificationTimestampStart_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.modificationTimestampEnd_ = modificationTimestampEnd_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.entityUuid_ = entityUuid_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.approvedOnStart_ = approvedOnStart_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.approvedOnEnd_ = approvedOnEnd_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.approvedByUserId_ = approvedByUserId_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.approverRoleId_ = approverRoleId_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.fgColor_ = fgColor_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.bgColor_ = bgColor_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.parentActivityTagId_ = parentActivityTagId_;
      }
      if (((from_bitField0_ & 0x00100000) != 0)) {
        result.isLeaf_ = isLeaf_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scailo.sdk.ActivitiesTagsServiceFilterReq) {
        return mergeFrom((com.scailo.sdk.ActivitiesTagsServiceFilterReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scailo.sdk.ActivitiesTagsServiceFilterReq other) {
      if (other == com.scailo.sdk.ActivitiesTagsServiceFilterReq.getDefaultInstance()) return this;
      if (other.isActive_ != 0) {
        setIsActiveValue(other.getIsActiveValue());
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (other.sortOrder_ != 0) {
        setSortOrderValue(other.getSortOrderValue());
      }
      if (other.sortKey_ != 0) {
        setSortKeyValue(other.getSortKeyValue());
      }
      if (other.getCreationTimestampStart() != 0L) {
        setCreationTimestampStart(other.getCreationTimestampStart());
      }
      if (other.getCreationTimestampEnd() != 0L) {
        setCreationTimestampEnd(other.getCreationTimestampEnd());
      }
      if (other.getModificationTimestampStart() != 0L) {
        setModificationTimestampStart(other.getModificationTimestampStart());
      }
      if (other.getModificationTimestampEnd() != 0L) {
        setModificationTimestampEnd(other.getModificationTimestampEnd());
      }
      if (!other.getEntityUuid().isEmpty()) {
        entityUuid_ = other.entityUuid_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getApprovedOnStart() != 0L) {
        setApprovedOnStart(other.getApprovedOnStart());
      }
      if (other.getApprovedOnEnd() != 0L) {
        setApprovedOnEnd(other.getApprovedOnEnd());
      }
      if (other.getApprovedByUserId() != 0L) {
        setApprovedByUserId(other.getApprovedByUserId());
      }
      if (other.getApproverRoleId() != 0L) {
        setApproverRoleId(other.getApproverRoleId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00008000;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00010000;
        onChanged();
      }
      if (!other.getFgColor().isEmpty()) {
        fgColor_ = other.fgColor_;
        bitField0_ |= 0x00020000;
        onChanged();
      }
      if (!other.getBgColor().isEmpty()) {
        bgColor_ = other.bgColor_;
        bitField0_ |= 0x00040000;
        onChanged();
      }
      if (other.getParentActivityTagId() != 0L) {
        setParentActivityTagId(other.getParentActivityTagId());
      }
      if (other.isLeaf_ != 0) {
        setIsLeafValue(other.getIsLeafValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isActive_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              count_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              offset_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              sortOrder_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              sortKey_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 66: {
              entityUuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 66
            case 80: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000400;
              break;
            } // case 80
            case 88: {
              approvedOnStart_ = input.readUInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 88
            case 96: {
              approvedOnEnd_ = input.readUInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 96
            case 104: {
              approvedByUserId_ = input.readUInt64();
              bitField0_ |= 0x00002000;
              break;
            } // case 104
            case 112: {
              approverRoleId_ = input.readUInt64();
              bitField0_ |= 0x00004000;
              break;
            } // case 112
            case 162: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00008000;
              break;
            } // case 162
            case 170: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00010000;
              break;
            } // case 170
            case 178: {
              fgColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00020000;
              break;
            } // case 178
            case 186: {
              bgColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00040000;
              break;
            } // case 186
            case 208: {
              parentActivityTagId_ = input.readUInt64();
              bitField0_ |= 0x00080000;
              break;
            } // case 208
            case 216: {
              isLeaf_ = input.readEnum();
              bitField0_ |= 0x00100000;
              break;
            } // case 216
            case 808: {
              creationTimestampStart_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 808
            case 816: {
              creationTimestampEnd_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 816
            case 824: {
              modificationTimestampStart_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 824
            case 832: {
              modificationTimestampEnd_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 832
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int isActive_ = 0;
    /**
     * <pre>
     * If true, then returns only active records. If false, then returns only inactive records
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
     * @return The enum numeric value on the wire for isActive.
     */
    @java.lang.Override public int getIsActiveValue() {
      return isActive_;
    }
    /**
     * <pre>
     * If true, then returns only active records. If false, then returns only inactive records
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
     * @param value The enum numeric value on the wire for isActive to set.
     * @return This builder for chaining.
     */
    public Builder setIsActiveValue(int value) {
      isActive_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, then returns only active records. If false, then returns only inactive records
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
     * @return The isActive.
     */
    @java.lang.Override
    public com.scailo.sdk.BOOL_FILTER getIsActive() {
      com.scailo.sdk.BOOL_FILTER result = com.scailo.sdk.BOOL_FILTER.forNumber(isActive_);
      return result == null ? com.scailo.sdk.BOOL_FILTER.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * If true, then returns only active records. If false, then returns only inactive records
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
     * @param value The isActive to set.
     * @return This builder for chaining.
     */
    public Builder setIsActive(com.scailo.sdk.BOOL_FILTER value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      isActive_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, then returns only active records. If false, then returns only inactive records
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsActive() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isActive_ = 0;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <pre>
     * The number of records that need to be sent in the response. Returns all records if it is set to -1
     * </pre>
     *
     * <code>int64 count = 2 [json_name = "count", (.buf.validate.field) = { ... }</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * The number of records that need to be sent in the response. Returns all records if it is set to -1
     * </pre>
     *
     * <code>int64 count = 2 [json_name = "count", (.buf.validate.field) = { ... }</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {
      
      count_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of records that need to be sent in the response. Returns all records if it is set to -1
     * </pre>
     *
     * <code>int64 count = 2 [json_name = "count", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      count_ = 0L;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <pre>
     * The number that need to be offset by before fetching the records
     * </pre>
     *
     * <code>uint64 offset = 3 [json_name = "offset", (.buf.validate.field) = { ... }</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <pre>
     * The number that need to be offset by before fetching the records
     * </pre>
     *
     * <code>uint64 offset = 3 [json_name = "offset", (.buf.validate.field) = { ... }</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number that need to be offset by before fetching the records
     * </pre>
     *
     * <code>uint64 offset = 3 [json_name = "offset", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      offset_ = 0L;
      onChanged();
      return this;
    }

    private int sortOrder_ = 0;
    /**
     * <pre>
     * The sort order that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
     * @return The enum numeric value on the wire for sortOrder.
     */
    @java.lang.Override public int getSortOrderValue() {
      return sortOrder_;
    }
    /**
     * <pre>
     * The sort order that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
     * @param value The enum numeric value on the wire for sortOrder to set.
     * @return This builder for chaining.
     */
    public Builder setSortOrderValue(int value) {
      sortOrder_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sort order that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
     * @return The sortOrder.
     */
    @java.lang.Override
    public com.scailo.sdk.SORT_ORDER getSortOrder() {
      com.scailo.sdk.SORT_ORDER result = com.scailo.sdk.SORT_ORDER.forNumber(sortOrder_);
      return result == null ? com.scailo.sdk.SORT_ORDER.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The sort order that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
     * @param value The sortOrder to set.
     * @return This builder for chaining.
     */
    public Builder setSortOrder(com.scailo.sdk.SORT_ORDER value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      sortOrder_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sort order that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSortOrder() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sortOrder_ = 0;
      onChanged();
      return this;
    }

    private int sortKey_ = 0;
    /**
     * <pre>
     * The sort key that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
     * @return The enum numeric value on the wire for sortKey.
     */
    @java.lang.Override public int getSortKeyValue() {
      return sortKey_;
    }
    /**
     * <pre>
     * The sort key that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
     * @param value The enum numeric value on the wire for sortKey to set.
     * @return This builder for chaining.
     */
    public Builder setSortKeyValue(int value) {
      sortKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sort key that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
     * @return The sortKey.
     */
    @java.lang.Override
    public com.scailo.sdk.ACTIVITY_TAG_SORT_KEY getSortKey() {
      com.scailo.sdk.ACTIVITY_TAG_SORT_KEY result = com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.forNumber(sortKey_);
      return result == null ? com.scailo.sdk.ACTIVITY_TAG_SORT_KEY.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The sort key that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
     * @param value The sortKey to set.
     * @return This builder for chaining.
     */
    public Builder setSortKey(com.scailo.sdk.ACTIVITY_TAG_SORT_KEY value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      sortKey_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The sort key that is to be used to fetch the pagination response
     * </pre>
     *
     * <code>.Scailo.ACTIVITY_TAG_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSortKey() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sortKey_ = 0;
      onChanged();
      return this;
    }

    private long creationTimestampStart_ ;
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_start = 101 [json_name = "creationTimestampStart"];</code>
     * @return The creationTimestampStart.
     */
    @java.lang.Override
    public long getCreationTimestampStart() {
      return creationTimestampStart_;
    }
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_start = 101 [json_name = "creationTimestampStart"];</code>
     * @param value The creationTimestampStart to set.
     * @return This builder for chaining.
     */
    public Builder setCreationTimestampStart(long value) {
      
      creationTimestampStart_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_start = 101 [json_name = "creationTimestampStart"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreationTimestampStart() {
      bitField0_ = (bitField0_ & ~0x00000020);
      creationTimestampStart_ = 0L;
      onChanged();
      return this;
    }

    private long creationTimestampEnd_ ;
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_end = 102 [json_name = "creationTimestampEnd"];</code>
     * @return The creationTimestampEnd.
     */
    @java.lang.Override
    public long getCreationTimestampEnd() {
      return creationTimestampEnd_;
    }
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_end = 102 [json_name = "creationTimestampEnd"];</code>
     * @param value The creationTimestampEnd to set.
     * @return This builder for chaining.
     */
    public Builder setCreationTimestampEnd(long value) {
      
      creationTimestampEnd_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by creation
     * </pre>
     *
     * <code>uint64 creation_timestamp_end = 102 [json_name = "creationTimestampEnd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreationTimestampEnd() {
      bitField0_ = (bitField0_ & ~0x00000040);
      creationTimestampEnd_ = 0L;
      onChanged();
      return this;
    }

    private long modificationTimestampStart_ ;
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_start = 103 [json_name = "modificationTimestampStart"];</code>
     * @return The modificationTimestampStart.
     */
    @java.lang.Override
    public long getModificationTimestampStart() {
      return modificationTimestampStart_;
    }
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_start = 103 [json_name = "modificationTimestampStart"];</code>
     * @param value The modificationTimestampStart to set.
     * @return This builder for chaining.
     */
    public Builder setModificationTimestampStart(long value) {
      
      modificationTimestampStart_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The minimum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_start = 103 [json_name = "modificationTimestampStart"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModificationTimestampStart() {
      bitField0_ = (bitField0_ & ~0x00000080);
      modificationTimestampStart_ = 0L;
      onChanged();
      return this;
    }

    private long modificationTimestampEnd_ ;
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_end = 104 [json_name = "modificationTimestampEnd"];</code>
     * @return The modificationTimestampEnd.
     */
    @java.lang.Override
    public long getModificationTimestampEnd() {
      return modificationTimestampEnd_;
    }
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_end = 104 [json_name = "modificationTimestampEnd"];</code>
     * @param value The modificationTimestampEnd to set.
     * @return This builder for chaining.
     */
    public Builder setModificationTimestampEnd(long value) {
      
      modificationTimestampEnd_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum timestamp that needs to be considered to filter by modification
     * </pre>
     *
     * <code>uint64 modification_timestamp_end = 104 [json_name = "modificationTimestampEnd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModificationTimestampEnd() {
      bitField0_ = (bitField0_ & ~0x00000100);
      modificationTimestampEnd_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object entityUuid_ = "";
    /**
     * <pre>
     * The entity UUID that is to be used to filter records
     * </pre>
     *
     * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
     * @return The entityUuid.
     */
    public java.lang.String getEntityUuid() {
      java.lang.Object ref = entityUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The entity UUID that is to be used to filter records
     * </pre>
     *
     * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
     * @return The bytes for entityUuid.
     */
    public com.google.protobuf.ByteString
        getEntityUuidBytes() {
      java.lang.Object ref = entityUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The entity UUID that is to be used to filter records
     * </pre>
     *
     * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
     * @param value The entityUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEntityUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entityUuid_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The entity UUID that is to be used to filter records
     * </pre>
     *
     * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityUuid() {
      entityUuid_ = getDefaultInstance().getEntityUuid();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The entity UUID that is to be used to filter records
     * </pre>
     *
     * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
     * @param value The bytes for entityUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEntityUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entityUuid_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * The status of this activity tag
     * </pre>
     *
     * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * The status of this activity tag
     * </pre>
     *
     * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The status of this activity tag
     * </pre>
     *
     * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.scailo.sdk.STANDARD_LIFECYCLE_STATUS getStatus() {
      com.scailo.sdk.STANDARD_LIFECYCLE_STATUS result = com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.forNumber(status_);
      return result == null ? com.scailo.sdk.STANDARD_LIFECYCLE_STATUS.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The status of this activity tag
     * </pre>
     *
     * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.scailo.sdk.STANDARD_LIFECYCLE_STATUS value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000400;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The status of this activity tag
     * </pre>
     *
     * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000400);
      status_ = 0;
      onChanged();
      return this;
    }

    private long approvedOnStart_ ;
    /**
     * <pre>
     * The start range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_start = 11 [json_name = "approvedOnStart"];</code>
     * @return The approvedOnStart.
     */
    @java.lang.Override
    public long getApprovedOnStart() {
      return approvedOnStart_;
    }
    /**
     * <pre>
     * The start range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_start = 11 [json_name = "approvedOnStart"];</code>
     * @param value The approvedOnStart to set.
     * @return This builder for chaining.
     */
    public Builder setApprovedOnStart(long value) {
      
      approvedOnStart_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The start range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_start = 11 [json_name = "approvedOnStart"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovedOnStart() {
      bitField0_ = (bitField0_ & ~0x00000800);
      approvedOnStart_ = 0L;
      onChanged();
      return this;
    }

    private long approvedOnEnd_ ;
    /**
     * <pre>
     * The end range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_end = 12 [json_name = "approvedOnEnd"];</code>
     * @return The approvedOnEnd.
     */
    @java.lang.Override
    public long getApprovedOnEnd() {
      return approvedOnEnd_;
    }
    /**
     * <pre>
     * The end range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_end = 12 [json_name = "approvedOnEnd"];</code>
     * @param value The approvedOnEnd to set.
     * @return This builder for chaining.
     */
    public Builder setApprovedOnEnd(long value) {
      
      approvedOnEnd_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The end range of approved timestamp
     * </pre>
     *
     * <code>uint64 approved_on_end = 12 [json_name = "approvedOnEnd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovedOnEnd() {
      bitField0_ = (bitField0_ & ~0x00001000);
      approvedOnEnd_ = 0L;
      onChanged();
      return this;
    }

    private long approvedByUserId_ ;
    /**
     * <pre>
     * The ID of the approver
     * </pre>
     *
     * <code>uint64 approved_by_user_id = 13 [json_name = "approvedByUserId"];</code>
     * @return The approvedByUserId.
     */
    @java.lang.Override
    public long getApprovedByUserId() {
      return approvedByUserId_;
    }
    /**
     * <pre>
     * The ID of the approver
     * </pre>
     *
     * <code>uint64 approved_by_user_id = 13 [json_name = "approvedByUserId"];</code>
     * @param value The approvedByUserId to set.
     * @return This builder for chaining.
     */
    public Builder setApprovedByUserId(long value) {
      
      approvedByUserId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the approver
     * </pre>
     *
     * <code>uint64 approved_by_user_id = 13 [json_name = "approvedByUserId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovedByUserId() {
      bitField0_ = (bitField0_ & ~0x00002000);
      approvedByUserId_ = 0L;
      onChanged();
      return this;
    }

    private long approverRoleId_ ;
    /**
     * <pre>
     * The role ID of the approver
     * </pre>
     *
     * <code>uint64 approver_role_id = 14 [json_name = "approverRoleId"];</code>
     * @return The approverRoleId.
     */
    @java.lang.Override
    public long getApproverRoleId() {
      return approverRoleId_;
    }
    /**
     * <pre>
     * The role ID of the approver
     * </pre>
     *
     * <code>uint64 approver_role_id = 14 [json_name = "approverRoleId"];</code>
     * @param value The approverRoleId to set.
     * @return This builder for chaining.
     */
    public Builder setApproverRoleId(long value) {
      
      approverRoleId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The role ID of the approver
     * </pre>
     *
     * <code>uint64 approver_role_id = 14 [json_name = "approverRoleId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApproverRoleId() {
      bitField0_ = (bitField0_ & ~0x00004000);
      approverRoleId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name of the activity tag
     * </pre>
     *
     * <code>string name = 20 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the activity tag
     * </pre>
     *
     * <code>string name = 20 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the activity tag
     * </pre>
     *
     * <code>string name = 20 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the activity tag
     * </pre>
     *
     * <code>string name = 20 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the activity tag
     * </pre>
     *
     * <code>string name = 20 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * The unique code by which the activity tag is classified
     * </pre>
     *
     * <code>string code = 21 [json_name = "code"];</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique code by which the activity tag is classified
     * </pre>
     *
     * <code>string code = 21 [json_name = "code"];</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique code by which the activity tag is classified
     * </pre>
     *
     * <code>string code = 21 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique code by which the activity tag is classified
     * </pre>
     *
     * <code>string code = 21 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00010000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique code by which the activity tag is classified
     * </pre>
     *
     * <code>string code = 21 [json_name = "code"];</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }

    private java.lang.Object fgColor_ = "";
    /**
     * <pre>
     * The color of the text that is displayed for easy recognition
     * </pre>
     *
     * <code>string fg_color = 22 [json_name = "fgColor"];</code>
     * @return The fgColor.
     */
    public java.lang.String getFgColor() {
      java.lang.Object ref = fgColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fgColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The color of the text that is displayed for easy recognition
     * </pre>
     *
     * <code>string fg_color = 22 [json_name = "fgColor"];</code>
     * @return The bytes for fgColor.
     */
    public com.google.protobuf.ByteString
        getFgColorBytes() {
      java.lang.Object ref = fgColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fgColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The color of the text that is displayed for easy recognition
     * </pre>
     *
     * <code>string fg_color = 22 [json_name = "fgColor"];</code>
     * @param value The fgColor to set.
     * @return This builder for chaining.
     */
    public Builder setFgColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fgColor_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The color of the text that is displayed for easy recognition
     * </pre>
     *
     * <code>string fg_color = 22 [json_name = "fgColor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFgColor() {
      fgColor_ = getDefaultInstance().getFgColor();
      bitField0_ = (bitField0_ & ~0x00020000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The color of the text that is displayed for easy recognition
     * </pre>
     *
     * <code>string fg_color = 22 [json_name = "fgColor"];</code>
     * @param value The bytes for fgColor to set.
     * @return This builder for chaining.
     */
    public Builder setFgColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fgColor_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }

    private java.lang.Object bgColor_ = "";
    /**
     * <pre>
     * The background color that is displayed for easy recognition
     * </pre>
     *
     * <code>string bg_color = 23 [json_name = "bgColor"];</code>
     * @return The bgColor.
     */
    public java.lang.String getBgColor() {
      java.lang.Object ref = bgColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bgColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The background color that is displayed for easy recognition
     * </pre>
     *
     * <code>string bg_color = 23 [json_name = "bgColor"];</code>
     * @return The bytes for bgColor.
     */
    public com.google.protobuf.ByteString
        getBgColorBytes() {
      java.lang.Object ref = bgColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bgColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The background color that is displayed for easy recognition
     * </pre>
     *
     * <code>string bg_color = 23 [json_name = "bgColor"];</code>
     * @param value The bgColor to set.
     * @return This builder for chaining.
     */
    public Builder setBgColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bgColor_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The background color that is displayed for easy recognition
     * </pre>
     *
     * <code>string bg_color = 23 [json_name = "bgColor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBgColor() {
      bgColor_ = getDefaultInstance().getBgColor();
      bitField0_ = (bitField0_ & ~0x00040000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The background color that is displayed for easy recognition
     * </pre>
     *
     * <code>string bg_color = 23 [json_name = "bgColor"];</code>
     * @param value The bytes for bgColor to set.
     * @return This builder for chaining.
     */
    public Builder setBgColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bgColor_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }

    private long parentActivityTagId_ ;
    /**
     * <pre>
     * The ID of the associated non-leaf parent activity tag (0, if the first activity tag that is being created is a leaf activity tag)
     * </pre>
     *
     * <code>uint64 parent_activity_tag_id = 26 [json_name = "parentActivityTagId"];</code>
     * @return The parentActivityTagId.
     */
    @java.lang.Override
    public long getParentActivityTagId() {
      return parentActivityTagId_;
    }
    /**
     * <pre>
     * The ID of the associated non-leaf parent activity tag (0, if the first activity tag that is being created is a leaf activity tag)
     * </pre>
     *
     * <code>uint64 parent_activity_tag_id = 26 [json_name = "parentActivityTagId"];</code>
     * @param value The parentActivityTagId to set.
     * @return This builder for chaining.
     */
    public Builder setParentActivityTagId(long value) {
      
      parentActivityTagId_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the associated non-leaf parent activity tag (0, if the first activity tag that is being created is a leaf activity tag)
     * </pre>
     *
     * <code>uint64 parent_activity_tag_id = 26 [json_name = "parentActivityTagId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParentActivityTagId() {
      bitField0_ = (bitField0_ & ~0x00080000);
      parentActivityTagId_ = 0L;
      onChanged();
      return this;
    }

    private int isLeaf_ = 0;
    /**
     * <pre>
     * Filter with the given leaf property
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
     * @return The enum numeric value on the wire for isLeaf.
     */
    @java.lang.Override public int getIsLeafValue() {
      return isLeaf_;
    }
    /**
     * <pre>
     * Filter with the given leaf property
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
     * @param value The enum numeric value on the wire for isLeaf to set.
     * @return This builder for chaining.
     */
    public Builder setIsLeafValue(int value) {
      isLeaf_ = value;
      bitField0_ |= 0x00100000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter with the given leaf property
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
     * @return The isLeaf.
     */
    @java.lang.Override
    public com.scailo.sdk.BOOL_FILTER getIsLeaf() {
      com.scailo.sdk.BOOL_FILTER result = com.scailo.sdk.BOOL_FILTER.forNumber(isLeaf_);
      return result == null ? com.scailo.sdk.BOOL_FILTER.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Filter with the given leaf property
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
     * @param value The isLeaf to set.
     * @return This builder for chaining.
     */
    public Builder setIsLeaf(com.scailo.sdk.BOOL_FILTER value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00100000;
      isLeaf_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter with the given leaf property
     * </pre>
     *
     * <code>.Scailo.BOOL_FILTER is_leaf = 27 [json_name = "isLeaf"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLeaf() {
      bitField0_ = (bitField0_ & ~0x00100000);
      isLeaf_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Scailo.ActivitiesTagsServiceFilterReq)
  }

  // @@protoc_insertion_point(class_scope:Scailo.ActivitiesTagsServiceFilterReq)
  private static final com.scailo.sdk.ActivitiesTagsServiceFilterReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scailo.sdk.ActivitiesTagsServiceFilterReq();
  }

  public static com.scailo.sdk.ActivitiesTagsServiceFilterReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActivitiesTagsServiceFilterReq>
      PARSER = new com.google.protobuf.AbstractParser<ActivitiesTagsServiceFilterReq>() {
    @java.lang.Override
    public ActivitiesTagsServiceFilterReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActivitiesTagsServiceFilterReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActivitiesTagsServiceFilterReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scailo.sdk.ActivitiesTagsServiceFilterReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

