// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions_codes.scailo.proto

package com.scailo.sdk;

public interface ActionsCodesServiceCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.ActionsCodesServiceCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ActionsCodes a globally unique entity UUID. This will be set at the organization level
   * </pre>
   *
   * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
   * @return The entityUuid.
   */
  java.lang.String getEntityUuid();
  /**
   * <pre>
   * ActionsCodes a globally unique entity UUID. This will be set at the organization level
   * </pre>
   *
   * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
   * @return The bytes for entityUuid.
   */
  com.google.protobuf.ByteString
      getEntityUuidBytes();

  /**
   * <pre>
   * ActionsCodes any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 2 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  java.lang.String getUserComment();
  /**
   * <pre>
   * ActionsCodes any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 2 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  com.google.protobuf.ByteString
      getUserCommentBytes();

  /**
   * <pre>
   * The name of the action code
   * </pre>
   *
   * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the action code
   * </pre>
   *
   * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The unique code by which the action code is classified
   * </pre>
   *
   * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * The unique code by which the action code is classified
   * </pre>
   *
   * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * The color of the text that is displayed for easy recognition
   * </pre>
   *
   * <code>string fg_color = 12 [json_name = "fgColor"];</code>
   * @return The fgColor.
   */
  java.lang.String getFgColor();
  /**
   * <pre>
   * The color of the text that is displayed for easy recognition
   * </pre>
   *
   * <code>string fg_color = 12 [json_name = "fgColor"];</code>
   * @return The bytes for fgColor.
   */
  com.google.protobuf.ByteString
      getFgColorBytes();

  /**
   * <pre>
   * The background color that is displayed for easy recognition
   * </pre>
   *
   * <code>string bg_color = 13 [json_name = "bgColor"];</code>
   * @return The bgColor.
   */
  java.lang.String getBgColor();
  /**
   * <pre>
   * The background color that is displayed for easy recognition
   * </pre>
   *
   * <code>string bg_color = 13 [json_name = "bgColor"];</code>
   * @return The bytes for bgColor.
   */
  com.google.protobuf.ByteString
      getBgColorBytes();

  /**
   * <pre>
   * The ID of the associated non-leaf parent action code (0, if the first action code that is being created is a leaf action code)
   * </pre>
   *
   * <code>uint64 parent_action_code_id = 16 [json_name = "parentActionCodeId", (.buf.validate.field) = { ... }</code>
   * @return The parentActionCodeId.
   */
  long getParentActionCodeId();

  /**
   * <pre>
   * Stores if this is a leaf action code or a non-leaf action code
   * </pre>
   *
   * <code>bool is_leaf = 17 [json_name = "isLeaf"];</code>
   * @return The isLeaf.
   */
  boolean getIsLeaf();

  /**
   * <pre>
   * The description of the action code
   * </pre>
   *
   * <code>string description = 18 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * The description of the action code
   * </pre>
   *
   * <code>string description = 18 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
