// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attendances.scailo.proto

package com.scailo.sdk;

public interface AttendancesServicePaginationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.AttendancesServicePaginationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of records in this payload
   * </pre>
   *
   * <code>uint64 count = 1 [json_name = "count"];</code>
   * @return The count.
   */
  long getCount();

  /**
   * <pre>
   * The number that has been offset before fetching the records. This is the same value that has been sent as part of the pagination request
   * </pre>
   *
   * <code>uint64 offset = 2 [json_name = "offset"];</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <pre>
   * The total number of records that are available
   * </pre>
   *
   * <code>uint64 total = 3 [json_name = "total"];</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <pre>
   * The list of records
   * </pre>
   *
   * <code>repeated .Scailo.Attendance payload = 4 [json_name = "payload"];</code>
   */
  java.util.List<com.scailo.sdk.Attendance> 
      getPayloadList();
  /**
   * <pre>
   * The list of records
   * </pre>
   *
   * <code>repeated .Scailo.Attendance payload = 4 [json_name = "payload"];</code>
   */
  com.scailo.sdk.Attendance getPayload(int index);
  /**
   * <pre>
   * The list of records
   * </pre>
   *
   * <code>repeated .Scailo.Attendance payload = 4 [json_name = "payload"];</code>
   */
  int getPayloadCount();
  /**
   * <pre>
   * The list of records
   * </pre>
   *
   * <code>repeated .Scailo.Attendance payload = 4 [json_name = "payload"];</code>
   */
  java.util.List<? extends com.scailo.sdk.AttendanceOrBuilder> 
      getPayloadOrBuilderList();
  /**
   * <pre>
   * The list of records
   * </pre>
   *
   * <code>repeated .Scailo.Attendance payload = 4 [json_name = "payload"];</code>
   */
  com.scailo.sdk.AttendanceOrBuilder getPayloadOrBuilder(
      int index);
}
