// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the parameters necessary to update a record
 * </pre>
 *
 * Protobuf type {@code Scailo.ClientsServiceUpdateRequest}
 */
public final class ClientsServiceUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Scailo.ClientsServiceUpdateRequest)
    ClientsServiceUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientsServiceUpdateRequest.newBuilder() to construct.
  private ClientsServiceUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientsServiceUpdateRequest() {
    userComment_ = "";
    name_ = "";
    code_ = "";
    email_ = "";
    phone_ = "";
    formData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientsServiceUpdateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scailo.sdk.ClientsScailoProto.internal_static_Scailo_ClientsServiceUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scailo.sdk.ClientsScailoProto.internal_static_Scailo_ClientsServiceUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scailo.sdk.ClientsServiceUpdateRequest.class, com.scailo.sdk.ClientsServiceUpdateRequest.Builder.class);
  }

  public static final int USER_COMMENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userComment_ = "";
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  @java.lang.Override
  public java.lang.String getUserComment() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userComment_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserCommentBytes() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_ = 0L;
  /**
   * <pre>
   * The ID of the record that needs to be updated
   * </pre>
   *
   * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NOTIFY_USERS_FIELD_NUMBER = 3;
  private boolean notifyUsers_ = false;
  /**
   * <pre>
   * Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
   * </pre>
   *
   * <code>bool notify_users = 3 [json_name = "notifyUsers"];</code>
   * @return The notifyUsers.
   */
  @java.lang.Override
  public boolean getNotifyUsers() {
    return notifyUsers_;
  }

  public static final int VAULT_FOLDER_ID_FIELD_NUMBER = 9;
  private long vaultFolderId_ = 0L;
  /**
   * <pre>
   * The associated vault folder ID
   * </pre>
   *
   * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
   * @return The vaultFolderId.
   */
  @java.lang.Override
  public long getVaultFolderId() {
    return vaultFolderId_;
  }

  public static final int NAME_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The name of the client
   * </pre>
   *
   * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the client
   * </pre>
   *
   * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * The unique code by which the client is classified
   * </pre>
   *
   * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique code by which the client is classified
   * </pre>
   *
   * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <pre>
   * The primary email of the client
   * </pre>
   *
   * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The primary email of the client
   * </pre>
   *
   * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phone_ = "";
  /**
   * <pre>
   * The primary contact number of the client
   * </pre>
   *
   * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
   * @return The phone.
   */
  @java.lang.Override
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The primary contact number of the client
   * </pre>
   *
   * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
   * @return The bytes for phone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORM_DATA_FIELD_NUMBER = 30;
  @SuppressWarnings("serial")
  private java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest> formData_;
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  @java.lang.Override
  public java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest> getFormDataList() {
    return formData_;
  }
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder> 
      getFormDataOrBuilderList() {
    return formData_;
  }
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  @java.lang.Override
  public int getFormDataCount() {
    return formData_.size();
  }
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  @java.lang.Override
  public com.scailo.sdk.FormFieldDatumCreateRequest getFormData(int index) {
    return formData_.get(index);
  }
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  @java.lang.Override
  public com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder getFormDataOrBuilder(
      int index) {
    return formData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userComment_);
    }
    if (id_ != 0L) {
      output.writeUInt64(2, id_);
    }
    if (notifyUsers_ != false) {
      output.writeBool(3, notifyUsers_);
    }
    if (vaultFolderId_ != 0L) {
      output.writeUInt64(9, vaultFolderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, phone_);
    }
    for (int i = 0; i < formData_.size(); i++) {
      output.writeMessage(30, formData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userComment_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, id_);
    }
    if (notifyUsers_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, notifyUsers_);
    }
    if (vaultFolderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, vaultFolderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, phone_);
    }
    for (int i = 0; i < formData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, formData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scailo.sdk.ClientsServiceUpdateRequest)) {
      return super.equals(obj);
    }
    com.scailo.sdk.ClientsServiceUpdateRequest other = (com.scailo.sdk.ClientsServiceUpdateRequest) obj;

    if (!getUserComment()
        .equals(other.getUserComment())) return false;
    if (getId()
        != other.getId()) return false;
    if (getNotifyUsers()
        != other.getNotifyUsers()) return false;
    if (getVaultFolderId()
        != other.getVaultFolderId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getPhone()
        .equals(other.getPhone())) return false;
    if (!getFormDataList()
        .equals(other.getFormDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserComment().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NOTIFY_USERS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNotifyUsers());
    hash = (37 * hash) + VAULT_FOLDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVaultFolderId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPhone().hashCode();
    if (getFormDataCount() > 0) {
      hash = (37 * hash) + FORM_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getFormDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.ClientsServiceUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scailo.sdk.ClientsServiceUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Describes the parameters necessary to update a record
   * </pre>
   *
   * Protobuf type {@code Scailo.ClientsServiceUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Scailo.ClientsServiceUpdateRequest)
      com.scailo.sdk.ClientsServiceUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scailo.sdk.ClientsScailoProto.internal_static_Scailo_ClientsServiceUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scailo.sdk.ClientsScailoProto.internal_static_Scailo_ClientsServiceUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scailo.sdk.ClientsServiceUpdateRequest.class, com.scailo.sdk.ClientsServiceUpdateRequest.Builder.class);
    }

    // Construct using com.scailo.sdk.ClientsServiceUpdateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userComment_ = "";
      id_ = 0L;
      notifyUsers_ = false;
      vaultFolderId_ = 0L;
      name_ = "";
      code_ = "";
      email_ = "";
      phone_ = "";
      if (formDataBuilder_ == null) {
        formData_ = java.util.Collections.emptyList();
      } else {
        formData_ = null;
        formDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scailo.sdk.ClientsScailoProto.internal_static_Scailo_ClientsServiceUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.scailo.sdk.ClientsServiceUpdateRequest getDefaultInstanceForType() {
      return com.scailo.sdk.ClientsServiceUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scailo.sdk.ClientsServiceUpdateRequest build() {
      com.scailo.sdk.ClientsServiceUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scailo.sdk.ClientsServiceUpdateRequest buildPartial() {
      com.scailo.sdk.ClientsServiceUpdateRequest result = new com.scailo.sdk.ClientsServiceUpdateRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.scailo.sdk.ClientsServiceUpdateRequest result) {
      if (formDataBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          formData_ = java.util.Collections.unmodifiableList(formData_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.formData_ = formData_;
      } else {
        result.formData_ = formDataBuilder_.build();
      }
    }

    private void buildPartial0(com.scailo.sdk.ClientsServiceUpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userComment_ = userComment_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.notifyUsers_ = notifyUsers_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.vaultFolderId_ = vaultFolderId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.phone_ = phone_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scailo.sdk.ClientsServiceUpdateRequest) {
        return mergeFrom((com.scailo.sdk.ClientsServiceUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scailo.sdk.ClientsServiceUpdateRequest other) {
      if (other == com.scailo.sdk.ClientsServiceUpdateRequest.getDefaultInstance()) return this;
      if (!other.getUserComment().isEmpty()) {
        userComment_ = other.userComment_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getNotifyUsers() != false) {
        setNotifyUsers(other.getNotifyUsers());
      }
      if (other.getVaultFolderId() != 0L) {
        setVaultFolderId(other.getVaultFolderId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getPhone().isEmpty()) {
        phone_ = other.phone_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (formDataBuilder_ == null) {
        if (!other.formData_.isEmpty()) {
          if (formData_.isEmpty()) {
            formData_ = other.formData_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureFormDataIsMutable();
            formData_.addAll(other.formData_);
          }
          onChanged();
        }
      } else {
        if (!other.formData_.isEmpty()) {
          if (formDataBuilder_.isEmpty()) {
            formDataBuilder_.dispose();
            formDataBuilder_ = null;
            formData_ = other.formData_;
            bitField0_ = (bitField0_ & ~0x00000100);
            formDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFormDataFieldBuilder() : null;
          } else {
            formDataBuilder_.addAllMessages(other.formData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userComment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              notifyUsers_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 72: {
              vaultFolderId_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 72
            case 82: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 82
            case 90: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 90
            case 98: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 98
            case 106: {
              phone_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 106
            case 242: {
              com.scailo.sdk.FormFieldDatumCreateRequest m =
                  input.readMessage(
                      com.scailo.sdk.FormFieldDatumCreateRequest.parser(),
                      extensionRegistry);
              if (formDataBuilder_ == null) {
                ensureFormDataIsMutable();
                formData_.add(m);
              } else {
                formDataBuilder_.addMessage(m);
              }
              break;
            } // case 242
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userComment_ = "";
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     * @return The userComment.
     */
    public java.lang.String getUserComment() {
      java.lang.Object ref = userComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     * @return The bytes for userComment.
     */
    public com.google.protobuf.ByteString
        getUserCommentBytes() {
      java.lang.Object ref = userComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     * @param value The userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserComment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userComment_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserComment() {
      userComment_ = getDefaultInstance().getUserComment();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     * @param value The bytes for userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userComment_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     * The ID of the record that needs to be updated
     * </pre>
     *
     * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * The ID of the record that needs to be updated
     * </pre>
     *
     * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the record that needs to be updated
     * </pre>
     *
     * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0L;
      onChanged();
      return this;
    }

    private boolean notifyUsers_ ;
    /**
     * <pre>
     * Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
     * </pre>
     *
     * <code>bool notify_users = 3 [json_name = "notifyUsers"];</code>
     * @return The notifyUsers.
     */
    @java.lang.Override
    public boolean getNotifyUsers() {
      return notifyUsers_;
    }
    /**
     * <pre>
     * Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
     * </pre>
     *
     * <code>bool notify_users = 3 [json_name = "notifyUsers"];</code>
     * @param value The notifyUsers to set.
     * @return This builder for chaining.
     */
    public Builder setNotifyUsers(boolean value) {
      
      notifyUsers_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
     * </pre>
     *
     * <code>bool notify_users = 3 [json_name = "notifyUsers"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNotifyUsers() {
      bitField0_ = (bitField0_ & ~0x00000004);
      notifyUsers_ = false;
      onChanged();
      return this;
    }

    private long vaultFolderId_ ;
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @return The vaultFolderId.
     */
    @java.lang.Override
    public long getVaultFolderId() {
      return vaultFolderId_;
    }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @param value The vaultFolderId to set.
     * @return This builder for chaining.
     */
    public Builder setVaultFolderId(long value) {
      
      vaultFolderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearVaultFolderId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      vaultFolderId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name of the client
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the client
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the client
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the client
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the client
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * The unique code by which the client is classified
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique code by which the client is classified
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique code by which the client is classified
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique code by which the client is classified
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique code by which the client is classified
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     * The primary email of the client
     * </pre>
     *
     * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The primary email of the client
     * </pre>
     *
     * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The primary email of the client
     * </pre>
     *
     * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The primary email of the client
     * </pre>
     *
     * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The primary email of the client
     * </pre>
     *
     * <code>string email = 12 [json_name = "email", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <pre>
     * The primary contact number of the client
     * </pre>
     *
     * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
     * @return The phone.
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The primary contact number of the client
     * </pre>
     *
     * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
     * @return The bytes for phone.
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The primary contact number of the client
     * </pre>
     *
     * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
     * @param value The phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhone(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The primary contact number of the client
     * </pre>
     *
     * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone() {
      phone_ = getDefaultInstance().getPhone();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The primary contact number of the client
     * </pre>
     *
     * <code>string phone = 13 [json_name = "phone", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest> formData_ =
      java.util.Collections.emptyList();
    private void ensureFormDataIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        formData_ = new java.util.ArrayList<com.scailo.sdk.FormFieldDatumCreateRequest>(formData_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scailo.sdk.FormFieldDatumCreateRequest, com.scailo.sdk.FormFieldDatumCreateRequest.Builder, com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder> formDataBuilder_;

    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest> getFormDataList() {
      if (formDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(formData_);
      } else {
        return formDataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public int getFormDataCount() {
      if (formDataBuilder_ == null) {
        return formData_.size();
      } else {
        return formDataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public com.scailo.sdk.FormFieldDatumCreateRequest getFormData(int index) {
      if (formDataBuilder_ == null) {
        return formData_.get(index);
      } else {
        return formDataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder setFormData(
        int index, com.scailo.sdk.FormFieldDatumCreateRequest value) {
      if (formDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFormDataIsMutable();
        formData_.set(index, value);
        onChanged();
      } else {
        formDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder setFormData(
        int index, com.scailo.sdk.FormFieldDatumCreateRequest.Builder builderForValue) {
      if (formDataBuilder_ == null) {
        ensureFormDataIsMutable();
        formData_.set(index, builderForValue.build());
        onChanged();
      } else {
        formDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder addFormData(com.scailo.sdk.FormFieldDatumCreateRequest value) {
      if (formDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFormDataIsMutable();
        formData_.add(value);
        onChanged();
      } else {
        formDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder addFormData(
        int index, com.scailo.sdk.FormFieldDatumCreateRequest value) {
      if (formDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFormDataIsMutable();
        formData_.add(index, value);
        onChanged();
      } else {
        formDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder addFormData(
        com.scailo.sdk.FormFieldDatumCreateRequest.Builder builderForValue) {
      if (formDataBuilder_ == null) {
        ensureFormDataIsMutable();
        formData_.add(builderForValue.build());
        onChanged();
      } else {
        formDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder addFormData(
        int index, com.scailo.sdk.FormFieldDatumCreateRequest.Builder builderForValue) {
      if (formDataBuilder_ == null) {
        ensureFormDataIsMutable();
        formData_.add(index, builderForValue.build());
        onChanged();
      } else {
        formDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder addAllFormData(
        java.lang.Iterable<? extends com.scailo.sdk.FormFieldDatumCreateRequest> values) {
      if (formDataBuilder_ == null) {
        ensureFormDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, formData_);
        onChanged();
      } else {
        formDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder clearFormData() {
      if (formDataBuilder_ == null) {
        formData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        formDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public Builder removeFormData(int index) {
      if (formDataBuilder_ == null) {
        ensureFormDataIsMutable();
        formData_.remove(index);
        onChanged();
      } else {
        formDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public com.scailo.sdk.FormFieldDatumCreateRequest.Builder getFormDataBuilder(
        int index) {
      return getFormDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder getFormDataOrBuilder(
        int index) {
      if (formDataBuilder_ == null) {
        return formData_.get(index);  } else {
        return formDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public java.util.List<? extends com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder> 
         getFormDataOrBuilderList() {
      if (formDataBuilder_ != null) {
        return formDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(formData_);
      }
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public com.scailo.sdk.FormFieldDatumCreateRequest.Builder addFormDataBuilder() {
      return getFormDataFieldBuilder().addBuilder(
          com.scailo.sdk.FormFieldDatumCreateRequest.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public com.scailo.sdk.FormFieldDatumCreateRequest.Builder addFormDataBuilder(
        int index) {
      return getFormDataFieldBuilder().addBuilder(
          index, com.scailo.sdk.FormFieldDatumCreateRequest.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of dynamic forms
     * </pre>
     *
     * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
     */
    public java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest.Builder> 
         getFormDataBuilderList() {
      return getFormDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scailo.sdk.FormFieldDatumCreateRequest, com.scailo.sdk.FormFieldDatumCreateRequest.Builder, com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder> 
        getFormDataFieldBuilder() {
      if (formDataBuilder_ == null) {
        formDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.scailo.sdk.FormFieldDatumCreateRequest, com.scailo.sdk.FormFieldDatumCreateRequest.Builder, com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder>(
                formData_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        formData_ = null;
      }
      return formDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Scailo.ClientsServiceUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:Scailo.ClientsServiceUpdateRequest)
  private static final com.scailo.sdk.ClientsServiceUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scailo.sdk.ClientsServiceUpdateRequest();
  }

  public static com.scailo.sdk.ClientsServiceUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientsServiceUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientsServiceUpdateRequest>() {
    @java.lang.Override
    public ClientsServiceUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientsServiceUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientsServiceUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scailo.sdk.ClientsServiceUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

