// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the data model to handle cloning of properties of a source record (denoted by source ID) into a target record (denoted by the target ID)
 * </pre>
 *
 * Protobuf type {@code Scailo.CloneRequest}
 */
public final class CloneRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Scailo.CloneRequest)
    CloneRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CloneRequest.newBuilder() to construct.
  private CloneRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CloneRequest() {
    userComment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CloneRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_CloneRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_CloneRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scailo.sdk.CloneRequest.class, com.scailo.sdk.CloneRequest.Builder.class);
  }

  public static final int SOURCE_ID_FIELD_NUMBER = 1;
  private long sourceId_ = 0L;
  /**
   * <pre>
   * The ID of the source record whose properties need to be cloned into the target record
   * </pre>
   *
   * <code>uint64 source_id = 1 [json_name = "sourceId", (.buf.validate.field) = { ... }</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public long getSourceId() {
    return sourceId_;
  }

  public static final int TARGET_ID_FIELD_NUMBER = 2;
  private long targetId_ = 0L;
  /**
   * <pre>
   * The ID of the target record that will store the cloned properties from the source
   * </pre>
   *
   * <code>uint64 target_id = 2 [json_name = "targetId", (.buf.validate.field) = { ... }</code>
   * @return The targetId.
   */
  @java.lang.Override
  public long getTargetId() {
    return targetId_;
  }

  public static final int DELETE_EXISTING_FIELD_NUMBER = 3;
  private boolean deleteExisting_ = false;
  /**
   * <pre>
   * Stores if the existing items in the target resource need to be deleted before cloning from the source resource
   * </pre>
   *
   * <code>bool delete_existing = 3 [json_name = "deleteExisting"];</code>
   * @return The deleteExisting.
   */
  @java.lang.Override
  public boolean getDeleteExisting() {
    return deleteExisting_;
  }

  public static final int USER_COMMENT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userComment_ = "";
  /**
   * <pre>
   * The comment entered by the user
   * </pre>
   *
   * <code>string user_comment = 4 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  @java.lang.Override
  public java.lang.String getUserComment() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userComment_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The comment entered by the user
   * </pre>
   *
   * <code>string user_comment = 4 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserCommentBytes() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sourceId_ != 0L) {
      output.writeUInt64(1, sourceId_);
    }
    if (targetId_ != 0L) {
      output.writeUInt64(2, targetId_);
    }
    if (deleteExisting_ != false) {
      output.writeBool(3, deleteExisting_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userComment_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sourceId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sourceId_);
    }
    if (targetId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, targetId_);
    }
    if (deleteExisting_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, deleteExisting_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userComment_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scailo.sdk.CloneRequest)) {
      return super.equals(obj);
    }
    com.scailo.sdk.CloneRequest other = (com.scailo.sdk.CloneRequest) obj;

    if (getSourceId()
        != other.getSourceId()) return false;
    if (getTargetId()
        != other.getTargetId()) return false;
    if (getDeleteExisting()
        != other.getDeleteExisting()) return false;
    if (!getUserComment()
        .equals(other.getUserComment())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSourceId());
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTargetId());
    hash = (37 * hash) + DELETE_EXISTING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeleteExisting());
    hash = (37 * hash) + USER_COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserComment().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scailo.sdk.CloneRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.CloneRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.CloneRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.CloneRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scailo.sdk.CloneRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Describes the data model to handle cloning of properties of a source record (denoted by source ID) into a target record (denoted by the target ID)
   * </pre>
   *
   * Protobuf type {@code Scailo.CloneRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Scailo.CloneRequest)
      com.scailo.sdk.CloneRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_CloneRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_CloneRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scailo.sdk.CloneRequest.class, com.scailo.sdk.CloneRequest.Builder.class);
    }

    // Construct using com.scailo.sdk.CloneRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sourceId_ = 0L;
      targetId_ = 0L;
      deleteExisting_ = false;
      userComment_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_CloneRequest_descriptor;
    }

    @java.lang.Override
    public com.scailo.sdk.CloneRequest getDefaultInstanceForType() {
      return com.scailo.sdk.CloneRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scailo.sdk.CloneRequest build() {
      com.scailo.sdk.CloneRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scailo.sdk.CloneRequest buildPartial() {
      com.scailo.sdk.CloneRequest result = new com.scailo.sdk.CloneRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scailo.sdk.CloneRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sourceId_ = sourceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.deleteExisting_ = deleteExisting_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.userComment_ = userComment_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scailo.sdk.CloneRequest) {
        return mergeFrom((com.scailo.sdk.CloneRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scailo.sdk.CloneRequest other) {
      if (other == com.scailo.sdk.CloneRequest.getDefaultInstance()) return this;
      if (other.getSourceId() != 0L) {
        setSourceId(other.getSourceId());
      }
      if (other.getTargetId() != 0L) {
        setTargetId(other.getTargetId());
      }
      if (other.getDeleteExisting() != false) {
        setDeleteExisting(other.getDeleteExisting());
      }
      if (!other.getUserComment().isEmpty()) {
        userComment_ = other.userComment_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sourceId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              targetId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              deleteExisting_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              userComment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long sourceId_ ;
    /**
     * <pre>
     * The ID of the source record whose properties need to be cloned into the target record
     * </pre>
     *
     * <code>uint64 source_id = 1 [json_name = "sourceId", (.buf.validate.field) = { ... }</code>
     * @return The sourceId.
     */
    @java.lang.Override
    public long getSourceId() {
      return sourceId_;
    }
    /**
     * <pre>
     * The ID of the source record whose properties need to be cloned into the target record
     * </pre>
     *
     * <code>uint64 source_id = 1 [json_name = "sourceId", (.buf.validate.field) = { ... }</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(long value) {
      
      sourceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the source record whose properties need to be cloned into the target record
     * </pre>
     *
     * <code>uint64 source_id = 1 [json_name = "sourceId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sourceId_ = 0L;
      onChanged();
      return this;
    }

    private long targetId_ ;
    /**
     * <pre>
     * The ID of the target record that will store the cloned properties from the source
     * </pre>
     *
     * <code>uint64 target_id = 2 [json_name = "targetId", (.buf.validate.field) = { ... }</code>
     * @return The targetId.
     */
    @java.lang.Override
    public long getTargetId() {
      return targetId_;
    }
    /**
     * <pre>
     * The ID of the target record that will store the cloned properties from the source
     * </pre>
     *
     * <code>uint64 target_id = 2 [json_name = "targetId", (.buf.validate.field) = { ... }</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(long value) {
      
      targetId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the target record that will store the cloned properties from the source
     * </pre>
     *
     * <code>uint64 target_id = 2 [json_name = "targetId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      targetId_ = 0L;
      onChanged();
      return this;
    }

    private boolean deleteExisting_ ;
    /**
     * <pre>
     * Stores if the existing items in the target resource need to be deleted before cloning from the source resource
     * </pre>
     *
     * <code>bool delete_existing = 3 [json_name = "deleteExisting"];</code>
     * @return The deleteExisting.
     */
    @java.lang.Override
    public boolean getDeleteExisting() {
      return deleteExisting_;
    }
    /**
     * <pre>
     * Stores if the existing items in the target resource need to be deleted before cloning from the source resource
     * </pre>
     *
     * <code>bool delete_existing = 3 [json_name = "deleteExisting"];</code>
     * @param value The deleteExisting to set.
     * @return This builder for chaining.
     */
    public Builder setDeleteExisting(boolean value) {
      
      deleteExisting_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores if the existing items in the target resource need to be deleted before cloning from the source resource
     * </pre>
     *
     * <code>bool delete_existing = 3 [json_name = "deleteExisting"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleteExisting() {
      bitField0_ = (bitField0_ & ~0x00000004);
      deleteExisting_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object userComment_ = "";
    /**
     * <pre>
     * The comment entered by the user
     * </pre>
     *
     * <code>string user_comment = 4 [json_name = "userComment"];</code>
     * @return The userComment.
     */
    public java.lang.String getUserComment() {
      java.lang.Object ref = userComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The comment entered by the user
     * </pre>
     *
     * <code>string user_comment = 4 [json_name = "userComment"];</code>
     * @return The bytes for userComment.
     */
    public com.google.protobuf.ByteString
        getUserCommentBytes() {
      java.lang.Object ref = userComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The comment entered by the user
     * </pre>
     *
     * <code>string user_comment = 4 [json_name = "userComment"];</code>
     * @param value The userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserComment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userComment_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comment entered by the user
     * </pre>
     *
     * <code>string user_comment = 4 [json_name = "userComment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserComment() {
      userComment_ = getDefaultInstance().getUserComment();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The comment entered by the user
     * </pre>
     *
     * <code>string user_comment = 4 [json_name = "userComment"];</code>
     * @param value The bytes for userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userComment_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Scailo.CloneRequest)
  }

  // @@protoc_insertion_point(class_scope:Scailo.CloneRequest)
  private static final com.scailo.sdk.CloneRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scailo.sdk.CloneRequest();
  }

  public static com.scailo.sdk.CloneRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloneRequest>
      PARSER = new com.google.protobuf.AbstractParser<CloneRequest>() {
    @java.lang.Override
    public CloneRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloneRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloneRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scailo.sdk.CloneRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

