// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credit_notes.scailo.proto

package com.scailo.sdk;

public interface CreditNoteItemProspectiveInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.CreditNoteItemProspectiveInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores the credit note ID
   * </pre>
   *
   * <code>uint64 credit_note_id = 10 [json_name = "creditNoteId", (.buf.validate.field) = { ... }</code>
   * @return The creditNoteId.
   */
  long getCreditNoteId();

  /**
   * <pre>
   * Stores the family ID
   * </pre>
   *
   * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
   * @return The familyId.
   */
  long getFamilyId();
}
