//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: departments.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializedepartmentsServiceCreateRequest")
public inline fun departmentsServiceCreateRequest(block: com.scailo.sdk.DepartmentsServiceCreateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.DepartmentsServiceCreateRequest =
  com.scailo.sdk.DepartmentsServiceCreateRequestKt.Dsl._create(com.scailo.sdk.DepartmentsServiceCreateRequest.newBuilder()).apply { block() }._build()
public object DepartmentsServiceCreateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.DepartmentsServiceCreateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.DepartmentsServiceCreateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.DepartmentsServiceCreateRequest = _builder.build()

    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     */
    public var entityUuid: kotlin.String
      @JvmName("getEntityUuid")
      get() = _builder.getEntityUuid()
      @JvmName("setEntityUuid")
      set(value) {
        _builder.setEntityUuid(value)
      }
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     */
    public fun clearEntityUuid() {
      _builder.clearEntityUuid()
    }

    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     */
    public var userComment: kotlin.String
      @JvmName("getUserComment")
      get() = _builder.getUserComment()
      @JvmName("setUserComment")
      set(value) {
        _builder.setUserComment(value)
      }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     */
    public fun clearUserComment() {
      _builder.clearUserComment()
    }

    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     */
    public var vaultFolderId: kotlin.Long
      @JvmName("getVaultFolderId")
      get() = _builder.getVaultFolderId()
      @JvmName("setVaultFolderId")
      set(value) {
        _builder.setVaultFolderId(value)
      }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearVaultFolderId() {
      _builder.clearVaultFolderId()
    }

    /**
     * <pre>
     * The name of the department
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * The name of the department
     * </pre>
     *
     * <code>string name = 10 [json_name = "name", (.buf.validate.field) = { ... }</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <pre>
     * The code of the department
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <pre>
     * The code of the department
     * </pre>
     *
     * <code>string code = 11 [json_name = "code", (.buf.validate.field) = { ... }</code>
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * <pre>
     * The ID of the user who is the department head of this department
     * </pre>
     *
     * <code>uint64 head_user_id = 12 [json_name = "headUserId", (.buf.validate.field) = { ... }</code>
     */
    public var headUserId: kotlin.Long
      @JvmName("getHeadUserId")
      get() = _builder.getHeadUserId()
      @JvmName("setHeadUserId")
      set(value) {
        _builder.setHeadUserId(value)
      }
    /**
     * <pre>
     * The ID of the user who is the department head of this department
     * </pre>
     *
     * <code>uint64 head_user_id = 12 [json_name = "headUserId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearHeadUserId() {
      _builder.clearHeadUserId()
    }

    /**
     * <pre>
     * The description of the department
     * </pre>
     *
     * <code>string description = 13 [json_name = "description", (.buf.validate.field) = { ... }</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * The description of the department
     * </pre>
     *
     * <code>string description = 13 [json_name = "description", (.buf.validate.field) = { ... }</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.DepartmentsServiceCreateRequest.copy(block: com.scailo.sdk.DepartmentsServiceCreateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.DepartmentsServiceCreateRequest =
  com.scailo.sdk.DepartmentsServiceCreateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

