// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equations_families.scailo.proto

package com.scailo.sdk;

public interface EquationsFamiliesServiceFilterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.EquationsFamiliesServiceFilterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If true, then returns only active records. If false, then returns only inactive records
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
   * @return The enum numeric value on the wire for isActive.
   */
  int getIsActiveValue();
  /**
   * <pre>
   * If true, then returns only active records. If false, then returns only inactive records
   * </pre>
   *
   * <code>.Scailo.BOOL_FILTER is_active = 1 [json_name = "isActive"];</code>
   * @return The isActive.
   */
  com.scailo.sdk.BOOL_FILTER getIsActive();

  /**
   * <pre>
   * The number of records that need to be sent in the response. Returns all records if it is set to -1
   * </pre>
   *
   * <code>int64 count = 2 [json_name = "count", (.buf.validate.field) = { ... }</code>
   * @return The count.
   */
  long getCount();

  /**
   * <pre>
   * The number that need to be offset by before fetching the records
   * </pre>
   *
   * <code>uint64 offset = 3 [json_name = "offset", (.buf.validate.field) = { ... }</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <pre>
   * The sort order that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
   * @return The enum numeric value on the wire for sortOrder.
   */
  int getSortOrderValue();
  /**
   * <pre>
   * The sort order that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.SORT_ORDER sort_order = 4 [json_name = "sortOrder"];</code>
   * @return The sortOrder.
   */
  com.scailo.sdk.SORT_ORDER getSortOrder();

  /**
   * <pre>
   * The sort key that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.EQUATION_FAMILY_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
   * @return The enum numeric value on the wire for sortKey.
   */
  int getSortKeyValue();
  /**
   * <pre>
   * The sort key that is to be used to fetch the pagination response
   * </pre>
   *
   * <code>.Scailo.EQUATION_FAMILY_SORT_KEY sort_key = 5 [json_name = "sortKey"];</code>
   * @return The sortKey.
   */
  com.scailo.sdk.EQUATION_FAMILY_SORT_KEY getSortKey();

  /**
   * <pre>
   * The minimum timestamp that needs to be considered to filter by creation
   * </pre>
   *
   * <code>uint64 creation_timestamp_start = 101 [json_name = "creationTimestampStart"];</code>
   * @return The creationTimestampStart.
   */
  long getCreationTimestampStart();

  /**
   * <pre>
   * The maximum timestamp that needs to be considered to filter by creation
   * </pre>
   *
   * <code>uint64 creation_timestamp_end = 102 [json_name = "creationTimestampEnd"];</code>
   * @return The creationTimestampEnd.
   */
  long getCreationTimestampEnd();

  /**
   * <pre>
   * The minimum timestamp that needs to be considered to filter by modification
   * </pre>
   *
   * <code>uint64 modification_timestamp_start = 103 [json_name = "modificationTimestampStart"];</code>
   * @return The modificationTimestampStart.
   */
  long getModificationTimestampStart();

  /**
   * <pre>
   * The maximum timestamp that needs to be considered to filter by modification
   * </pre>
   *
   * <code>uint64 modification_timestamp_end = 104 [json_name = "modificationTimestampEnd"];</code>
   * @return The modificationTimestampEnd.
   */
  long getModificationTimestampEnd();

  /**
   * <pre>
   * The entity UUID that is to be used to filter records
   * </pre>
   *
   * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
   * @return The entityUuid.
   */
  java.lang.String getEntityUuid();
  /**
   * <pre>
   * The entity UUID that is to be used to filter records
   * </pre>
   *
   * <code>string entity_uuid = 8 [json_name = "entityUuid"];</code>
   * @return The bytes for entityUuid.
   */
  com.google.protobuf.ByteString
      getEntityUuidBytes();

  /**
   * <pre>
   * The status of this equation family
   * </pre>
   *
   * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * The status of this equation family
   * </pre>
   *
   * <code>.Scailo.STANDARD_LIFECYCLE_STATUS status = 10 [json_name = "status"];</code>
   * @return The status.
   */
  com.scailo.sdk.STANDARD_LIFECYCLE_STATUS getStatus();

  /**
   * <pre>
   * The start range of approved timestamp
   * </pre>
   *
   * <code>uint64 approved_on_start = 11 [json_name = "approvedOnStart"];</code>
   * @return The approvedOnStart.
   */
  long getApprovedOnStart();

  /**
   * <pre>
   * The end range of approved timestamp
   * </pre>
   *
   * <code>uint64 approved_on_end = 12 [json_name = "approvedOnEnd"];</code>
   * @return The approvedOnEnd.
   */
  long getApprovedOnEnd();

  /**
   * <pre>
   * The ID of the approver
   * </pre>
   *
   * <code>uint64 approved_by_user_id = 13 [json_name = "approvedByUserId"];</code>
   * @return The approvedByUserId.
   */
  long getApprovedByUserId();

  /**
   * <pre>
   * The role ID of the approver
   * </pre>
   *
   * <code>uint64 approver_role_id = 14 [json_name = "approverRoleId"];</code>
   * @return The approverRoleId.
   */
  long getApproverRoleId();

  /**
   * <pre>
   * The start range of completed timestamp
   * </pre>
   *
   * <code>uint64 completed_on_start = 15 [json_name = "completedOnStart"];</code>
   * @return The completedOnStart.
   */
  long getCompletedOnStart();

  /**
   * <pre>
   * The end range of completed timestamp
   * </pre>
   *
   * <code>uint64 completed_on_end = 16 [json_name = "completedOnEnd"];</code>
   * @return The completedOnEnd.
   */
  long getCompletedOnEnd();

  /**
   * <pre>
   * The name of the equation family
   * </pre>
   *
   * <code>string name = 20 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the equation family
   * </pre>
   *
   * <code>string name = 20 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The ID of the family that this equation belongs to
   * </pre>
   *
   * <code>uint64 family_id = 21 [json_name = "familyId"];</code>
   * @return The familyId.
   */
  long getFamilyId();

  /**
   * <pre>
   * The ID of the constituent family that is part of an equation
   * </pre>
   *
   * <code>uint64 constituent_family_id = 30 [json_name = "constituentFamilyId"];</code>
   * @return The constituentFamilyId.
   */
  long getConstituentFamilyId();
}
