// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: expenses.scailo.proto

package com.scailo.sdk;

public interface ExpensesServiceUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.ExpensesServiceUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  java.lang.String getUserComment();
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  com.google.protobuf.ByteString
      getUserCommentBytes();

  /**
   * <pre>
   * The ID of the record that needs to be updated
   * </pre>
   *
   * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
   * </pre>
   *
   * <code>bool notify_users = 3 [json_name = "notifyUsers"];</code>
   * @return The notifyUsers.
   */
  boolean getNotifyUsers();

  /**
   * <pre>
   * The associated project ID
   * </pre>
   *
   * <code>uint64 project_id = 8 [json_name = "projectId", (.buf.validate.field) = { ... }</code>
   * @return The projectId.
   */
  long getProjectId();

  /**
   * <pre>
   * The associated vault folder ID
   * </pre>
   *
   * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
   * @return The vaultFolderId.
   */
  long getVaultFolderId();

  /**
   * <pre>
   * The reference ID of the expense
   * </pre>
   *
   * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <pre>
   * The reference ID of the expense
   * </pre>
   *
   * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <pre>
   * The reference on which the expense has been created
   * </pre>
   *
   * <code>string ref_from = 12 [json_name = "refFrom", (.buf.validate.field) = { ... }</code>
   * @return The refFrom.
   */
  java.lang.String getRefFrom();
  /**
   * <pre>
   * The reference on which the expense has been created
   * </pre>
   *
   * <code>string ref_from = 12 [json_name = "refFrom", (.buf.validate.field) = { ... }</code>
   * @return The bytes for refFrom.
   */
  com.google.protobuf.ByteString
      getRefFromBytes();

  /**
   * <pre>
   * The ID of the associated reference (can be 0 in case ref_from is "not-applicable")
   * </pre>
   *
   * <code>uint64 ref_id = 13 [json_name = "refId", (.buf.validate.field) = { ... }</code>
   * @return The refId.
   */
  long getRefId();

  /**
   * <pre>
   * The ID of the associated currency
   * </pre>
   *
   * <code>uint64 currency_id = 14 [json_name = "currencyId", (.buf.validate.field) = { ... }</code>
   * @return The currencyId.
   */
  long getCurrencyId();

  /**
   * <pre>
   * The ID of the user who paid for this expense (if paid by organization, then this will be 0)
   * </pre>
   *
   * <code>uint64 paid_by_user_id = 15 [json_name = "paidByUserId", (.buf.validate.field) = { ... }</code>
   * @return The paidByUserId.
   */
  long getPaidByUserId();

  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  java.util.List<com.scailo.sdk.FormFieldDatumCreateRequest> 
      getFormDataList();
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  com.scailo.sdk.FormFieldDatumCreateRequest getFormData(int index);
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  int getFormDataCount();
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  java.util.List<? extends com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder> 
      getFormDataOrBuilderList();
  /**
   * <pre>
   * The list of dynamic forms
   * </pre>
   *
   * <code>repeated .Scailo.FormFieldDatumCreateRequest form_data = 30 [json_name = "formData"];</code>
   */
  com.scailo.sdk.FormFieldDatumCreateRequestOrBuilder getFormDataOrBuilder(
      int index);
}
