// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: goods_receipts.scailo.proto

package com.scailo.sdk;

public interface GoodsReceiptsServiceMultipleItemsSingletonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.GoodsReceiptsServiceMultipleItemsSingleton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores the family ID
   * </pre>
   *
   * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
   * @return The familyId.
   */
  long getFamilyId();

  /**
   * <pre>
   * The quantity (in cents) being admitted in internal unit of material
   * </pre>
   *
   * <code>uint64 internal_quantity = 12 [json_name = "internalQuantity", (.buf.validate.field) = { ... }</code>
   * @return The internalQuantity.
   */
  long getInternalQuantity();

  /**
   * <pre>
   * Stores the ID of the vendor's unit of material
   * </pre>
   *
   * <code>uint64 vendor_uom_id = 13 [json_name = "vendorUomId", (.buf.validate.field) = { ... }</code>
   * @return The vendorUomId.
   */
  long getVendorUomId();

  /**
   * <pre>
   * Stores the quantity (in cents) being admitted in vendor's unit of material
   * </pre>
   *
   * <code>uint64 vendor_quantity = 14 [json_name = "vendorQuantity", (.buf.validate.field) = { ... }</code>
   * @return The vendorQuantity.
   */
  long getVendorQuantity();

  /**
   * <pre>
   * Optional specifications
   * </pre>
   *
   * <code>string specifications = 18 [json_name = "specifications"];</code>
   * @return The specifications.
   */
  java.lang.String getSpecifications();
  /**
   * <pre>
   * Optional specifications
   * </pre>
   *
   * <code>string specifications = 18 [json_name = "specifications"];</code>
   * @return The bytes for specifications.
   */
  com.google.protobuf.ByteString
      getSpecificationsBytes();
}
