//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: base.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializegPSCoordinatesResponse")
public inline fun gPSCoordinatesResponse(block: com.scailo.sdk.GPSCoordinatesResponseKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.GPSCoordinatesResponse =
  com.scailo.sdk.GPSCoordinatesResponseKt.Dsl._create(com.scailo.sdk.GPSCoordinatesResponse.newBuilder()).apply { block() }._build()
public object GPSCoordinatesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.GPSCoordinatesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.GPSCoordinatesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.GPSCoordinatesResponse = _builder.build()

    /**
     * <pre>
     * Stores the latitude
     * </pre>
     *
     * <code>double latitude = 1 [json_name = "latitude"];</code>
     */
    public var latitude: kotlin.Double
      @JvmName("getLatitude")
      get() = _builder.getLatitude()
      @JvmName("setLatitude")
      set(value) {
        _builder.setLatitude(value)
      }
    /**
     * <pre>
     * Stores the latitude
     * </pre>
     *
     * <code>double latitude = 1 [json_name = "latitude"];</code>
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * <pre>
     * Stores the longitude
     * </pre>
     *
     * <code>double longitude = 2 [json_name = "longitude"];</code>
     */
    public var longitude: kotlin.Double
      @JvmName("getLongitude")
      get() = _builder.getLongitude()
      @JvmName("setLongitude")
      set(value) {
        _builder.setLongitude(value)
      }
    /**
     * <pre>
     * Stores the longitude
     * </pre>
     *
     * <code>double longitude = 2 [json_name = "longitude"];</code>
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.GPSCoordinatesResponse.copy(block: com.scailo.sdk.GPSCoordinatesResponseKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.GPSCoordinatesResponse =
  com.scailo.sdk.GPSCoordinatesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

