// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: holidays.scailo.proto

package com.scailo.sdk;

public interface HolidaysServiceShiftGroupCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.HolidaysServiceShiftGroupCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  java.lang.String getUserComment();
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  com.google.protobuf.ByteString
      getUserCommentBytes();

  /**
   * <pre>
   * Stores the holiday ID
   * </pre>
   *
   * <code>uint64 holiday_id = 10 [json_name = "holidayId", (.buf.validate.field) = { ... }</code>
   * @return The holidayId.
   */
  long getHolidayId();

  /**
   * <pre>
   * Stores the shift group ID
   * </pre>
   *
   * <code>uint64 shift_group_id = 11 [json_name = "shiftGroupId", (.buf.validate.field) = { ... }</code>
   * @return The shiftGroupId.
   */
  long getShiftGroupId();
}
