//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: base.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializeidentifierWithEmailAttributes")
public inline fun identifierWithEmailAttributes(block: com.scailo.sdk.IdentifierWithEmailAttributesKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.IdentifierWithEmailAttributes =
  com.scailo.sdk.IdentifierWithEmailAttributesKt.Dsl._create(com.scailo.sdk.IdentifierWithEmailAttributes.newBuilder()).apply { block() }._build()
public object IdentifierWithEmailAttributesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.IdentifierWithEmailAttributes.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.IdentifierWithEmailAttributes.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.IdentifierWithEmailAttributes = _builder.build()

    /**
     * <pre>
     * ID of the resource
     * </pre>
     *
     * <code>uint64 id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <pre>
     * ID of the resource
     * </pre>
     *
     * <code>uint64 id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <pre>
     * The subject of the email
     * </pre>
     *
     * <code>string subject = 10 [json_name = "subject"];</code>
     */
    public var subject: kotlin.String
      @JvmName("getSubject")
      get() = _builder.getSubject()
      @JvmName("setSubject")
      set(value) {
        _builder.setSubject(value)
      }
    /**
     * <pre>
     * The subject of the email
     * </pre>
     *
     * <code>string subject = 10 [json_name = "subject"];</code>
     */
    public fun clearSubject() {
      _builder.clearSubject()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RecipientsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @return A list containing the recipients.
     */
    public val recipients: com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRecipientsList()
      )
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @param value The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRecipients")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.add(value: kotlin.String) {
      _builder.addRecipients(value)
    }
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @param value The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRecipients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @param values The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRecipients")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllRecipients(values)
    }
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @param values The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRecipients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     * @param index The index to set the value at.
     * @param value The recipients to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRecipients")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setRecipients(index, value)
    }/**
     * <pre>
     * The list of email addresses of the recipients
     * </pre>
     *
     * <code>repeated string recipients = 11 [json_name = "recipients"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRecipients")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RecipientsProxy>.clear() {
      _builder.clearRecipients()
    }
    /**
     * <pre>
     * The body of the email
     * </pre>
     *
     * <code>string body = 12 [json_name = "body"];</code>
     */
    public var body: kotlin.String
      @JvmName("getBody")
      get() = _builder.getBody()
      @JvmName("setBody")
      set(value) {
        _builder.setBody(value)
      }
    /**
     * <pre>
     * The body of the email
     * </pre>
     *
     * <code>string body = 12 [json_name = "body"];</code>
     */
    public fun clearBody() {
      _builder.clearBody()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.IdentifierWithEmailAttributes.copy(block: com.scailo.sdk.IdentifierWithEmailAttributesKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.IdentifierWithEmailAttributes =
  com.scailo.sdk.IdentifierWithEmailAttributesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

