//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: inward_jobs.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializeinwardJobsServiceContactCreateRequest")
public inline fun inwardJobsServiceContactCreateRequest(block: com.scailo.sdk.InwardJobsServiceContactCreateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.InwardJobsServiceContactCreateRequest =
  com.scailo.sdk.InwardJobsServiceContactCreateRequestKt.Dsl._create(com.scailo.sdk.InwardJobsServiceContactCreateRequest.newBuilder()).apply { block() }._build()
public object InwardJobsServiceContactCreateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.InwardJobsServiceContactCreateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.InwardJobsServiceContactCreateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.InwardJobsServiceContactCreateRequest = _builder.build()

    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     */
    public var userComment: kotlin.String
      @JvmName("getUserComment")
      get() = _builder.getUserComment()
      @JvmName("setUserComment")
      set(value) {
        _builder.setUserComment(value)
      }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     */
    public fun clearUserComment() {
      _builder.clearUserComment()
    }

    /**
     * <pre>
     * Stores the inward job ID
     * </pre>
     *
     * <code>uint64 inward_job_id = 10 [json_name = "inwardJobId", (.buf.validate.field) = { ... }</code>
     */
    public var inwardJobId: kotlin.Long
      @JvmName("getInwardJobId")
      get() = _builder.getInwardJobId()
      @JvmName("setInwardJobId")
      set(value) {
        _builder.setInwardJobId(value)
      }
    /**
     * <pre>
     * Stores the inward job ID
     * </pre>
     *
     * <code>uint64 inward_job_id = 10 [json_name = "inwardJobId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearInwardJobId() {
      _builder.clearInwardJobId()
    }

    /**
     * <pre>
     * Stores the associate ID
     * </pre>
     *
     * <code>uint64 associate_id = 11 [json_name = "associateId", (.buf.validate.field) = { ... }</code>
     */
    public var associateId: kotlin.Long
      @JvmName("getAssociateId")
      get() = _builder.getAssociateId()
      @JvmName("setAssociateId")
      set(value) {
        _builder.setAssociateId(value)
      }
    /**
     * <pre>
     * Stores the associate ID
     * </pre>
     *
     * <code>uint64 associate_id = 11 [json_name = "associateId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearAssociateId() {
      _builder.clearAssociateId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.InwardJobsServiceContactCreateRequest.copy(block: com.scailo.sdk.InwardJobsServiceContactCreateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.InwardJobsServiceContactCreateRequest =
  com.scailo.sdk.InwardJobsServiceContactCreateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

