// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the payload that will be used to filter records on the basis of the given month and day
 * </pre>
 *
 * Protobuf type {@code Scailo.MonthAndDayFilter}
 */
public final class MonthAndDayFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Scailo.MonthAndDayFilter)
    MonthAndDayFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonthAndDayFilter.newBuilder() to construct.
  private MonthAndDayFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonthAndDayFilter() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MonthAndDayFilter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_MonthAndDayFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_MonthAndDayFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scailo.sdk.MonthAndDayFilter.class, com.scailo.sdk.MonthAndDayFilter.Builder.class);
  }

  public static final int MONTH_FIELD_NUMBER = 1;
  private long month_ = 0L;
  /**
   * <pre>
   * Stores the month (1 for Jan, 2 for Feb, etc.)
   * </pre>
   *
   * <code>uint64 month = 1 [json_name = "month"];</code>
   * @return The month.
   */
  @java.lang.Override
  public long getMonth() {
    return month_;
  }

  public static final int DAY_FIELD_NUMBER = 2;
  private long day_ = 0L;
  /**
   * <pre>
   * Stores the day
   * </pre>
   *
   * <code>uint64 day = 2 [json_name = "day"];</code>
   * @return The day.
   */
  @java.lang.Override
  public long getDay() {
    return day_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (month_ != 0L) {
      output.writeUInt64(1, month_);
    }
    if (day_ != 0L) {
      output.writeUInt64(2, day_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (month_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, month_);
    }
    if (day_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, day_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scailo.sdk.MonthAndDayFilter)) {
      return super.equals(obj);
    }
    com.scailo.sdk.MonthAndDayFilter other = (com.scailo.sdk.MonthAndDayFilter) obj;

    if (getMonth()
        != other.getMonth()) return false;
    if (getDay()
        != other.getDay()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMonth());
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDay());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.MonthAndDayFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scailo.sdk.MonthAndDayFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Describes the payload that will be used to filter records on the basis of the given month and day
   * </pre>
   *
   * Protobuf type {@code Scailo.MonthAndDayFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Scailo.MonthAndDayFilter)
      com.scailo.sdk.MonthAndDayFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_MonthAndDayFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_MonthAndDayFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scailo.sdk.MonthAndDayFilter.class, com.scailo.sdk.MonthAndDayFilter.Builder.class);
    }

    // Construct using com.scailo.sdk.MonthAndDayFilter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      month_ = 0L;
      day_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scailo.sdk.BaseScailoProto.internal_static_Scailo_MonthAndDayFilter_descriptor;
    }

    @java.lang.Override
    public com.scailo.sdk.MonthAndDayFilter getDefaultInstanceForType() {
      return com.scailo.sdk.MonthAndDayFilter.getDefaultInstance();
    }

    @java.lang.Override
    public com.scailo.sdk.MonthAndDayFilter build() {
      com.scailo.sdk.MonthAndDayFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scailo.sdk.MonthAndDayFilter buildPartial() {
      com.scailo.sdk.MonthAndDayFilter result = new com.scailo.sdk.MonthAndDayFilter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scailo.sdk.MonthAndDayFilter result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.month_ = month_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.day_ = day_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scailo.sdk.MonthAndDayFilter) {
        return mergeFrom((com.scailo.sdk.MonthAndDayFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scailo.sdk.MonthAndDayFilter other) {
      if (other == com.scailo.sdk.MonthAndDayFilter.getDefaultInstance()) return this;
      if (other.getMonth() != 0L) {
        setMonth(other.getMonth());
      }
      if (other.getDay() != 0L) {
        setDay(other.getDay());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              month_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              day_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long month_ ;
    /**
     * <pre>
     * Stores the month (1 for Jan, 2 for Feb, etc.)
     * </pre>
     *
     * <code>uint64 month = 1 [json_name = "month"];</code>
     * @return The month.
     */
    @java.lang.Override
    public long getMonth() {
      return month_;
    }
    /**
     * <pre>
     * Stores the month (1 for Jan, 2 for Feb, etc.)
     * </pre>
     *
     * <code>uint64 month = 1 [json_name = "month"];</code>
     * @param value The month to set.
     * @return This builder for chaining.
     */
    public Builder setMonth(long value) {
      
      month_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores the month (1 for Jan, 2 for Feb, etc.)
     * </pre>
     *
     * <code>uint64 month = 1 [json_name = "month"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMonth() {
      bitField0_ = (bitField0_ & ~0x00000001);
      month_ = 0L;
      onChanged();
      return this;
    }

    private long day_ ;
    /**
     * <pre>
     * Stores the day
     * </pre>
     *
     * <code>uint64 day = 2 [json_name = "day"];</code>
     * @return The day.
     */
    @java.lang.Override
    public long getDay() {
      return day_;
    }
    /**
     * <pre>
     * Stores the day
     * </pre>
     *
     * <code>uint64 day = 2 [json_name = "day"];</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(long value) {
      
      day_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores the day
     * </pre>
     *
     * <code>uint64 day = 2 [json_name = "day"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      bitField0_ = (bitField0_ & ~0x00000002);
      day_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Scailo.MonthAndDayFilter)
  }

  // @@protoc_insertion_point(class_scope:Scailo.MonthAndDayFilter)
  private static final com.scailo.sdk.MonthAndDayFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scailo.sdk.MonthAndDayFilter();
  }

  public static com.scailo.sdk.MonthAndDayFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonthAndDayFilter>
      PARSER = new com.google.protobuf.AbstractParser<MonthAndDayFilter>() {
    @java.lang.Override
    public MonthAndDayFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MonthAndDayFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonthAndDayFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scailo.sdk.MonthAndDayFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

