// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outward_jobs_free_issue_materials_returns.scailo.proto

package com.scailo.sdk;

public interface OutwardJobsFreeIssueMaterialsReturnsItemsListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.OutwardJobsFreeIssueMaterialsReturnsItemsList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.OutwardJobFreeIssueMaterialReturnItem list = 1 [json_name = "list"];</code>
   */
  java.util.List<com.scailo.sdk.OutwardJobFreeIssueMaterialReturnItem> 
      getListList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.OutwardJobFreeIssueMaterialReturnItem list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.OutwardJobFreeIssueMaterialReturnItem getList(int index);
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.OutwardJobFreeIssueMaterialReturnItem list = 1 [json_name = "list"];</code>
   */
  int getListCount();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.OutwardJobFreeIssueMaterialReturnItem list = 1 [json_name = "list"];</code>
   */
  java.util.List<? extends com.scailo.sdk.OutwardJobFreeIssueMaterialReturnItemOrBuilder> 
      getListOrBuilderList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.OutwardJobFreeIssueMaterialReturnItem list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.OutwardJobFreeIssueMaterialReturnItemOrBuilder getListOrBuilder(
      int index);
}
