// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: production_indents.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Stores all the possible production references from which a production indent can be added
 * </pre>
 *
 * Protobuf enum {@code Scailo.PRODUCTION_INDENT_PRODUCTION_REF_FOR}
 */
public enum PRODUCTION_INDENT_PRODUCTION_REF_FOR
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Used only in filters
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_ANY_UNSPECIFIED = 0;</code>
   */
  PRODUCTION_INDENT_PRODUCTION_REF_FOR_ANY_UNSPECIFIED(0),
  /**
   * <pre>
   * Denotes that the production indent is not associated to any production plan
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_NONE = 1;</code>
   */
  PRODUCTION_INDENT_PRODUCTION_REF_FOR_NONE(1),
  /**
   * <pre>
   * Denotes that the production indent is associated to a production plan
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_PRODUCTION_PLAN = 2;</code>
   */
  PRODUCTION_INDENT_PRODUCTION_REF_FOR_PRODUCTION_PLAN(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Used only in filters
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_ANY_UNSPECIFIED = 0;</code>
   */
  public static final int PRODUCTION_INDENT_PRODUCTION_REF_FOR_ANY_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Denotes that the production indent is not associated to any production plan
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_NONE = 1;</code>
   */
  public static final int PRODUCTION_INDENT_PRODUCTION_REF_FOR_NONE_VALUE = 1;
  /**
   * <pre>
   * Denotes that the production indent is associated to a production plan
   * </pre>
   *
   * <code>PRODUCTION_INDENT_PRODUCTION_REF_FOR_PRODUCTION_PLAN = 2;</code>
   */
  public static final int PRODUCTION_INDENT_PRODUCTION_REF_FOR_PRODUCTION_PLAN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PRODUCTION_INDENT_PRODUCTION_REF_FOR valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PRODUCTION_INDENT_PRODUCTION_REF_FOR forNumber(int value) {
    switch (value) {
      case 0: return PRODUCTION_INDENT_PRODUCTION_REF_FOR_ANY_UNSPECIFIED;
      case 1: return PRODUCTION_INDENT_PRODUCTION_REF_FOR_NONE;
      case 2: return PRODUCTION_INDENT_PRODUCTION_REF_FOR_PRODUCTION_PLAN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PRODUCTION_INDENT_PRODUCTION_REF_FOR>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PRODUCTION_INDENT_PRODUCTION_REF_FOR> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PRODUCTION_INDENT_PRODUCTION_REF_FOR>() {
          public PRODUCTION_INDENT_PRODUCTION_REF_FOR findValueByNumber(int number) {
            return PRODUCTION_INDENT_PRODUCTION_REF_FOR.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scailo.sdk.ProductionIndentsScailoProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final PRODUCTION_INDENT_PRODUCTION_REF_FOR[] VALUES = values();

  public static PRODUCTION_INDENT_PRODUCTION_REF_FOR valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PRODUCTION_INDENT_PRODUCTION_REF_FOR(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Scailo.PRODUCTION_INDENT_PRODUCTION_REF_FOR)
}

