//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: purchases_returns.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializepurchaseReturnAncillaryParameters")
public inline fun purchaseReturnAncillaryParameters(block: com.scailo.sdk.PurchaseReturnAncillaryParametersKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.PurchaseReturnAncillaryParameters =
  com.scailo.sdk.PurchaseReturnAncillaryParametersKt.Dsl._create(com.scailo.sdk.PurchaseReturnAncillaryParameters.newBuilder()).apply { block() }._build()
public object PurchaseReturnAncillaryParametersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.PurchaseReturnAncillaryParameters.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.PurchaseReturnAncillaryParameters.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.PurchaseReturnAncillaryParameters = _builder.build()

    /**
     * <pre>
     * The UUID of the ref_id (the UUID of the associated ref_id)
     * </pre>
     *
     * <code>string ref_uuid = 213 [json_name = "refUuid"];</code>
     */
    public var refUuid: kotlin.String
      @JvmName("getRefUuid")
      get() = _builder.getRefUuid()
      @JvmName("setRefUuid")
      set(value) {
        _builder.setRefUuid(value)
      }
    /**
     * <pre>
     * The UUID of the ref_id (the UUID of the associated ref_id)
     * </pre>
     *
     * <code>string ref_uuid = 213 [json_name = "refUuid"];</code>
     */
    public fun clearRefUuid() {
      _builder.clearRefUuid()
    }

    /**
     * <pre>
     * The UUID of the location (the UUID of the associated location_id)
     * </pre>
     *
     * <code>string location_uuid = 215 [json_name = "locationUuid"];</code>
     */
    public var locationUuid: kotlin.String
      @JvmName("getLocationUuid")
      get() = _builder.getLocationUuid()
      @JvmName("setLocationUuid")
      set(value) {
        _builder.setLocationUuid(value)
      }
    /**
     * <pre>
     * The UUID of the location (the UUID of the associated location_id)
     * </pre>
     *
     * <code>string location_uuid = 215 [json_name = "locationUuid"];</code>
     */
    public fun clearLocationUuid() {
      _builder.clearLocationUuid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.PurchaseReturnAncillaryParameters.copy(block: com.scailo.sdk.PurchaseReturnAncillaryParametersKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.PurchaseReturnAncillaryParameters =
  com.scailo.sdk.PurchaseReturnAncillaryParametersKt.Dsl._create(this.toBuilder()).apply { block() }._build()

