// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchases_orders.scailo.proto

package com.scailo.sdk;

public interface PurchaseOrderPriceMatchListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.PurchaseOrderPriceMatchList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.PurchaseOrderPriceMatch list = 1 [json_name = "list"];</code>
   */
  java.util.List<com.scailo.sdk.PurchaseOrderPriceMatch> 
      getListList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.PurchaseOrderPriceMatch list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.PurchaseOrderPriceMatch getList(int index);
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.PurchaseOrderPriceMatch list = 1 [json_name = "list"];</code>
   */
  int getListCount();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.PurchaseOrderPriceMatch list = 1 [json_name = "list"];</code>
   */
  java.util.List<? extends com.scailo.sdk.PurchaseOrderPriceMatchOrBuilder> 
      getListOrBuilderList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.PurchaseOrderPriceMatch list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.PurchaseOrderPriceMatchOrBuilder getListOrBuilder(
      int index);
}
