// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchases_payments.scailo.proto

package com.scailo.sdk;

public final class PurchasesPaymentsScailoProto {
  private PurchasesPaymentsScailoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServiceUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServiceUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasePaymentAncillaryParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasePaymentAncillaryParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasePayment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasePayment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServicePaginationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServicePaginationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServicePaginationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServicePaginationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServiceFilterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServiceFilterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServiceCountReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServiceCountReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_PurchasesPaymentsServiceSearchAllReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_PurchasesPaymentsServiceSearchAllReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037purchases_payments.scailo.proto\022\006Scail" +
      "o\032\021base.scailo.proto\032\033buf/validate/valid" +
      "ate.proto\032\030magic_links.scailo.proto\"\225\005\n%" +
      "PurchasesPaymentsServiceCreateRequest\022\037\n" +
      "\013entity_uuid\030\001 \001(\tR\nentityUuid\022!\n\014user_c" +
      "omment\030\002 \001(\tR\013userComment\022/\n\017vault_folde" +
      "r_id\030\t \001(\004B\007\272H\0042\002(\000R\rvaultFolderId\0228\n\014re" +
      "ference_id\030\n \001(\tB\025\272H\022r\0202\016[0-9A-Za-z ]+$R" +
      "\013referenceId\022<\n\010ref_from\030\014 \001(\0162!.Scailo." +
      "PURCHASE_PAYMENT_REF_FROMR\007refFrom\022\036\n\006re" +
      "f_id\030\r \001(\004B\007\272H\0042\002 \000R\005refId\022/\n\017bank_accou" +
      "nt_id\030\017 \001(\004B\007\272H\0042\002 \000R\rbankAccountId\022(\n\013c" +
      "urrency_id\030\020 \001(\004B\007\272H\0042\002 \000R\ncurrencyId\022C\n" +
      "\020transaction_type\030\021 \001(\0162\030.Scailo.TRANSAC" +
      "TION_TYPER\017transactionType\022(\n\013amount_bas" +
      "e\030\022 \001(\004B\007\272H\0042\002(\000R\namountBase\022&\n\namount_n" +
      "et\030\023 \001(\004B\007\272H\0042\002(\000R\tamountNet\0224\n\021payment_" +
      "timestamp\030\024 \001(\004B\007\272H\0042\002 \000R\020paymentTimesta" +
      "mp\0227\n\013description\030\025 \001(\tB\025\272H\022r\0202\016[0-9A-Za" +
      "-z ]+$R\013description\"\322\004\n%PurchasesPayment" +
      "sServiceUpdateRequest\022!\n\014user_comment\030\001 " +
      "\001(\tR\013userComment\022\027\n\002id\030\002 \001(\004B\007\272H\0042\002 \000R\002i" +
      "d\022!\n\014notify_users\030\003 \001(\010R\013notifyUsers\022/\n\017" +
      "vault_folder_id\030\t \001(\004B\007\272H\0042\002(\000R\rvaultFol" +
      "derId\0228\n\014reference_id\030\n \001(\tB\025\272H\022r\0202\016[0-9" +
      "A-Za-z ]+$R\013referenceId\022/\n\017bank_account_" +
      "id\030\017 \001(\004B\007\272H\0042\002 \000R\rbankAccountId\022(\n\013curr" +
      "ency_id\030\020 \001(\004B\007\272H\0042\002 \000R\ncurrencyId\022C\n\020tr" +
      "ansaction_type\030\021 \001(\0162\030.Scailo.TRANSACTIO" +
      "N_TYPER\017transactionType\022(\n\013amount_base\030\022" +
      " \001(\004B\007\272H\0042\002(\000R\namountBase\022&\n\namount_net\030" +
      "\023 \001(\004B\007\272H\0042\002(\000R\tamountNet\0224\n\021payment_tim" +
      "estamp\030\024 \001(\004B\007\272H\0042\002 \000R\020paymentTimestamp\022" +
      "7\n\013description\030\025 \001(\tB\025\272H\022r\0202\016[0-9A-Za-z " +
      "]+$R\013description\"\265\001\n\"PurchasePaymentAnci" +
      "llaryParameters\022\032\n\010ref_uuid\030\325\001 \001(\tR\007refU" +
      "uid\022 \n\013vendor_uuid\030\326\001 \001(\tR\nvendorUuid\022+\n" +
      "\021bank_account_uuid\030\327\001 \001(\tR\017bankAccountUu" +
      "id\022$\n\rcurrency_uuid\030\330\001 \001(\tR\014currencyUuid" +
      "\"\303\006\n\017PurchasePayment\022\037\n\013entity_uuid\030\001 \001(" +
      "\tR\nentityUuid\0224\n\010metadata\030\002 \001(\0132\030.Scailo" +
      ".EmployeeMetadataR\010metadata\022E\n\021approval_" +
      "metadata\030\003 \001(\0132\030.Scailo.ApprovalMetadata" +
      "R\020approvalMetadata\0229\n\006status\030\004 \001(\0162!.Sca" +
      "ilo.STANDARD_LIFECYCLE_STATUSR\006status\0220\n" +
      "\004logs\030\005 \003(\0132\034.Scailo.LogbookLogConciseSL" +
      "CR\004logs\022!\n\014completed_on\030\006 \001(\004R\013completed" +
      "On\022&\n\017vault_folder_id\030\t \001(\004R\rvaultFolder" +
      "Id\022!\n\014reference_id\030\n \001(\tR\013referenceId\022(\n" +
      "\020final_ref_number\030\013 \001(\tR\016finalRefNumber\022" +
      "<\n\010ref_from\030\014 \001(\0162!.Scailo.PURCHASE_PAYM" +
      "ENT_REF_FROMR\007refFrom\022\025\n\006ref_id\030\r \001(\004R\005r" +
      "efId\022\033\n\tvendor_id\030\016 \001(\004R\010vendorId\022&\n\017ban" +
      "k_account_id\030\017 \001(\004R\rbankAccountId\022\037\n\013cur" +
      "rency_id\030\020 \001(\004R\ncurrencyId\022C\n\020transactio" +
      "n_type\030\021 \001(\0162\030.Scailo.TRANSACTION_TYPER\017" +
      "transactionType\022\037\n\013amount_base\030\022 \001(\004R\nam" +
      "ountBase\022\035\n\namount_net\030\023 \001(\004R\tamountNet\022" +
      "+\n\021payment_timestamp\030\024 \001(\004R\020paymentTimes" +
      "tamp\022 \n\013description\030\025 \001(\tR\013description\"D" +
      "\n\025PurchasesPaymentsList\022+\n\004list\030\001 \003(\0132\027." +
      "Scailo.PurchasePaymentR\004list\"\305\002\n%Purchas" +
      "esPaymentsServicePaginationReq\0220\n\tis_act" +
      "ive\030\001 \001(\0162\023.Scailo.BOOL_FILTERR\010isActive" +
      "\022\035\n\005count\030\002 \001(\003B\007\272H\004\"\002 \000R\005count\022\037\n\006offse" +
      "t\030\003 \001(\004B\007\272H\0042\002(\000R\006offset\0221\n\nsort_order\030\004" +
      " \001(\0162\022.Scailo.SORT_ORDERR\tsortOrder\022<\n\010s" +
      "ort_key\030\005 \001(\0162!.Scailo.PURCHASE_PAYMENT_" +
      "SORT_KEYR\007sortKey\0229\n\006status\030\006 \001(\0162!.Scai" +
      "lo.STANDARD_LIFECYCLE_STATUSR\006status\"\243\001\n" +
      "*PurchasesPaymentsServicePaginationRespo" +
      "nse\022\024\n\005count\030\001 \001(\004R\005count\022\026\n\006offset\030\002 \001(" +
      "\004R\006offset\022\024\n\005total\030\003 \001(\004R\005total\0221\n\007paylo" +
      "ad\030\004 \003(\0132\027.Scailo.PurchasePaymentR\007paylo" +
      "ad\"\231\n\n!PurchasesPaymentsServiceFilterReq" +
      "\0220\n\tis_active\030\001 \001(\0162\023.Scailo.BOOL_FILTER" +
      "R\010isActive\022&\n\005count\030\002 \001(\003B\020\272H\r\"\013(\377\377\377\377\377\377\377" +
      "\377\377\001R\005count\022\037\n\006offset\030\003 \001(\004B\007\272H\0042\002(\000R\006off" +
      "set\0221\n\nsort_order\030\004 \001(\0162\022.Scailo.SORT_OR" +
      "DERR\tsortOrder\022<\n\010sort_key\030\005 \001(\0162!.Scail" +
      "o.PURCHASE_PAYMENT_SORT_KEYR\007sortKey\0228\n\030" +
      "creation_timestamp_start\030e \001(\004R\026creation" +
      "TimestampStart\0224\n\026creation_timestamp_end" +
      "\030f \001(\004R\024creationTimestampEnd\022@\n\034modifica" +
      "tion_timestamp_start\030g \001(\004R\032modification" +
      "TimestampStart\022<\n\032modification_timestamp" +
      "_end\030h \001(\004R\030modificationTimestampEnd\022\037\n\013" +
      "entity_uuid\030\010 \001(\tR\nentityUuid\0229\n\006status\030" +
      "\n \001(\0162!.Scailo.STANDARD_LIFECYCLE_STATUS" +
      "R\006status\022*\n\021approved_on_start\030\013 \001(\004R\017app" +
      "rovedOnStart\022&\n\017approved_on_end\030\014 \001(\004R\ra" +
      "pprovedOnEnd\022-\n\023approved_by_user_id\030\r \001(" +
      "\004R\020approvedByUserId\022(\n\020approver_role_id\030" +
      "\016 \001(\004R\016approverRoleId\022,\n\022completed_on_st" +
      "art\030\017 \001(\004R\020completedOnStart\022(\n\020completed" +
      "_on_end\030\020 \001(\004R\016completedOnEnd\022!\n\014referen" +
      "ce_id\030\024 \001(\tR\013referenceId\022(\n\020final_ref_nu" +
      "mber\030\025 \001(\tR\016finalRefNumber\022<\n\010ref_from\030\026" +
      " \001(\0162!.Scailo.PURCHASE_PAYMENT_REF_FROMR" +
      "\007refFrom\022\025\n\006ref_id\030\027 \001(\004R\005refId\022\033\n\tvendo" +
      "r_id\030\030 \001(\004R\010vendorId\022&\n\017bank_account_id\030" +
      "\031 \001(\004R\rbankAccountId\022\037\n\013currency_id\030\032 \001(" +
      "\004R\ncurrencyId\022C\n\020transaction_type\030\033 \001(\0162" +
      "\030.Scailo.TRANSACTION_TYPER\017transactionTy" +
      "pe\0226\n\027payment_timestamp_start\030\034 \001(\004R\025pay" +
      "mentTimestampStart\0222\n\025payment_timestamp_" +
      "end\030\035 \001(\004R\023paymentTimestampEnd\"\336\010\n Purch" +
      "asesPaymentsServiceCountReq\0220\n\tis_active" +
      "\030\001 \001(\0162\023.Scailo.BOOL_FILTERR\010isActive\0228\n" +
      "\030creation_timestamp_start\030e \001(\004R\026creatio" +
      "nTimestampStart\0224\n\026creation_timestamp_en" +
      "d\030f \001(\004R\024creationTimestampEnd\022@\n\034modific" +
      "ation_timestamp_start\030g \001(\004R\032modificatio" +
      "nTimestampStart\022<\n\032modification_timestam" +
      "p_end\030h \001(\004R\030modificationTimestampEnd\022\037\n" +
      "\013entity_uuid\030\010 \001(\tR\nentityUuid\0229\n\006status" +
      "\030\n \001(\0162!.Scailo.STANDARD_LIFECYCLE_STATU" +
      "SR\006status\022*\n\021approved_on_start\030\013 \001(\004R\017ap" +
      "provedOnStart\022&\n\017approved_on_end\030\014 \001(\004R\r" +
      "approvedOnEnd\022-\n\023approved_by_user_id\030\r \001" +
      "(\004R\020approvedByUserId\022(\n\020approver_role_id" +
      "\030\016 \001(\004R\016approverRoleId\022,\n\022completed_on_s" +
      "tart\030\017 \001(\004R\020completedOnStart\022(\n\020complete" +
      "d_on_end\030\020 \001(\004R\016completedOnEnd\022!\n\014refere" +
      "nce_id\030\024 \001(\tR\013referenceId\022(\n\020final_ref_n" +
      "umber\030\025 \001(\tR\016finalRefNumber\022<\n\010ref_from\030" +
      "\026 \001(\0162!.Scailo.PURCHASE_PAYMENT_REF_FROM" +
      "R\007refFrom\022\025\n\006ref_id\030\027 \001(\004R\005refId\022\033\n\tvend" +
      "or_id\030\030 \001(\004R\010vendorId\022&\n\017bank_account_id" +
      "\030\031 \001(\004R\rbankAccountId\022\037\n\013currency_id\030\032 \001" +
      "(\004R\ncurrencyId\022C\n\020transaction_type\030\033 \001(\016" +
      "2\030.Scailo.TRANSACTION_TYPER\017transactionT" +
      "ype\0226\n\027payment_timestamp_start\030\034 \001(\004R\025pa" +
      "ymentTimestampStart\0222\n\025payment_timestamp" +
      "_end\030\035 \001(\004R\023paymentTimestampEnd\"\252\003\n$Purc" +
      "hasesPaymentsServiceSearchAllReq\0220\n\tis_a" +
      "ctive\030\001 \001(\0162\023.Scailo.BOOL_FILTERR\010isActi" +
      "ve\022&\n\005count\030\002 \001(\003B\020\272H\r\"\013(\377\377\377\377\377\377\377\377\377\001R\005cou" +
      "nt\022\037\n\006offset\030\003 \001(\004B\007\272H\0042\002(\000R\006offset\0221\n\ns" +
      "ort_order\030\004 \001(\0162\022.Scailo.SORT_ORDERR\tsor" +
      "tOrder\022<\n\010sort_key\030\005 \001(\0162!.Scailo.PURCHA" +
      "SE_PAYMENT_SORT_KEYR\007sortKey\022\037\n\013entity_u" +
      "uid\030\006 \001(\tR\nentityUuid\0229\n\006status\030\n \001(\0162!." +
      "Scailo.STANDARD_LIFECYCLE_STATUSR\006status" +
      "\022\035\n\nsearch_key\030\013 \001(\tR\tsearchKey\022\033\n\tvendo" +
      "r_id\030\031 \001(\004R\010vendorId*\320\001\n\031PURCHASE_PAYMEN" +
      "T_REF_FROM\022-\n)PURCHASE_PAYMENT_REF_FROM_" +
      "ANY_UNSPECIFIED\020\000\022,\n(PURCHASE_PAYMENT_RE" +
      "F_FROM_PURCHASE_ORDER\020\001\022,\n(PURCHASE_PAYM" +
      "ENT_REF_FROM_VENDOR_INVOICE\020\002\022(\n$PURCHAS" +
      "E_PAYMENT_REF_FROM_DEBIT_NOTE\020\003*\335\003\n\031PURC" +
      "HASE_PAYMENT_SORT_KEY\022,\n(PURCHASE_PAYMEN" +
      "T_SORT_KEY_ID_UNSPECIFIED\020\000\022(\n$PURCHASE_" +
      "PAYMENT_SORT_KEY_CREATED_AT\020\001\022)\n%PURCHAS" +
      "E_PAYMENT_SORT_KEY_MODIFIED_AT\020\002\022)\n%PURC" +
      "HASE_PAYMENT_SORT_KEY_APPROVED_ON\020\003\022)\n%P" +
      "URCHASE_PAYMENT_SORT_KEY_APPROVED_BY\020\004\022." +
      "\n*PURCHASE_PAYMENT_SORT_KEY_APPROVER_ROL" +
      "E_ID\020\005\022*\n&PURCHASE_PAYMENT_SORT_KEY_COMP" +
      "LETED_ON\020\006\022*\n&PURCHASE_PAYMENT_SORT_KEY_" +
      "REFERENCE_ID\020\n\022.\n*PURCHASE_PAYMENT_SORT_" +
      "KEY_FINAL_REF_NUMBER\020\013\022/\n+PURCHASE_PAYME" +
      "NT_SORT_KEY_PAYMENT_TIMESTAMP\020\0142\226\024\n\030Purc" +
      "hasesPaymentsService\022S\n\006Create\022-.Scailo." +
      "PurchasesPaymentsServiceCreateRequest\032\032." +
      "Scailo.IdentifierResponse\022R\n\005Draft\022-.Sca" +
      "ilo.PurchasesPaymentsServiceCreateReques" +
      "t\032\032.Scailo.IdentifierResponse\022X\n\013DraftUp" +
      "date\022-.Scailo.PurchasesPaymentsServiceUp" +
      "dateRequest\032\032.Scailo.IdentifierResponse\022" +
      "X\n\023SendForVerification\022%.Scailo.Identifi" +
      "erUUIDWithUserComment\032\032.Scailo.Identifie" +
      "rResponse\022K\n\006Verify\022%.Scailo.IdentifierU" +
      "UIDWithUserComment\032\032.Scailo.IdentifierRe" +
      "sponse\022L\n\007Approve\022%.Scailo.IdentifierUUI" +
      "DWithUserComment\032\032.Scailo.IdentifierResp" +
      "onse\022T\n\017SendForRevision\022%.Scailo.Identif" +
      "ierUUIDWithUserComment\032\032.Scailo.Identifi" +
      "erResponse\022[\n\016RevisionUpdate\022-.Scailo.Pu" +
      "rchasesPaymentsServiceUpdateRequest\032\032.Sc" +
      "ailo.IdentifierResponse\022I\n\004Halt\022%.Scailo" +
      ".IdentifierUUIDWithUserComment\032\032.Scailo." +
      "IdentifierResponse\022L\n\007Discard\022%.Scailo.I" +
      "dentifierUUIDWithUserComment\032\032.Scailo.Id" +
      "entifierResponse\022L\n\007Restore\022%.Scailo.Ide" +
      "ntifierUUIDWithUserComment\032\032.Scailo.Iden" +
      "tifierResponse\022M\n\010Complete\022%.Scailo.Iden" +
      "tifierUUIDWithUserComment\032\032.Scailo.Ident" +
      "ifierResponse\022K\n\006Repeat\022%.Scailo.Identif" +
      "ierUUIDWithUserComment\032\032.Scailo.Identifi" +
      "erResponse\022O\n\nCommentAdd\022%.Scailo.Identi" +
      "fierUUIDWithUserComment\032\032.Scailo.Identif" +
      "ierResponse\022N\n\tSendEmail\022%.Scailo.Identi" +
      "fierWithEmailAttributes\032\032.Scailo.Identif" +
      "ierResponse\022_\n\017CreateMagicLink\0229.Scailo." +
      "MagicLinksServiceCreateRequestForSpecifi" +
      "cResource\032\021.Scailo.MagicLink\0227\n\010ViewByID" +
      "\022\022.Scailo.Identifier\032\027.Scailo.PurchasePa" +
      "yment\022=\n\nViewByUUID\022\026.Scailo.IdentifierU" +
      "UID\032\027.Scailo.PurchasePayment\022@\n\021ViewEsse" +
      "ntialByID\022\022.Scailo.Identifier\032\027.Scailo.P" +
      "urchasePayment\022F\n\023ViewEssentialByUUID\022\026." +
      "Scailo.IdentifierUUID\032\027.Scailo.PurchaseP" +
      "ayment\022E\n\013ViewFromIDs\022\027.Scailo.Identifie" +
      "rsList\032\035.Scailo.PurchasesPaymentsList\022c\n" +
      "\035ViewAncillaryParametersByUUID\022\026.Scailo." +
      "IdentifierUUID\032*.Scailo.PurchasePaymentA" +
      "ncillaryParameters\022>\n\007ViewAll\022\024.Scailo.A" +
      "ctiveStatus\032\035.Scailo.PurchasesPaymentsLi" +
      "st\022M\n\024ViewAllForEntityUUID\022\026.Scailo.Iden" +
      "tifierUUID\032\035.Scailo.PurchasesPaymentsLis" +
      "t\022w\n\022ViewWithPagination\022-.Scailo.Purchas" +
      "esPaymentsServicePaginationReq\0322.Scailo." +
      "PurchasesPaymentsServicePaginationRespon" +
      "se\022A\n\016IsDownloadable\022\026.Scailo.Identifier" +
      "UUID\032\027.Scailo.BooleanResponse\022>\n\016Downloa" +
      "dByUUID\022\026.Scailo.IdentifierUUID\032\024.Scailo" +
      ".StandardFile\022X\n\tSearchAll\022,.Scailo.Purc" +
      "hasesPaymentsServiceSearchAllReq\032\035.Scail" +
      "o.PurchasesPaymentsList\022R\n\006Filter\022).Scai" +
      "lo.PurchasesPaymentsServiceFilterReq\032\035.S" +
      "cailo.PurchasesPaymentsList\022G\n\rCountInSt" +
      "atus\022\037.Scailo.CountInSLCStatusRequest\032\025." +
      "Scailo.CountResponse\022H\n\005Count\022(.Scailo.P" +
      "urchasesPaymentsServiceCountReq\032\025.Scailo" +
      ".CountResponse\022P\n\rDownloadAsCSV\022).Scailo" +
      ".PurchasesPaymentsServiceFilterReq\032\024.Sca" +
      "ilo.StandardFileBv\n\016com.scailo.sdkB\034Purc" +
      "hasesPaymentsScailoProtoP\001Z\nScailo/sdk\242\002" +
      "\003SXX\252\002\nScailo.Sdk\312\002\006Scailo\342\002\022Scailo\\GPBM" +
      "etadata\352\002\006Scailob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.scailo.sdk.BaseScailoProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
          com.scailo.sdk.MagicLinksScailoProto.getDescriptor(),
        });
    internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor,
        new java.lang.String[] { "EntityUuid", "UserComment", "VaultFolderId", "ReferenceId", "RefFrom", "RefId", "BankAccountId", "CurrencyId", "TransactionType", "AmountBase", "AmountNet", "PaymentTimestamp", "Description", });
    internal_static_Scailo_PurchasesPaymentsServiceUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Scailo_PurchasesPaymentsServiceUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServiceUpdateRequest_descriptor,
        new java.lang.String[] { "UserComment", "Id", "NotifyUsers", "VaultFolderId", "ReferenceId", "BankAccountId", "CurrencyId", "TransactionType", "AmountBase", "AmountNet", "PaymentTimestamp", "Description", });
    internal_static_Scailo_PurchasePaymentAncillaryParameters_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Scailo_PurchasePaymentAncillaryParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasePaymentAncillaryParameters_descriptor,
        new java.lang.String[] { "RefUuid", "VendorUuid", "BankAccountUuid", "CurrencyUuid", });
    internal_static_Scailo_PurchasePayment_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Scailo_PurchasePayment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasePayment_descriptor,
        new java.lang.String[] { "EntityUuid", "Metadata", "ApprovalMetadata", "Status", "Logs", "CompletedOn", "VaultFolderId", "ReferenceId", "FinalRefNumber", "RefFrom", "RefId", "VendorId", "BankAccountId", "CurrencyId", "TransactionType", "AmountBase", "AmountNet", "PaymentTimestamp", "Description", });
    internal_static_Scailo_PurchasesPaymentsList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Scailo_PurchasesPaymentsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_Scailo_PurchasesPaymentsServicePaginationReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Scailo_PurchasesPaymentsServicePaginationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServicePaginationReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "Status", });
    internal_static_Scailo_PurchasesPaymentsServicePaginationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Scailo_PurchasesPaymentsServicePaginationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServicePaginationResponse_descriptor,
        new java.lang.String[] { "Count", "Offset", "Total", "Payload", });
    internal_static_Scailo_PurchasesPaymentsServiceFilterReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Scailo_PurchasesPaymentsServiceFilterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServiceFilterReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "CreationTimestampStart", "CreationTimestampEnd", "ModificationTimestampStart", "ModificationTimestampEnd", "EntityUuid", "Status", "ApprovedOnStart", "ApprovedOnEnd", "ApprovedByUserId", "ApproverRoleId", "CompletedOnStart", "CompletedOnEnd", "ReferenceId", "FinalRefNumber", "RefFrom", "RefId", "VendorId", "BankAccountId", "CurrencyId", "TransactionType", "PaymentTimestampStart", "PaymentTimestampEnd", });
    internal_static_Scailo_PurchasesPaymentsServiceCountReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Scailo_PurchasesPaymentsServiceCountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServiceCountReq_descriptor,
        new java.lang.String[] { "IsActive", "CreationTimestampStart", "CreationTimestampEnd", "ModificationTimestampStart", "ModificationTimestampEnd", "EntityUuid", "Status", "ApprovedOnStart", "ApprovedOnEnd", "ApprovedByUserId", "ApproverRoleId", "CompletedOnStart", "CompletedOnEnd", "ReferenceId", "FinalRefNumber", "RefFrom", "RefId", "VendorId", "BankAccountId", "CurrencyId", "TransactionType", "PaymentTimestampStart", "PaymentTimestampEnd", });
    internal_static_Scailo_PurchasesPaymentsServiceSearchAllReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Scailo_PurchasesPaymentsServiceSearchAllReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_PurchasesPaymentsServiceSearchAllReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "EntityUuid", "Status", "SearchKey", "VendorId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.scailo.sdk.BaseScailoProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.scailo.sdk.MagicLinksScailoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
