// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchases_payments.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the parameters necessary to create a record
 * </pre>
 *
 * Protobuf type {@code Scailo.PurchasesPaymentsServiceCreateRequest}
 */
public final class PurchasesPaymentsServiceCreateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Scailo.PurchasesPaymentsServiceCreateRequest)
    PurchasesPaymentsServiceCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PurchasesPaymentsServiceCreateRequest.newBuilder() to construct.
  private PurchasesPaymentsServiceCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PurchasesPaymentsServiceCreateRequest() {
    entityUuid_ = "";
    userComment_ = "";
    referenceId_ = "";
    refFrom_ = 0;
    transactionType_ = 0;
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PurchasesPaymentsServiceCreateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scailo.sdk.PurchasesPaymentsScailoProto.internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scailo.sdk.PurchasesPaymentsScailoProto.internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.class, com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.Builder.class);
  }

  public static final int ENTITY_UUID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entityUuid_ = "";
  /**
   * <pre>
   * Stores a globally unique entity UUID. This will be set at the organization level
   * </pre>
   *
   * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
   * @return The entityUuid.
   */
  @java.lang.Override
  public java.lang.String getEntityUuid() {
    java.lang.Object ref = entityUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stores a globally unique entity UUID. This will be set at the organization level
   * </pre>
   *
   * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
   * @return The bytes for entityUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityUuidBytes() {
    java.lang.Object ref = entityUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_COMMENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userComment_ = "";
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 2 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  @java.lang.Override
  public java.lang.String getUserComment() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userComment_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 2 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserCommentBytes() {
    java.lang.Object ref = userComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAULT_FOLDER_ID_FIELD_NUMBER = 9;
  private long vaultFolderId_ = 0L;
  /**
   * <pre>
   * The associated vault folder ID
   * </pre>
   *
   * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
   * @return The vaultFolderId.
   */
  @java.lang.Override
  public long getVaultFolderId() {
    return vaultFolderId_;
  }

  public static final int REFERENCE_ID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object referenceId_ = "";
  /**
   * <pre>
   * The reference ID of the purchase payment
   * </pre>
   *
   * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The reference ID of the purchase payment
   * </pre>
   *
   * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REF_FROM_FIELD_NUMBER = 12;
  private int refFrom_ = 0;
  /**
   * <pre>
   * The reference on which the purchase payment has been created
   * </pre>
   *
   * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
   * @return The enum numeric value on the wire for refFrom.
   */
  @java.lang.Override public int getRefFromValue() {
    return refFrom_;
  }
  /**
   * <pre>
   * The reference on which the purchase payment has been created
   * </pre>
   *
   * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
   * @return The refFrom.
   */
  @java.lang.Override public com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM getRefFrom() {
    com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM result = com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.forNumber(refFrom_);
    return result == null ? com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.UNRECOGNIZED : result;
  }

  public static final int REF_ID_FIELD_NUMBER = 13;
  private long refId_ = 0L;
  /**
   * <pre>
   * The ID of the associated reference
   * </pre>
   *
   * <code>uint64 ref_id = 13 [json_name = "refId", (.buf.validate.field) = { ... }</code>
   * @return The refId.
   */
  @java.lang.Override
  public long getRefId() {
    return refId_;
  }

  public static final int BANK_ACCOUNT_ID_FIELD_NUMBER = 15;
  private long bankAccountId_ = 0L;
  /**
   * <pre>
   * The ID of the associated bank account
   * </pre>
   *
   * <code>uint64 bank_account_id = 15 [json_name = "bankAccountId", (.buf.validate.field) = { ... }</code>
   * @return The bankAccountId.
   */
  @java.lang.Override
  public long getBankAccountId() {
    return bankAccountId_;
  }

  public static final int CURRENCY_ID_FIELD_NUMBER = 16;
  private long currencyId_ = 0L;
  /**
   * <pre>
   * The ID of the associated currency
   * </pre>
   *
   * <code>uint64 currency_id = 16 [json_name = "currencyId", (.buf.validate.field) = { ... }</code>
   * @return The currencyId.
   */
  @java.lang.Override
  public long getCurrencyId() {
    return currencyId_;
  }

  public static final int TRANSACTION_TYPE_FIELD_NUMBER = 17;
  private int transactionType_ = 0;
  /**
   * <pre>
   * The type of the transaction
   * </pre>
   *
   * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
   * @return The enum numeric value on the wire for transactionType.
   */
  @java.lang.Override public int getTransactionTypeValue() {
    return transactionType_;
  }
  /**
   * <pre>
   * The type of the transaction
   * </pre>
   *
   * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
   * @return The transactionType.
   */
  @java.lang.Override public com.scailo.sdk.TRANSACTION_TYPE getTransactionType() {
    com.scailo.sdk.TRANSACTION_TYPE result = com.scailo.sdk.TRANSACTION_TYPE.forNumber(transactionType_);
    return result == null ? com.scailo.sdk.TRANSACTION_TYPE.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_BASE_FIELD_NUMBER = 18;
  private long amountBase_ = 0L;
  /**
   * <pre>
   * The initial amount in cents, without any deductions
   * </pre>
   *
   * <code>uint64 amount_base = 18 [json_name = "amountBase", (.buf.validate.field) = { ... }</code>
   * @return The amountBase.
   */
  @java.lang.Override
  public long getAmountBase() {
    return amountBase_;
  }

  public static final int AMOUNT_NET_FIELD_NUMBER = 19;
  private long amountNet_ = 0L;
  /**
   * <pre>
   * The final amount in cents, after all the deductions
   * </pre>
   *
   * <code>uint64 amount_net = 19 [json_name = "amountNet", (.buf.validate.field) = { ... }</code>
   * @return The amountNet.
   */
  @java.lang.Override
  public long getAmountNet() {
    return amountNet_;
  }

  public static final int PAYMENT_TIMESTAMP_FIELD_NUMBER = 20;
  private long paymentTimestamp_ = 0L;
  /**
   * <pre>
   * The date &amp; time of when the payment needs to be made
   * </pre>
   *
   * <code>uint64 payment_timestamp = 20 [json_name = "paymentTimestamp", (.buf.validate.field) = { ... }</code>
   * @return The paymentTimestamp.
   */
  @java.lang.Override
  public long getPaymentTimestamp() {
    return paymentTimestamp_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 21;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * The description of the purchase payment
   * </pre>
   *
   * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The description of the purchase payment
   * </pre>
   *
   * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityUuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entityUuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userComment_);
    }
    if (vaultFolderId_ != 0L) {
      output.writeUInt64(9, vaultFolderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(referenceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, referenceId_);
    }
    if (refFrom_ != com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.PURCHASE_PAYMENT_REF_FROM_ANY_UNSPECIFIED.getNumber()) {
      output.writeEnum(12, refFrom_);
    }
    if (refId_ != 0L) {
      output.writeUInt64(13, refId_);
    }
    if (bankAccountId_ != 0L) {
      output.writeUInt64(15, bankAccountId_);
    }
    if (currencyId_ != 0L) {
      output.writeUInt64(16, currencyId_);
    }
    if (transactionType_ != com.scailo.sdk.TRANSACTION_TYPE.TRANSACTION_TYPE_ANY_UNSPECIFIED.getNumber()) {
      output.writeEnum(17, transactionType_);
    }
    if (amountBase_ != 0L) {
      output.writeUInt64(18, amountBase_);
    }
    if (amountNet_ != 0L) {
      output.writeUInt64(19, amountNet_);
    }
    if (paymentTimestamp_ != 0L) {
      output.writeUInt64(20, paymentTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 21, description_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityUuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entityUuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userComment_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userComment_);
    }
    if (vaultFolderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, vaultFolderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(referenceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, referenceId_);
    }
    if (refFrom_ != com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.PURCHASE_PAYMENT_REF_FROM_ANY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, refFrom_);
    }
    if (refId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, refId_);
    }
    if (bankAccountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(15, bankAccountId_);
    }
    if (currencyId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(16, currencyId_);
    }
    if (transactionType_ != com.scailo.sdk.TRANSACTION_TYPE.TRANSACTION_TYPE_ANY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(17, transactionType_);
    }
    if (amountBase_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(18, amountBase_);
    }
    if (amountNet_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(19, amountNet_);
    }
    if (paymentTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(20, paymentTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, description_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scailo.sdk.PurchasesPaymentsServiceCreateRequest)) {
      return super.equals(obj);
    }
    com.scailo.sdk.PurchasesPaymentsServiceCreateRequest other = (com.scailo.sdk.PurchasesPaymentsServiceCreateRequest) obj;

    if (!getEntityUuid()
        .equals(other.getEntityUuid())) return false;
    if (!getUserComment()
        .equals(other.getUserComment())) return false;
    if (getVaultFolderId()
        != other.getVaultFolderId()) return false;
    if (!getReferenceId()
        .equals(other.getReferenceId())) return false;
    if (refFrom_ != other.refFrom_) return false;
    if (getRefId()
        != other.getRefId()) return false;
    if (getBankAccountId()
        != other.getBankAccountId()) return false;
    if (getCurrencyId()
        != other.getCurrencyId()) return false;
    if (transactionType_ != other.transactionType_) return false;
    if (getAmountBase()
        != other.getAmountBase()) return false;
    if (getAmountNet()
        != other.getAmountNet()) return false;
    if (getPaymentTimestamp()
        != other.getPaymentTimestamp()) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITY_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getEntityUuid().hashCode();
    hash = (37 * hash) + USER_COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserComment().hashCode();
    hash = (37 * hash) + VAULT_FOLDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVaultFolderId());
    hash = (37 * hash) + REFERENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceId().hashCode();
    hash = (37 * hash) + REF_FROM_FIELD_NUMBER;
    hash = (53 * hash) + refFrom_;
    hash = (37 * hash) + REF_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRefId());
    hash = (37 * hash) + BANK_ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBankAccountId());
    hash = (37 * hash) + CURRENCY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrencyId());
    hash = (37 * hash) + TRANSACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + transactionType_;
    hash = (37 * hash) + AMOUNT_BASE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountBase());
    hash = (37 * hash) + AMOUNT_NET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountNet());
    hash = (37 * hash) + PAYMENT_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPaymentTimestamp());
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scailo.sdk.PurchasesPaymentsServiceCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Describes the parameters necessary to create a record
   * </pre>
   *
   * Protobuf type {@code Scailo.PurchasesPaymentsServiceCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Scailo.PurchasesPaymentsServiceCreateRequest)
      com.scailo.sdk.PurchasesPaymentsServiceCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scailo.sdk.PurchasesPaymentsScailoProto.internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scailo.sdk.PurchasesPaymentsScailoProto.internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.class, com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.Builder.class);
    }

    // Construct using com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      entityUuid_ = "";
      userComment_ = "";
      vaultFolderId_ = 0L;
      referenceId_ = "";
      refFrom_ = 0;
      refId_ = 0L;
      bankAccountId_ = 0L;
      currencyId_ = 0L;
      transactionType_ = 0;
      amountBase_ = 0L;
      amountNet_ = 0L;
      paymentTimestamp_ = 0L;
      description_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scailo.sdk.PurchasesPaymentsScailoProto.internal_static_Scailo_PurchasesPaymentsServiceCreateRequest_descriptor;
    }

    @java.lang.Override
    public com.scailo.sdk.PurchasesPaymentsServiceCreateRequest getDefaultInstanceForType() {
      return com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scailo.sdk.PurchasesPaymentsServiceCreateRequest build() {
      com.scailo.sdk.PurchasesPaymentsServiceCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scailo.sdk.PurchasesPaymentsServiceCreateRequest buildPartial() {
      com.scailo.sdk.PurchasesPaymentsServiceCreateRequest result = new com.scailo.sdk.PurchasesPaymentsServiceCreateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scailo.sdk.PurchasesPaymentsServiceCreateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entityUuid_ = entityUuid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userComment_ = userComment_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.vaultFolderId_ = vaultFolderId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.referenceId_ = referenceId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.refFrom_ = refFrom_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.refId_ = refId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.bankAccountId_ = bankAccountId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.currencyId_ = currencyId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.transactionType_ = transactionType_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.amountBase_ = amountBase_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.amountNet_ = amountNet_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.paymentTimestamp_ = paymentTimestamp_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.description_ = description_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scailo.sdk.PurchasesPaymentsServiceCreateRequest) {
        return mergeFrom((com.scailo.sdk.PurchasesPaymentsServiceCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scailo.sdk.PurchasesPaymentsServiceCreateRequest other) {
      if (other == com.scailo.sdk.PurchasesPaymentsServiceCreateRequest.getDefaultInstance()) return this;
      if (!other.getEntityUuid().isEmpty()) {
        entityUuid_ = other.entityUuid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getUserComment().isEmpty()) {
        userComment_ = other.userComment_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getVaultFolderId() != 0L) {
        setVaultFolderId(other.getVaultFolderId());
      }
      if (!other.getReferenceId().isEmpty()) {
        referenceId_ = other.referenceId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.refFrom_ != 0) {
        setRefFromValue(other.getRefFromValue());
      }
      if (other.getRefId() != 0L) {
        setRefId(other.getRefId());
      }
      if (other.getBankAccountId() != 0L) {
        setBankAccountId(other.getBankAccountId());
      }
      if (other.getCurrencyId() != 0L) {
        setCurrencyId(other.getCurrencyId());
      }
      if (other.transactionType_ != 0) {
        setTransactionTypeValue(other.getTransactionTypeValue());
      }
      if (other.getAmountBase() != 0L) {
        setAmountBase(other.getAmountBase());
      }
      if (other.getAmountNet() != 0L) {
        setAmountNet(other.getAmountNet());
      }
      if (other.getPaymentTimestamp() != 0L) {
        setPaymentTimestamp(other.getPaymentTimestamp());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              entityUuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              userComment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 72: {
              vaultFolderId_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 72
            case 82: {
              referenceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 82
            case 96: {
              refFrom_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 96
            case 104: {
              refId_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 104
            case 120: {
              bankAccountId_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 120
            case 128: {
              currencyId_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 128
            case 136: {
              transactionType_ = input.readEnum();
              bitField0_ |= 0x00000100;
              break;
            } // case 136
            case 144: {
              amountBase_ = input.readUInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 144
            case 152: {
              amountNet_ = input.readUInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 152
            case 160: {
              paymentTimestamp_ = input.readUInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 160
            case 170: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object entityUuid_ = "";
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     * @return The entityUuid.
     */
    public java.lang.String getEntityUuid() {
      java.lang.Object ref = entityUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     * @return The bytes for entityUuid.
     */
    public com.google.protobuf.ByteString
        getEntityUuidBytes() {
      java.lang.Object ref = entityUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     * @param value The entityUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEntityUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entityUuid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityUuid() {
      entityUuid_ = getDefaultInstance().getEntityUuid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores a globally unique entity UUID. This will be set at the organization level
     * </pre>
     *
     * <code>string entity_uuid = 1 [json_name = "entityUuid"];</code>
     * @param value The bytes for entityUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEntityUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entityUuid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object userComment_ = "";
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     * @return The userComment.
     */
    public java.lang.String getUserComment() {
      java.lang.Object ref = userComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     * @return The bytes for userComment.
     */
    public com.google.protobuf.ByteString
        getUserCommentBytes() {
      java.lang.Object ref = userComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     * @param value The userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserComment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userComment_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserComment() {
      userComment_ = getDefaultInstance().getUserComment();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 2 [json_name = "userComment"];</code>
     * @param value The bytes for userComment to set.
     * @return This builder for chaining.
     */
    public Builder setUserCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userComment_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long vaultFolderId_ ;
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @return The vaultFolderId.
     */
    @java.lang.Override
    public long getVaultFolderId() {
      return vaultFolderId_;
    }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @param value The vaultFolderId to set.
     * @return This builder for chaining.
     */
    public Builder setVaultFolderId(long value) {
      
      vaultFolderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearVaultFolderId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      vaultFolderId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object referenceId_ = "";
    /**
     * <pre>
     * The reference ID of the purchase payment
     * </pre>
     *
     * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
     * @return The referenceId.
     */
    public java.lang.String getReferenceId() {
      java.lang.Object ref = referenceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The reference ID of the purchase payment
     * </pre>
     *
     * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for referenceId.
     */
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      java.lang.Object ref = referenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The reference ID of the purchase payment
     * </pre>
     *
     * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      referenceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference ID of the purchase payment
     * </pre>
     *
     * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      referenceId_ = getDefaultInstance().getReferenceId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference ID of the purchase payment
     * </pre>
     *
     * <code>string reference_id = 10 [json_name = "referenceId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      referenceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int refFrom_ = 0;
    /**
     * <pre>
     * The reference on which the purchase payment has been created
     * </pre>
     *
     * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
     * @return The enum numeric value on the wire for refFrom.
     */
    @java.lang.Override public int getRefFromValue() {
      return refFrom_;
    }
    /**
     * <pre>
     * The reference on which the purchase payment has been created
     * </pre>
     *
     * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
     * @param value The enum numeric value on the wire for refFrom to set.
     * @return This builder for chaining.
     */
    public Builder setRefFromValue(int value) {
      refFrom_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference on which the purchase payment has been created
     * </pre>
     *
     * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
     * @return The refFrom.
     */
    @java.lang.Override
    public com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM getRefFrom() {
      com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM result = com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.forNumber(refFrom_);
      return result == null ? com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The reference on which the purchase payment has been created
     * </pre>
     *
     * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
     * @param value The refFrom to set.
     * @return This builder for chaining.
     */
    public Builder setRefFrom(com.scailo.sdk.PURCHASE_PAYMENT_REF_FROM value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      refFrom_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The reference on which the purchase payment has been created
     * </pre>
     *
     * <code>.Scailo.PURCHASE_PAYMENT_REF_FROM ref_from = 12 [json_name = "refFrom"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefFrom() {
      bitField0_ = (bitField0_ & ~0x00000010);
      refFrom_ = 0;
      onChanged();
      return this;
    }

    private long refId_ ;
    /**
     * <pre>
     * The ID of the associated reference
     * </pre>
     *
     * <code>uint64 ref_id = 13 [json_name = "refId", (.buf.validate.field) = { ... }</code>
     * @return The refId.
     */
    @java.lang.Override
    public long getRefId() {
      return refId_;
    }
    /**
     * <pre>
     * The ID of the associated reference
     * </pre>
     *
     * <code>uint64 ref_id = 13 [json_name = "refId", (.buf.validate.field) = { ... }</code>
     * @param value The refId to set.
     * @return This builder for chaining.
     */
    public Builder setRefId(long value) {
      
      refId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the associated reference
     * </pre>
     *
     * <code>uint64 ref_id = 13 [json_name = "refId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRefId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      refId_ = 0L;
      onChanged();
      return this;
    }

    private long bankAccountId_ ;
    /**
     * <pre>
     * The ID of the associated bank account
     * </pre>
     *
     * <code>uint64 bank_account_id = 15 [json_name = "bankAccountId", (.buf.validate.field) = { ... }</code>
     * @return The bankAccountId.
     */
    @java.lang.Override
    public long getBankAccountId() {
      return bankAccountId_;
    }
    /**
     * <pre>
     * The ID of the associated bank account
     * </pre>
     *
     * <code>uint64 bank_account_id = 15 [json_name = "bankAccountId", (.buf.validate.field) = { ... }</code>
     * @param value The bankAccountId to set.
     * @return This builder for chaining.
     */
    public Builder setBankAccountId(long value) {
      
      bankAccountId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the associated bank account
     * </pre>
     *
     * <code>uint64 bank_account_id = 15 [json_name = "bankAccountId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBankAccountId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      bankAccountId_ = 0L;
      onChanged();
      return this;
    }

    private long currencyId_ ;
    /**
     * <pre>
     * The ID of the associated currency
     * </pre>
     *
     * <code>uint64 currency_id = 16 [json_name = "currencyId", (.buf.validate.field) = { ... }</code>
     * @return The currencyId.
     */
    @java.lang.Override
    public long getCurrencyId() {
      return currencyId_;
    }
    /**
     * <pre>
     * The ID of the associated currency
     * </pre>
     *
     * <code>uint64 currency_id = 16 [json_name = "currencyId", (.buf.validate.field) = { ... }</code>
     * @param value The currencyId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyId(long value) {
      
      currencyId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the associated currency
     * </pre>
     *
     * <code>uint64 currency_id = 16 [json_name = "currencyId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyId() {
      bitField0_ = (bitField0_ & ~0x00000080);
      currencyId_ = 0L;
      onChanged();
      return this;
    }

    private int transactionType_ = 0;
    /**
     * <pre>
     * The type of the transaction
     * </pre>
     *
     * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
     * @return The enum numeric value on the wire for transactionType.
     */
    @java.lang.Override public int getTransactionTypeValue() {
      return transactionType_;
    }
    /**
     * <pre>
     * The type of the transaction
     * </pre>
     *
     * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
     * @param value The enum numeric value on the wire for transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionTypeValue(int value) {
      transactionType_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the transaction
     * </pre>
     *
     * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
     * @return The transactionType.
     */
    @java.lang.Override
    public com.scailo.sdk.TRANSACTION_TYPE getTransactionType() {
      com.scailo.sdk.TRANSACTION_TYPE result = com.scailo.sdk.TRANSACTION_TYPE.forNumber(transactionType_);
      return result == null ? com.scailo.sdk.TRANSACTION_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The type of the transaction
     * </pre>
     *
     * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
     * @param value The transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionType(com.scailo.sdk.TRANSACTION_TYPE value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      transactionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of the transaction
     * </pre>
     *
     * <code>.Scailo.TRANSACTION_TYPE transaction_type = 17 [json_name = "transactionType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionType() {
      bitField0_ = (bitField0_ & ~0x00000100);
      transactionType_ = 0;
      onChanged();
      return this;
    }

    private long amountBase_ ;
    /**
     * <pre>
     * The initial amount in cents, without any deductions
     * </pre>
     *
     * <code>uint64 amount_base = 18 [json_name = "amountBase", (.buf.validate.field) = { ... }</code>
     * @return The amountBase.
     */
    @java.lang.Override
    public long getAmountBase() {
      return amountBase_;
    }
    /**
     * <pre>
     * The initial amount in cents, without any deductions
     * </pre>
     *
     * <code>uint64 amount_base = 18 [json_name = "amountBase", (.buf.validate.field) = { ... }</code>
     * @param value The amountBase to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBase(long value) {
      
      amountBase_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The initial amount in cents, without any deductions
     * </pre>
     *
     * <code>uint64 amount_base = 18 [json_name = "amountBase", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountBase() {
      bitField0_ = (bitField0_ & ~0x00000200);
      amountBase_ = 0L;
      onChanged();
      return this;
    }

    private long amountNet_ ;
    /**
     * <pre>
     * The final amount in cents, after all the deductions
     * </pre>
     *
     * <code>uint64 amount_net = 19 [json_name = "amountNet", (.buf.validate.field) = { ... }</code>
     * @return The amountNet.
     */
    @java.lang.Override
    public long getAmountNet() {
      return amountNet_;
    }
    /**
     * <pre>
     * The final amount in cents, after all the deductions
     * </pre>
     *
     * <code>uint64 amount_net = 19 [json_name = "amountNet", (.buf.validate.field) = { ... }</code>
     * @param value The amountNet to set.
     * @return This builder for chaining.
     */
    public Builder setAmountNet(long value) {
      
      amountNet_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The final amount in cents, after all the deductions
     * </pre>
     *
     * <code>uint64 amount_net = 19 [json_name = "amountNet", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountNet() {
      bitField0_ = (bitField0_ & ~0x00000400);
      amountNet_ = 0L;
      onChanged();
      return this;
    }

    private long paymentTimestamp_ ;
    /**
     * <pre>
     * The date &amp; time of when the payment needs to be made
     * </pre>
     *
     * <code>uint64 payment_timestamp = 20 [json_name = "paymentTimestamp", (.buf.validate.field) = { ... }</code>
     * @return The paymentTimestamp.
     */
    @java.lang.Override
    public long getPaymentTimestamp() {
      return paymentTimestamp_;
    }
    /**
     * <pre>
     * The date &amp; time of when the payment needs to be made
     * </pre>
     *
     * <code>uint64 payment_timestamp = 20 [json_name = "paymentTimestamp", (.buf.validate.field) = { ... }</code>
     * @param value The paymentTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentTimestamp(long value) {
      
      paymentTimestamp_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The date &amp; time of when the payment needs to be made
     * </pre>
     *
     * <code>uint64 payment_timestamp = 20 [json_name = "paymentTimestamp", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000800);
      paymentTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * The description of the purchase payment
     * </pre>
     *
     * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The description of the purchase payment
     * </pre>
     *
     * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The description of the purchase payment
     * </pre>
     *
     * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The description of the purchase payment
     * </pre>
     *
     * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The description of the purchase payment
     * </pre>
     *
     * <code>string description = 21 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Scailo.PurchasesPaymentsServiceCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:Scailo.PurchasesPaymentsServiceCreateRequest)
  private static final com.scailo.sdk.PurchasesPaymentsServiceCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scailo.sdk.PurchasesPaymentsServiceCreateRequest();
  }

  public static com.scailo.sdk.PurchasesPaymentsServiceCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PurchasesPaymentsServiceCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<PurchasesPaymentsServiceCreateRequest>() {
    @java.lang.Override
    public PurchasesPaymentsServiceCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PurchasesPaymentsServiceCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PurchasesPaymentsServiceCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scailo.sdk.PurchasesPaymentsServiceCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

