// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qc_groups.scailo.proto

package com.scailo.sdk;

public final class QcGroupsScailoProto {
  private QcGroupsScailoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceItemCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceItemCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceItemUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceItemUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsItemsList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsItemsList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupItemHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupItemHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupItemsSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupItemsSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServicePaginatedItemsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServicePaginatedItemsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServicePaginationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServicePaginationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServicePaginationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServicePaginationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceFilterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceFilterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceCountReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceCountReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Scailo_QCGroupsServiceSearchAllReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Scailo_QCGroupsServiceSearchAllReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026qc_groups.scailo.proto\022\006Scailo\032\021base.s" +
      "cailo.proto\032\033buf/validate/validate.proto" +
      "\032\036forms_fields_data.scailo.proto\"\261\002\n\034QCG" +
      "roupsServiceCreateRequest\022\037\n\013entity_uuid" +
      "\030\001 \001(\tR\nentityUuid\022!\n\014user_comment\030\002 \001(\t" +
      "R\013userComment\022/\n\017vault_folder_id\030\t \001(\004B\007" +
      "\272H\0042\002(\000R\rvaultFolderId\022\033\n\004name\030\n \001(\tB\007\272H" +
      "\004r\002\020\001R\004name\022\033\n\004code\030\013 \001(\tB\007\272H\004r\002\020\001R\004code" +
      "\022 \n\013description\030\r \001(\tR\013description\022@\n\tfo" +
      "rm_data\030\036 \003(\0132#.Scailo.FormFieldDatumCre" +
      "ateRequestR\010formData\"\314\002\n\034QCGroupsService" +
      "UpdateRequest\022!\n\014user_comment\030\001 \001(\tR\013use" +
      "rComment\022\027\n\002id\030\002 \001(\004B\007\272H\0042\002 \000R\002id\022!\n\014not" +
      "ify_users\030\003 \001(\010R\013notifyUsers\022/\n\017vault_fo" +
      "lder_id\030\t \001(\004B\007\272H\0042\002(\000R\rvaultFolderId\022\033\n" +
      "\004name\030\n \001(\tB\007\272H\004r\002\020\001R\004name\022\033\n\004code\030\013 \001(\t" +
      "B\007\272H\004r\002\020\001R\004code\022 \n\013description\030\r \001(\tR\013de" +
      "scription\022@\n\tform_data\030\036 \003(\0132#.Scailo.Fo" +
      "rmFieldDatumCreateRequestR\010formData\"\220\004\n\007" +
      "QCGroup\022\037\n\013entity_uuid\030\001 \001(\tR\nentityUuid" +
      "\0224\n\010metadata\030\002 \001(\0132\030.Scailo.EmployeeMeta" +
      "dataR\010metadata\022E\n\021approval_metadata\030\003 \001(" +
      "\0132\030.Scailo.ApprovalMetadataR\020approvalMet" +
      "adata\0229\n\006status\030\004 \001(\0162!.Scailo.STANDARD_" +
      "LIFECYCLE_STATUSR\006status\0220\n\004logs\030\005 \003(\0132\034" +
      ".Scailo.LogbookLogConciseSLCR\004logs\022!\n\014co" +
      "mpleted_on\030\006 \001(\004R\013completedOn\022&\n\017vault_f" +
      "older_id\030\t \001(\004R\rvaultFolderId\022\022\n\004name\030\n " +
      "\001(\tR\004name\022\033\n\004code\030\013 \001(\tB\007\272H\004r\002\020\001R\004code\022 " +
      "\n\013description\030\r \001(\tR\013description\022\'\n\004list" +
      "\030\024 \003(\0132\023.Scailo.QCGroupItemR\004list\0223\n\tfor" +
      "m_data\030\036 \003(\0132\026.Scailo.FormFieldDatumR\010fo" +
      "rmData\"\323\005\n QCGroupsServiceItemCreateRequ" +
      "est\022!\n\014user_comment\030\001 \001(\tR\013userComment\022\'" +
      "\n\013qc_group_id\030\n \001(\004B\007\272H\0042\002 \000R\tqcGroupId\022" +
      "\'\n\013qc_param_id\030\013 \001(\004B\007\272H\0042\002 \000R\tqcParamId" +
      "\022\036\n\006uom_id\030\014 \001(\004B\007\272H\0042\002 \000R\005uomId\022\037\n\013is_i" +
      "nternal\030\023 \001(\010R\nisInternal\022_\n\025acceptable_" +
      "value_type\030\024 \001(\0162+.Scailo.QC_GROUP_ITEM_" +
      "ACCEPTABLE_VALUE_TYPER\023acceptableValueTy" +
      "pe\0226\n\027number_acceptable_value\030\025 \001(\003R\025num" +
      "berAcceptableValue\022=\n\033number_relative_lo" +
      "wer_bound\030\026 \001(\003R\030numberRelativeLowerBoun" +
      "d\022=\n\033number_relative_upper_bound\030\027 \001(\003R\030" +
      "numberRelativeUpperBound\0224\n\026text_accepta" +
      "ble_values\030\036 \003(\tR\024textAcceptableValues\022P" +
      "\n%text_acceptable_values_with_deviation\030" +
      "\037 \003(\tR!textAcceptableValuesWithDeviation" +
      "\0228\n\030text_unacceptable_values\030  \003(\tR\026text" +
      "UnacceptableValues\022 \n\013description\030( \001(\tR" +
      "\013description\"\372\004\n QCGroupsServiceItemUpda" +
      "teRequest\022!\n\014user_comment\030\001 \001(\tR\013userCom" +
      "ment\022\027\n\002id\030\002 \001(\004B\007\272H\0042\002 \000R\002id\022\037\n\013is_inte" +
      "rnal\030\023 \001(\010R\nisInternal\022_\n\025acceptable_val" +
      "ue_type\030\024 \001(\0162+.Scailo.QC_GROUP_ITEM_ACC" +
      "EPTABLE_VALUE_TYPER\023acceptableValueType\022" +
      "6\n\027number_acceptable_value\030\025 \001(\003R\025number" +
      "AcceptableValue\022=\n\033number_relative_lower" +
      "_bound\030\026 \001(\003R\030numberRelativeLowerBound\022=" +
      "\n\033number_relative_upper_bound\030\027 \001(\003R\030num" +
      "berRelativeUpperBound\0224\n\026text_acceptable" +
      "_values\030\036 \003(\tR\024textAcceptableValues\022P\n%t" +
      "ext_acceptable_values_with_deviation\030\037 \003" +
      "(\tR!textAcceptableValuesWithDeviation\0228\n" +
      "\030text_unacceptable_values\030  \003(\tR\026textUna" +
      "cceptableValues\022 \n\013description\030( \001(\tR\013de" +
      "scription\"\201\007\n\013QCGroupItem\022\037\n\013entity_uuid" +
      "\030\001 \001(\tR\nentityUuid\0224\n\010metadata\030\002 \001(\0132\030.S" +
      "cailo.EmployeeMetadataR\010metadata\022E\n\021appr" +
      "oval_metadata\030\003 \001(\0132\030.Scailo.ApprovalMet" +
      "adataR\020approvalMetadata\022#\n\rneed_approval" +
      "\030\004 \001(\010R\014needApproval\022!\n\014user_comment\030\005 \001" +
      "(\tR\013userComment\022\'\n\013qc_group_id\030\n \001(\004B\007\272H" +
      "\0042\002 \000R\tqcGroupId\022\'\n\013qc_param_id\030\013 \001(\004B\007\272" +
      "H\0042\002 \000R\tqcParamId\022\036\n\006uom_id\030\014 \001(\004B\007\272H\0042\002" +
      " \000R\005uomId\022\037\n\013is_internal\030\023 \001(\010R\nisIntern" +
      "al\022_\n\025acceptable_value_type\030\024 \001(\0162+.Scai" +
      "lo.QC_GROUP_ITEM_ACCEPTABLE_VALUE_TYPER\023" +
      "acceptableValueType\0226\n\027number_acceptable" +
      "_value\030\025 \001(\003R\025numberAcceptableValue\022=\n\033n" +
      "umber_relative_lower_bound\030\026 \001(\003R\030number" +
      "RelativeLowerBound\022=\n\033number_relative_up" +
      "per_bound\030\027 \001(\003R\030numberRelativeUpperBoun" +
      "d\0224\n\026text_acceptable_values\030\036 \003(\tR\024textA" +
      "cceptableValues\022P\n%text_acceptable_value" +
      "s_with_deviation\030\037 \003(\tR!textAcceptableVa" +
      "luesWithDeviation\0228\n\030text_unacceptable_v" +
      "alues\030  \003(\tR\026textUnacceptableValues\022 \n\013d" +
      "escription\030( \001(\tR\013description\"3\n\014QCGroup" +
      "sList\022#\n\004list\030\001 \003(\0132\017.Scailo.QCGroupR\004li" +
      "st\"<\n\021QCGroupsItemsList\022\'\n\004list\030\001 \003(\0132\023." +
      "Scailo.QCGroupItemR\004list\"m\n\031QCGroupItemH" +
      "istoryRequest\022\'\n\013qc_group_id\030\n \001(\004B\007\272H\0042" +
      "\002 \000R\tqcGroupId\022\'\n\013qc_param_id\030\013 \001(\004B\007\272H\004" +
      "2\002 \000R\tqcParamId\"\225\006\n\031QCGroupItemsSearchRe" +
      "quest\0220\n\tis_active\030\001 \001(\0162\023.Scailo.BOOL_F" +
      "ILTERR\010isActive\022&\n\005count\030\002 \001(\003B\020\272H\r\"\013(\377\377" +
      "\377\377\377\377\377\377\377\001R\005count\022\037\n\006offset\030\003 \001(\004B\007\272H\0042\002(\000" +
      "R\006offset\0221\n\nsort_order\030\004 \001(\0162\022.Scailo.SO" +
      "RT_ORDERR\tsortOrder\0229\n\010sort_key\030\005 \001(\0162\036." +
      "Scailo.QC_GROUP_ITEM_SORT_KEYR\007sortKey\022\037" +
      "\n\013entity_uuid\030\006 \001(\tR\nentityUuid\0224\n\006statu" +
      "s\030\007 \001(\0162\034.Scailo.QC_GROUP_ITEM_STATUSR\006s" +
      "tatus\022*\n\021approved_on_start\030\n \001(\004R\017approv" +
      "edOnStart\022&\n\017approved_on_end\030\013 \001(\004R\rappr" +
      "ovedOnEnd\022-\n\023approved_by_user_id\030\014 \001(\004R\020" +
      "approvedByUserId\022(\n\020approver_role_id\030\r \001" +
      "(\004R\016approverRoleId\022\036\n\013qc_group_id\030\024 \001(\004R" +
      "\tqcGroupId\022\036\n\013qc_param_id\030\025 \001(\004R\tqcParam" +
      "Id\022\025\n\006uom_id\030\026 \001(\004R\005uomId\0224\n\013is_internal" +
      "\030\035 \001(\0162\023.Scailo.BOOL_FILTERR\nisInternal\022" +
      "_\n\025acceptable_value_type\030\036 \001(\0162+.Scailo." +
      "QC_GROUP_ITEM_ACCEPTABLE_VALUE_TYPER\023acc" +
      "eptableValueType\022\035\n\nsearch_key\030( \001(\tR\tse" +
      "archKey\"\232\001\n%QCGroupsServicePaginatedItem" +
      "sResponse\022\024\n\005count\030\001 \001(\004R\005count\022\026\n\006offse" +
      "t\030\002 \001(\004R\006offset\022\024\n\005total\030\003 \001(\004R\005total\022-\n" +
      "\007payload\030\004 \003(\0132\023.Scailo.QCGroupItemR\007pay" +
      "load\"\264\002\n\034QCGroupsServicePaginationReq\0220\n" +
      "\tis_active\030\001 \001(\0162\023.Scailo.BOOL_FILTERR\010i" +
      "sActive\022\035\n\005count\030\002 \001(\003B\007\272H\004\"\002 \000R\005count\022\037" +
      "\n\006offset\030\003 \001(\004B\007\272H\0042\002(\000R\006offset\0221\n\nsort_" +
      "order\030\004 \001(\0162\022.Scailo.SORT_ORDERR\tsortOrd" +
      "er\0224\n\010sort_key\030\005 \001(\0162\031.Scailo.QC_GROUP_S" +
      "ORT_KEYR\007sortKey\0229\n\006status\030\006 \001(\0162!.Scail" +
      "o.STANDARD_LIFECYCLE_STATUSR\006status\"\222\001\n!" +
      "QCGroupsServicePaginationResponse\022\024\n\005cou" +
      "nt\030\001 \001(\004R\005count\022\026\n\006offset\030\002 \001(\004R\006offset\022" +
      "\024\n\005total\030\003 \001(\004R\005total\022)\n\007payload\030\004 \003(\0132\017" +
      ".Scailo.QCGroupR\007payload\"\327\007\n\030QCGroupsSer" +
      "viceFilterReq\0220\n\tis_active\030\001 \001(\0162\023.Scail" +
      "o.BOOL_FILTERR\010isActive\022&\n\005count\030\002 \001(\003B\020" +
      "\272H\r\"\013(\377\377\377\377\377\377\377\377\377\001R\005count\022\037\n\006offset\030\003 \001(\004B" +
      "\007\272H\0042\002(\000R\006offset\0221\n\nsort_order\030\004 \001(\0162\022.S" +
      "cailo.SORT_ORDERR\tsortOrder\0224\n\010sort_key\030" +
      "\005 \001(\0162\031.Scailo.QC_GROUP_SORT_KEYR\007sortKe" +
      "y\0228\n\030creation_timestamp_start\030e \001(\004R\026cre" +
      "ationTimestampStart\0224\n\026creation_timestam" +
      "p_end\030f \001(\004R\024creationTimestampEnd\022@\n\034mod" +
      "ification_timestamp_start\030g \001(\004R\032modific" +
      "ationTimestampStart\022<\n\032modification_time" +
      "stamp_end\030h \001(\004R\030modificationTimestampEn" +
      "d\022\037\n\013entity_uuid\030\010 \001(\tR\nentityUuid\0229\n\006st" +
      "atus\030\n \001(\0162!.Scailo.STANDARD_LIFECYCLE_S" +
      "TATUSR\006status\022*\n\021approved_on_start\030\013 \001(\004" +
      "R\017approvedOnStart\022&\n\017approved_on_end\030\014 \001" +
      "(\004R\rapprovedOnEnd\022-\n\023approved_by_user_id" +
      "\030\r \001(\004R\020approvedByUserId\022(\n\020approver_rol" +
      "e_id\030\016 \001(\004R\016approverRoleId\022,\n\022completed_" +
      "on_start\030\017 \001(\004R\020completedOnStart\022(\n\020comp" +
      "leted_on_end\030\020 \001(\004R\016completedOnEnd\022\022\n\004na" +
      "me\030\024 \001(\tR\004name\022\022\n\004code\030\025 \001(\tR\004code\022\033\n\tfa" +
      "mily_id\030\036 \001(\004R\010familyId\022A\n\tform_data\030\364\003 " +
      "\003(\0132#.Scailo.FormFieldDatumFilterRequest" +
      "R\010formData\"\244\006\n\027QCGroupsServiceCountReq\0220" +
      "\n\tis_active\030\001 \001(\0162\023.Scailo.BOOL_FILTERR\010" +
      "isActive\0228\n\030creation_timestamp_start\030e \001" +
      "(\004R\026creationTimestampStart\0224\n\026creation_t" +
      "imestamp_end\030f \001(\004R\024creationTimestampEnd" +
      "\022@\n\034modification_timestamp_start\030g \001(\004R\032" +
      "modificationTimestampStart\022<\n\032modificati" +
      "on_timestamp_end\030h \001(\004R\030modificationTime" +
      "stampEnd\022\037\n\013entity_uuid\030\010 \001(\tR\nentityUui" +
      "d\0229\n\006status\030\n \001(\0162!.Scailo.STANDARD_LIFE" +
      "CYCLE_STATUSR\006status\022*\n\021approved_on_star" +
      "t\030\013 \001(\004R\017approvedOnStart\022&\n\017approved_on_" +
      "end\030\014 \001(\004R\rapprovedOnEnd\022-\n\023approved_by_" +
      "user_id\030\r \001(\004R\020approvedByUserId\022(\n\020appro" +
      "ver_role_id\030\016 \001(\004R\016approverRoleId\022,\n\022com" +
      "pleted_on_start\030\017 \001(\004R\020completedOnStart\022" +
      "(\n\020completed_on_end\030\020 \001(\004R\016completedOnEn" +
      "d\022\022\n\004name\030\024 \001(\tR\004name\022\022\n\004code\030\025 \001(\tR\004cod" +
      "e\022\033\n\tfamily_id\030\036 \001(\004R\010familyId\022A\n\tform_d" +
      "ata\030\364\003 \003(\0132#.Scailo.FormFieldDatumFilter" +
      "RequestR\010formData\"\231\003\n\033QCGroupsServiceSea" +
      "rchAllReq\0220\n\tis_active\030\001 \001(\0162\023.Scailo.BO" +
      "OL_FILTERR\010isActive\022&\n\005count\030\002 \001(\003B\020\272H\r\"" +
      "\013(\377\377\377\377\377\377\377\377\377\001R\005count\022\037\n\006offset\030\003 \001(\004B\007\272H\004" +
      "2\002(\000R\006offset\0221\n\nsort_order\030\004 \001(\0162\022.Scail" +
      "o.SORT_ORDERR\tsortOrder\0224\n\010sort_key\030\005 \001(" +
      "\0162\031.Scailo.QC_GROUP_SORT_KEYR\007sortKey\022\037\n" +
      "\013entity_uuid\030\006 \001(\tR\nentityUuid\0229\n\006status" +
      "\030\n \001(\0162!.Scailo.STANDARD_LIFECYCLE_STATU" +
      "SR\006status\022\035\n\nsearch_key\030\013 \001(\tR\tsearchKey" +
      "\022\033\n\tfamily_id\030\036 \001(\004R\010familyId*\275\002\n#QC_GRO" +
      "UP_ITEM_ACCEPTABLE_VALUE_TYPE\0227\n3QC_GROU" +
      "P_ITEM_ACCEPTABLE_VALUE_TYPE_ANY_UNSPECI" +
      "FIED\020\000\0227\n3QC_GROUP_ITEM_ACCEPTABLE_VALUE" +
      "_TYPE_NUMBER_ABSOLUTE\020\001\0229\n5QC_GROUP_ITEM" +
      "_ACCEPTABLE_VALUE_TYPE_NUMBER_PERCENTAGE" +
      "\020\002\0222\n.QC_GROUP_ITEM_ACCEPTABLE_VALUE_TYP" +
      "E_TEXT_INPUT\020\003\0225\n1QC_GROUP_ITEM_ACCEPTAB" +
      "LE_VALUE_TYPE_TEXT_DROPDOWN\020\004*\202\003\n\026QC_GRO" +
      "UP_ITEM_SORT_KEY\022)\n%QC_GROUP_ITEM_SORT_K" +
      "EY_ID_UNSPECIFIED\020\000\022%\n!QC_GROUP_ITEM_SOR" +
      "T_KEY_CREATED_AT\020\001\022&\n\"QC_GROUP_ITEM_SORT" +
      "_KEY_MODIFIED_AT\020\002\022&\n\"QC_GROUP_ITEM_SORT" +
      "_KEY_APPROVED_ON\020\003\022&\n\"QC_GROUP_ITEM_SORT" +
      "_KEY_APPROVED_BY\020\004\022+\n\'QC_GROUP_ITEM_SORT" +
      "_KEY_APPROVER_ROLE_ID\020\005\022&\n\"QC_GROUP_ITEM" +
      "_SORT_KEY_QC_GROUP_ID\020\n\022&\n\"QC_GROUP_ITEM" +
      "_SORT_KEY_QC_PARAM_ID\020\013\022!\n\035QC_GROUP_ITEM" +
      "_SORT_KEY_UOM_ID\020\014*\210\001\n\024QC_GROUP_ITEM_STA" +
      "TUS\022(\n$QC_GROUP_ITEM_STATUS_ANY_UNSPECIF" +
      "IED\020\000\022!\n\035QC_GROUP_ITEM_STATUS_APPROVED\020\001" +
      "\022#\n\037QC_GROUP_ITEM_STATUS_UNAPPROVED\020\002*\254\002" +
      "\n\021QC_GROUP_SORT_KEY\022$\n QC_GROUP_SORT_KEY" +
      "_ID_UNSPECIFIED\020\000\022 \n\034QC_GROUP_SORT_KEY_C" +
      "REATED_AT\020\001\022!\n\035QC_GROUP_SORT_KEY_MODIFIE" +
      "D_AT\020\002\022!\n\035QC_GROUP_SORT_KEY_APPROVED_ON\020" +
      "\003\022!\n\035QC_GROUP_SORT_KEY_APPROVED_BY\020\004\022&\n\"" +
      "QC_GROUP_SORT_KEY_APPROVER_ROLE_ID\020\005\022\"\n\036" +
      "QC_GROUP_SORT_KEY_COMPLETED_ON\020\006\022\032\n\026QC_G" +
      "ROUP_SORT_KEY_NAME\020\n2\374\033\n\017QCGroupsService" +
      "\022J\n\006Create\022$.Scailo.QCGroupsServiceCreat" +
      "eRequest\032\032.Scailo.IdentifierResponse\022I\n\005" +
      "Draft\022$.Scailo.QCGroupsServiceCreateRequ" +
      "est\032\032.Scailo.IdentifierResponse\022O\n\013Draft" +
      "Update\022$.Scailo.QCGroupsServiceUpdateReq" +
      "uest\032\032.Scailo.IdentifierResponse\022X\n\023Send" +
      "ForVerification\022%.Scailo.IdentifierUUIDW" +
      "ithUserComment\032\032.Scailo.IdentifierRespon" +
      "se\022K\n\006Verify\022%.Scailo.IdentifierUUIDWith" +
      "UserComment\032\032.Scailo.IdentifierResponse\022" +
      "L\n\007Approve\022%.Scailo.IdentifierUUIDWithUs" +
      "erComment\032\032.Scailo.IdentifierResponse\022T\n" +
      "\017SendForRevision\022%.Scailo.IdentifierUUID" +
      "WithUserComment\032\032.Scailo.IdentifierRespo" +
      "nse\022R\n\016RevisionUpdate\022$.Scailo.QCGroupsS" +
      "erviceUpdateRequest\032\032.Scailo.IdentifierR" +
      "esponse\022I\n\004Halt\022%.Scailo.IdentifierUUIDW" +
      "ithUserComment\032\032.Scailo.IdentifierRespon" +
      "se\022L\n\007Discard\022%.Scailo.IdentifierUUIDWit" +
      "hUserComment\032\032.Scailo.IdentifierResponse" +
      "\022L\n\007Restore\022%.Scailo.IdentifierUUIDWithU" +
      "serComment\032\032.Scailo.IdentifierResponse\022M" +
      "\n\010Complete\022%.Scailo.IdentifierUUIDWithUs" +
      "erComment\032\032.Scailo.IdentifierResponse\022K\n" +
      "\006Repeat\022%.Scailo.IdentifierUUIDWithUserC" +
      "omment\032\032.Scailo.IdentifierResponse\022K\n\006Re" +
      "open\022%.Scailo.IdentifierUUIDWithUserComm" +
      "ent\032\032.Scailo.IdentifierResponse\022O\n\nComme" +
      "ntAdd\022%.Scailo.IdentifierUUIDWithUserCom" +
      "ment\032\032.Scailo.IdentifierResponse\0229\n\005Clon" +
      "e\022\024.Scailo.CloneRequest\032\032.Scailo.Identif" +
      "ierResponse\022V\n\016AddQCGroupItem\022(.Scailo.Q" +
      "CGroupsServiceItemCreateRequest\032\032.Scailo" +
      ".IdentifierResponse\022Y\n\021ModifyQCGroupItem" +
      "\022(.Scailo.QCGroupsServiceItemUpdateReque" +
      "st\032\032.Scailo.IdentifierResponse\022S\n\022Approv" +
      "eQCGroupItem\022!.Scailo.IdentifierWithUser" +
      "Comment\032\032.Scailo.IdentifierResponse\022R\n\021D" +
      "eleteQCGroupItem\022!.Scailo.IdentifierWith" +
      "UserComment\032\032.Scailo.IdentifierResponse\022" +
      "N\n\023ReorderQCGroupItems\022\033.Scailo.ReorderI" +
      "temsRequest\032\032.Scailo.IdentifierResponse\022" +
      ">\n\023ViewQCGroupItemByID\022\022.Scailo.Identifi" +
      "er\032\023.Scailo.QCGroupItem\022V\n\030ViewApprovedQ" +
      "CGroupItems\022\037.Scailo.IdentifierWithSearc" +
      "hKey\032\031.Scailo.QCGroupsItemsList\022X\n\032ViewU" +
      "napprovedQCGroupItems\022\037.Scailo.Identifie" +
      "rWithSearchKey\032\031.Scailo.QCGroupsItemsLis" +
      "t\022V\n\026ViewQCGroupItemHistory\022!.Scailo.QCG" +
      "roupItemHistoryRequest\032\031.Scailo.QCGroups" +
      "ItemsList\022u\n!ViewPaginatedApprovedQCGrou" +
      "pItems\022!.Scailo.QCGroupItemsSearchReques" +
      "t\032-.Scailo.QCGroupsServicePaginatedItems" +
      "Response\022w\n#ViewPaginatedUnapprovedQCGro" +
      "upItems\022!.Scailo.QCGroupItemsSearchReque" +
      "st\032-.Scailo.QCGroupsServicePaginatedItem" +
      "sResponse\022m\n\031SearchItemsWithPagination\022!" +
      ".Scailo.QCGroupItemsSearchRequest\032-.Scai" +
      "lo.QCGroupsServicePaginatedItemsResponse" +
      "\022B\n\022DownloadItemsAsCSV\022\026.Scailo.Identifi" +
      "erUUID\032\024.Scailo.StandardFile\022A\n\032Download" +
      "ItemsTemplateAsCSV\022\r.Scailo.Empty\032\024.Scai" +
      "lo.StandardFile\022M\n\022UploadQCGroupItems\022\036." +
      "Scailo.IdentifierUUIDWithFile\032\027.Scailo.I" +
      "dentifiersList\022/\n\010ViewByID\022\022.Scailo.Iden" +
      "tifier\032\017.Scailo.QCGroup\0225\n\nViewByUUID\022\026." +
      "Scailo.IdentifierUUID\032\017.Scailo.QCGroup\0226" +
      "\n\nViewByCode\022\027.Scailo.SimpleSearchReq\032\017." +
      "Scailo.QCGroup\0228\n\021ViewEssentialByID\022\022.Sc" +
      "ailo.Identifier\032\017.Scailo.QCGroup\022>\n\023View" +
      "EssentialByUUID\022\026.Scailo.IdentifierUUID\032" +
      "\017.Scailo.QCGroup\022<\n\013ViewFromIDs\022\027.Scailo" +
      ".IdentifiersList\032\024.Scailo.QCGroupsList\0225" +
      "\n\007ViewAll\022\024.Scailo.ActiveStatus\032\024.Scailo" +
      ".QCGroupsList\022D\n\024ViewAllForEntityUUID\022\026." +
      "Scailo.IdentifierUUID\032\024.Scailo.QCGroupsL" +
      "ist\022e\n\022ViewWithPagination\022$.Scailo.QCGro" +
      "upsServicePaginationReq\032).Scailo.QCGroup" +
      "sServicePaginationResponse\022F\n\tSearchAll\022" +
      "#.Scailo.QCGroupsServiceSearchAllReq\032\024.S" +
      "cailo.QCGroupsList\022@\n\006Filter\022 .Scailo.QC" +
      "GroupsServiceFilterReq\032\024.Scailo.QCGroups" +
      "List\022G\n\rCountInStatus\022\037.Scailo.CountInSL" +
      "CStatusRequest\032\025.Scailo.CountResponse\022?\n" +
      "\005Count\022\037.Scailo.QCGroupsServiceCountReq\032" +
      "\025.Scailo.CountResponse\022G\n\rDownloadAsCSV\022" +
      " .Scailo.QCGroupsServiceFilterReq\032\024.Scai" +
      "lo.StandardFile\022B\n\rImportFromCSV\022\024.Scail" +
      "o.StandardFile\032\033.Scailo.IdentifierUUIDsL" +
      "istBm\n\016com.scailo.sdkB\023QcGroupsScailoPro" +
      "toP\001Z\nScailo/sdk\242\002\003SXX\252\002\nScailo.Sdk\312\002\006Sc" +
      "ailo\342\002\022Scailo\\GPBMetadata\352\002\006Scailob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.scailo.sdk.BaseScailoProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
          com.scailo.sdk.FormsFieldsDataScailoProto.getDescriptor(),
        });
    internal_static_Scailo_QCGroupsServiceCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Scailo_QCGroupsServiceCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceCreateRequest_descriptor,
        new java.lang.String[] { "EntityUuid", "UserComment", "VaultFolderId", "Name", "Code", "Description", "FormData", });
    internal_static_Scailo_QCGroupsServiceUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Scailo_QCGroupsServiceUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceUpdateRequest_descriptor,
        new java.lang.String[] { "UserComment", "Id", "NotifyUsers", "VaultFolderId", "Name", "Code", "Description", "FormData", });
    internal_static_Scailo_QCGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Scailo_QCGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroup_descriptor,
        new java.lang.String[] { "EntityUuid", "Metadata", "ApprovalMetadata", "Status", "Logs", "CompletedOn", "VaultFolderId", "Name", "Code", "Description", "List", "FormData", });
    internal_static_Scailo_QCGroupsServiceItemCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Scailo_QCGroupsServiceItemCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceItemCreateRequest_descriptor,
        new java.lang.String[] { "UserComment", "QcGroupId", "QcParamId", "UomId", "IsInternal", "AcceptableValueType", "NumberAcceptableValue", "NumberRelativeLowerBound", "NumberRelativeUpperBound", "TextAcceptableValues", "TextAcceptableValuesWithDeviation", "TextUnacceptableValues", "Description", });
    internal_static_Scailo_QCGroupsServiceItemUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Scailo_QCGroupsServiceItemUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceItemUpdateRequest_descriptor,
        new java.lang.String[] { "UserComment", "Id", "IsInternal", "AcceptableValueType", "NumberAcceptableValue", "NumberRelativeLowerBound", "NumberRelativeUpperBound", "TextAcceptableValues", "TextAcceptableValuesWithDeviation", "TextUnacceptableValues", "Description", });
    internal_static_Scailo_QCGroupItem_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Scailo_QCGroupItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupItem_descriptor,
        new java.lang.String[] { "EntityUuid", "Metadata", "ApprovalMetadata", "NeedApproval", "UserComment", "QcGroupId", "QcParamId", "UomId", "IsInternal", "AcceptableValueType", "NumberAcceptableValue", "NumberRelativeLowerBound", "NumberRelativeUpperBound", "TextAcceptableValues", "TextAcceptableValuesWithDeviation", "TextUnacceptableValues", "Description", });
    internal_static_Scailo_QCGroupsList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Scailo_QCGroupsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_Scailo_QCGroupsItemsList_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Scailo_QCGroupsItemsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsItemsList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_Scailo_QCGroupItemHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Scailo_QCGroupItemHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupItemHistoryRequest_descriptor,
        new java.lang.String[] { "QcGroupId", "QcParamId", });
    internal_static_Scailo_QCGroupItemsSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Scailo_QCGroupItemsSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupItemsSearchRequest_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "EntityUuid", "Status", "ApprovedOnStart", "ApprovedOnEnd", "ApprovedByUserId", "ApproverRoleId", "QcGroupId", "QcParamId", "UomId", "IsInternal", "AcceptableValueType", "SearchKey", });
    internal_static_Scailo_QCGroupsServicePaginatedItemsResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Scailo_QCGroupsServicePaginatedItemsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServicePaginatedItemsResponse_descriptor,
        new java.lang.String[] { "Count", "Offset", "Total", "Payload", });
    internal_static_Scailo_QCGroupsServicePaginationReq_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Scailo_QCGroupsServicePaginationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServicePaginationReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "Status", });
    internal_static_Scailo_QCGroupsServicePaginationResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Scailo_QCGroupsServicePaginationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServicePaginationResponse_descriptor,
        new java.lang.String[] { "Count", "Offset", "Total", "Payload", });
    internal_static_Scailo_QCGroupsServiceFilterReq_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Scailo_QCGroupsServiceFilterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceFilterReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "CreationTimestampStart", "CreationTimestampEnd", "ModificationTimestampStart", "ModificationTimestampEnd", "EntityUuid", "Status", "ApprovedOnStart", "ApprovedOnEnd", "ApprovedByUserId", "ApproverRoleId", "CompletedOnStart", "CompletedOnEnd", "Name", "Code", "FamilyId", "FormData", });
    internal_static_Scailo_QCGroupsServiceCountReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Scailo_QCGroupsServiceCountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceCountReq_descriptor,
        new java.lang.String[] { "IsActive", "CreationTimestampStart", "CreationTimestampEnd", "ModificationTimestampStart", "ModificationTimestampEnd", "EntityUuid", "Status", "ApprovedOnStart", "ApprovedOnEnd", "ApprovedByUserId", "ApproverRoleId", "CompletedOnStart", "CompletedOnEnd", "Name", "Code", "FamilyId", "FormData", });
    internal_static_Scailo_QCGroupsServiceSearchAllReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Scailo_QCGroupsServiceSearchAllReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Scailo_QCGroupsServiceSearchAllReq_descriptor,
        new java.lang.String[] { "IsActive", "Count", "Offset", "SortOrder", "SortKey", "EntityUuid", "Status", "SearchKey", "FamilyId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.scailo.sdk.BaseScailoProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.scailo.sdk.FormsFieldsDataScailoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
