//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: quotations_responses.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializequotationsResponsesServiceItemUpdateRequest")
public inline fun quotationsResponsesServiceItemUpdateRequest(block: com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest =
  com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequestKt.Dsl._create(com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest.newBuilder()).apply { block() }._build()
public object QuotationsResponsesServiceItemUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest = _builder.build()

    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     */
    public var userComment: kotlin.String
      @JvmName("getUserComment")
      get() = _builder.getUserComment()
      @JvmName("setUserComment")
      set(value) {
        _builder.setUserComment(value)
      }
    /**
     * <pre>
     * Stores any comment that the user might add during this operation
     * </pre>
     *
     * <code>string user_comment = 1 [json_name = "userComment"];</code>
     */
    public fun clearUserComment() {
      _builder.clearUserComment()
    }

    /**
     * <pre>
     * The ID of the record
     * </pre>
     *
     * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <pre>
     * The ID of the record
     * </pre>
     *
     * <code>uint64 id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     */
    public var vaultFolderId: kotlin.Long
      @JvmName("getVaultFolderId")
      get() = _builder.getVaultFolderId()
      @JvmName("setVaultFolderId")
      set(value) {
        _builder.setVaultFolderId(value)
      }
    /**
     * <pre>
     * The associated vault folder ID
     * </pre>
     *
     * <code>uint64 vault_folder_id = 9 [json_name = "vaultFolderId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearVaultFolderId() {
      _builder.clearVaultFolderId()
    }

    /**
     * <pre>
     * Stores the name of the item
     * </pre>
     *
     * <code>string name = 12 [json_name = "name", (.buf.validate.field) = { ... }</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * Stores the name of the item
     * </pre>
     *
     * <code>string name = 12 [json_name = "name", (.buf.validate.field) = { ... }</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <pre>
     * Stores the HSN/SAC code of the item
     * </pre>
     *
     * <code>string hsn_sac_code = 13 [json_name = "hsnSacCode", (.buf.validate.field) = { ... }</code>
     */
    public var hsnSacCode: kotlin.String
      @JvmName("getHsnSacCode")
      get() = _builder.getHsnSacCode()
      @JvmName("setHsnSacCode")
      set(value) {
        _builder.setHsnSacCode(value)
      }
    /**
     * <pre>
     * Stores the HSN/SAC code of the item
     * </pre>
     *
     * <code>string hsn_sac_code = 13 [json_name = "hsnSacCode", (.buf.validate.field) = { ... }</code>
     */
    public fun clearHsnSacCode() {
      _builder.clearHsnSacCode()
    }

    /**
     * <pre>
     * The internal unit of material
     * </pre>
     *
     * <code>uint64 uom_id = 14 [json_name = "uomId", (.buf.validate.field) = { ... }</code>
     */
    public var uomId: kotlin.Long
      @JvmName("getUomId")
      get() = _builder.getUomId()
      @JvmName("setUomId")
      set(value) {
        _builder.setUomId(value)
      }
    /**
     * <pre>
     * The internal unit of material
     * </pre>
     *
     * <code>uint64 uom_id = 14 [json_name = "uomId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearUomId() {
      _builder.clearUomId()
    }

    /**
     * <pre>
     * The internal quantity offered (in cents)
     * </pre>
     *
     * <code>uint64 internal_quantity = 15 [json_name = "internalQuantity", (.buf.validate.field) = { ... }</code>
     */
    public var internalQuantity: kotlin.Long
      @JvmName("getInternalQuantity")
      get() = _builder.getInternalQuantity()
      @JvmName("setInternalQuantity")
      set(value) {
        _builder.setInternalQuantity(value)
      }
    /**
     * <pre>
     * The internal quantity offered (in cents)
     * </pre>
     *
     * <code>uint64 internal_quantity = 15 [json_name = "internalQuantity", (.buf.validate.field) = { ... }</code>
     */
    public fun clearInternalQuantity() {
      _builder.clearInternalQuantity()
    }

    /**
     * <pre>
     * The vendor's unit of material
     * </pre>
     *
     * <code>uint64 vendor_uom_id = 16 [json_name = "vendorUomId", (.buf.validate.field) = { ... }</code>
     */
    public var vendorUomId: kotlin.Long
      @JvmName("getVendorUomId")
      get() = _builder.getVendorUomId()
      @JvmName("setVendorUomId")
      set(value) {
        _builder.setVendorUomId(value)
      }
    /**
     * <pre>
     * The vendor's unit of material
     * </pre>
     *
     * <code>uint64 vendor_uom_id = 16 [json_name = "vendorUomId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearVendorUomId() {
      _builder.clearVendorUomId()
    }

    /**
     * <pre>
     * The quantity offered in vendor's unit of material (in cents)
     * </pre>
     *
     * <code>uint64 vendor_quantity = 17 [json_name = "vendorQuantity", (.buf.validate.field) = { ... }</code>
     */
    public var vendorQuantity: kotlin.Long
      @JvmName("getVendorQuantity")
      get() = _builder.getVendorQuantity()
      @JvmName("setVendorQuantity")
      set(value) {
        _builder.setVendorQuantity(value)
      }
    /**
     * <pre>
     * The quantity offered in vendor's unit of material (in cents)
     * </pre>
     *
     * <code>uint64 vendor_quantity = 17 [json_name = "vendorQuantity", (.buf.validate.field) = { ... }</code>
     */
    public fun clearVendorQuantity() {
      _builder.clearVendorQuantity()
    }

    /**
     * <pre>
     * The unit price per vendor's unit of material
     * </pre>
     *
     * <code>uint64 vendor_unit_price = 18 [json_name = "vendorUnitPrice", (.buf.validate.field) = { ... }</code>
     */
    public var vendorUnitPrice: kotlin.Long
      @JvmName("getVendorUnitPrice")
      get() = _builder.getVendorUnitPrice()
      @JvmName("setVendorUnitPrice")
      set(value) {
        _builder.setVendorUnitPrice(value)
      }
    /**
     * <pre>
     * The unit price per vendor's unit of material
     * </pre>
     *
     * <code>uint64 vendor_unit_price = 18 [json_name = "vendorUnitPrice", (.buf.validate.field) = { ... }</code>
     */
    public fun clearVendorUnitPrice() {
      _builder.clearVendorUnitPrice()
    }

    /**
     * <pre>
     * The associated tax group ID
     * </pre>
     *
     * <code>uint64 tax_group_id = 19 [json_name = "taxGroupId", (.buf.validate.field) = { ... }</code>
     */
    public var taxGroupId: kotlin.Long
      @JvmName("getTaxGroupId")
      get() = _builder.getTaxGroupId()
      @JvmName("setTaxGroupId")
      set(value) {
        _builder.setTaxGroupId(value)
      }
    /**
     * <pre>
     * The associated tax group ID
     * </pre>
     *
     * <code>uint64 tax_group_id = 19 [json_name = "taxGroupId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearTaxGroupId() {
      _builder.clearTaxGroupId()
    }

    /**
     * <pre>
     * The delivery time in days (in cents)
     * </pre>
     *
     * <code>uint64 delivery_time_in_days = 20 [json_name = "deliveryTimeInDays", (.buf.validate.field) = { ... }</code>
     */
    public var deliveryTimeInDays: kotlin.Long
      @JvmName("getDeliveryTimeInDays")
      get() = _builder.getDeliveryTimeInDays()
      @JvmName("setDeliveryTimeInDays")
      set(value) {
        _builder.setDeliveryTimeInDays(value)
      }
    /**
     * <pre>
     * The delivery time in days (in cents)
     * </pre>
     *
     * <code>uint64 delivery_time_in_days = 20 [json_name = "deliveryTimeInDays", (.buf.validate.field) = { ... }</code>
     */
    public fun clearDeliveryTimeInDays() {
      _builder.clearDeliveryTimeInDays()
    }

    /**
     * <pre>
     * The specifications of the item
     * </pre>
     *
     * <code>string specifications = 21 [json_name = "specifications"];</code>
     */
    public var specifications: kotlin.String
      @JvmName("getSpecifications")
      get() = _builder.getSpecifications()
      @JvmName("setSpecifications")
      set(value) {
        _builder.setSpecifications(value)
      }
    /**
     * <pre>
     * The specifications of the item
     * </pre>
     *
     * <code>string specifications = 21 [json_name = "specifications"];</code>
     */
    public fun clearSpecifications() {
      _builder.clearSpecifications()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest.copy(block: com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequest =
  com.scailo.sdk.QuotationsResponsesServiceItemUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

