// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quotations_responses.scailo.proto

package com.scailo.sdk;

public interface QuotationsResponsesItemsListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.QuotationsResponsesItemsList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.QuotationResponseItem list = 1 [json_name = "list"];</code>
   */
  java.util.List<com.scailo.sdk.QuotationResponseItem> 
      getListList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.QuotationResponseItem list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.QuotationResponseItem getList(int index);
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.QuotationResponseItem list = 1 [json_name = "list"];</code>
   */
  int getListCount();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.QuotationResponseItem list = 1 [json_name = "list"];</code>
   */
  java.util.List<? extends com.scailo.sdk.QuotationResponseItemOrBuilder> 
      getListOrBuilderList();
  /**
   * <pre>
   * List of records
   * </pre>
   *
   * <code>repeated .Scailo.QuotationResponseItem list = 1 [json_name = "list"];</code>
   */
  com.scailo.sdk.QuotationResponseItemOrBuilder getListOrBuilder(
      int index);
}
