//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: sales_invoices.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializesalesInvoiceItemProspectiveInfoRequest")
public inline fun salesInvoiceItemProspectiveInfoRequest(block: com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest =
  com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequestKt.Dsl._create(com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest.newBuilder()).apply { block() }._build()
public object SalesInvoiceItemProspectiveInfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest = _builder.build()

    /**
     * <pre>
     * Stores the sales invoice ID
     * </pre>
     *
     * <code>uint64 sales_invoice_id = 10 [json_name = "salesInvoiceId", (.buf.validate.field) = { ... }</code>
     */
    public var salesInvoiceId: kotlin.Long
      @JvmName("getSalesInvoiceId")
      get() = _builder.getSalesInvoiceId()
      @JvmName("setSalesInvoiceId")
      set(value) {
        _builder.setSalesInvoiceId(value)
      }
    /**
     * <pre>
     * Stores the sales invoice ID
     * </pre>
     *
     * <code>uint64 sales_invoice_id = 10 [json_name = "salesInvoiceId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearSalesInvoiceId() {
      _builder.clearSalesInvoiceId()
    }

    /**
     * <pre>
     * Stores the family ID
     * </pre>
     *
     * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
     */
    public var familyId: kotlin.Long
      @JvmName("getFamilyId")
      get() = _builder.getFamilyId()
      @JvmName("setFamilyId")
      set(value) {
        _builder.setFamilyId(value)
      }
    /**
     * <pre>
     * Stores the family ID
     * </pre>
     *
     * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearFamilyId() {
      _builder.clearFamilyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest.copy(block: com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequest =
  com.scailo.sdk.SalesInvoiceItemProspectiveInfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

