// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_issuances.scailo.proto

package com.scailo.sdk;

public interface StockIssuancesServiceItemCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.StockIssuancesServiceItemCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The userComment.
   */
  java.lang.String getUserComment();
  /**
   * <pre>
   * Stores any comment that the user might add during this operation
   * </pre>
   *
   * <code>string user_comment = 1 [json_name = "userComment"];</code>
   * @return The bytes for userComment.
   */
  com.google.protobuf.ByteString
      getUserCommentBytes();

  /**
   * <pre>
   * Stores the stock issuance ID
   * </pre>
   *
   * <code>uint64 stock_issuance_id = 10 [json_name = "stockIssuanceId", (.buf.validate.field) = { ... }</code>
   * @return The stockIssuanceId.
   */
  long getStockIssuanceId();

  /**
   * <pre>
   * Stores the family ID
   * </pre>
   *
   * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
   * @return The familyId.
   */
  long getFamilyId();

  /**
   * <pre>
   * The quantity (in cents) being admitted in internal unit of material
   * </pre>
   *
   * <code>uint64 internal_quantity = 12 [json_name = "internalQuantity", (.buf.validate.field) = { ... }</code>
   * @return The internalQuantity.
   */
  long getInternalQuantity();

  /**
   * <pre>
   * The hash of the inventory item
   * </pre>
   *
   * <code>string item_hash = 13 [json_name = "itemHash", (.buf.validate.field) = { ... }</code>
   * @return The itemHash.
   */
  java.lang.String getItemHash();
  /**
   * <pre>
   * The hash of the inventory item
   * </pre>
   *
   * <code>string item_hash = 13 [json_name = "itemHash", (.buf.validate.field) = { ... }</code>
   * @return The bytes for itemHash.
   */
  com.google.protobuf.ByteString
      getItemHashBytes();
}
