// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storages.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Describes the available sort keys
 * </pre>
 *
 * Protobuf enum {@code Scailo.STORAGE_SORT_KEY}
 */
public enum STORAGE_SORT_KEY
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Fetch ordered results by id
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_ID_UNSPECIFIED = 0;</code>
   */
  STORAGE_SORT_KEY_ID_UNSPECIFIED(0),
  /**
   * <pre>
   * Fetch ordered results by the creation timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_CREATED_AT = 1;</code>
   */
  STORAGE_SORT_KEY_CREATED_AT(1),
  /**
   * <pre>
   * Fetch ordered results by the modified timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_MODIFIED_AT = 2;</code>
   */
  STORAGE_SORT_KEY_MODIFIED_AT(2),
  /**
   * <pre>
   * Fetch ordered results by the approved on timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVED_ON = 3;</code>
   */
  STORAGE_SORT_KEY_APPROVED_ON(3),
  /**
   * <pre>
   * Fetch ordered results by the approved by field
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVED_BY = 4;</code>
   */
  STORAGE_SORT_KEY_APPROVED_BY(4),
  /**
   * <pre>
   * Fetch ordered results by the approver's role ID
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVER_ROLE_ID = 5;</code>
   */
  STORAGE_SORT_KEY_APPROVER_ROLE_ID(5),
  /**
   * <pre>
   * Fetch ordered results by the name
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_NAME = 10;</code>
   */
  STORAGE_SORT_KEY_NAME(10),
  /**
   * <pre>
   * Fetch ordered results by the code
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_CODE = 11;</code>
   */
  STORAGE_SORT_KEY_CODE(11),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Fetch ordered results by id
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_ID_UNSPECIFIED = 0;</code>
   */
  public static final int STORAGE_SORT_KEY_ID_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Fetch ordered results by the creation timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_CREATED_AT = 1;</code>
   */
  public static final int STORAGE_SORT_KEY_CREATED_AT_VALUE = 1;
  /**
   * <pre>
   * Fetch ordered results by the modified timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_MODIFIED_AT = 2;</code>
   */
  public static final int STORAGE_SORT_KEY_MODIFIED_AT_VALUE = 2;
  /**
   * <pre>
   * Fetch ordered results by the approved on timestamp
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVED_ON = 3;</code>
   */
  public static final int STORAGE_SORT_KEY_APPROVED_ON_VALUE = 3;
  /**
   * <pre>
   * Fetch ordered results by the approved by field
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVED_BY = 4;</code>
   */
  public static final int STORAGE_SORT_KEY_APPROVED_BY_VALUE = 4;
  /**
   * <pre>
   * Fetch ordered results by the approver's role ID
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_APPROVER_ROLE_ID = 5;</code>
   */
  public static final int STORAGE_SORT_KEY_APPROVER_ROLE_ID_VALUE = 5;
  /**
   * <pre>
   * Fetch ordered results by the name
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_NAME = 10;</code>
   */
  public static final int STORAGE_SORT_KEY_NAME_VALUE = 10;
  /**
   * <pre>
   * Fetch ordered results by the code
   * </pre>
   *
   * <code>STORAGE_SORT_KEY_CODE = 11;</code>
   */
  public static final int STORAGE_SORT_KEY_CODE_VALUE = 11;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static STORAGE_SORT_KEY valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static STORAGE_SORT_KEY forNumber(int value) {
    switch (value) {
      case 0: return STORAGE_SORT_KEY_ID_UNSPECIFIED;
      case 1: return STORAGE_SORT_KEY_CREATED_AT;
      case 2: return STORAGE_SORT_KEY_MODIFIED_AT;
      case 3: return STORAGE_SORT_KEY_APPROVED_ON;
      case 4: return STORAGE_SORT_KEY_APPROVED_BY;
      case 5: return STORAGE_SORT_KEY_APPROVER_ROLE_ID;
      case 10: return STORAGE_SORT_KEY_NAME;
      case 11: return STORAGE_SORT_KEY_CODE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<STORAGE_SORT_KEY>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      STORAGE_SORT_KEY> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<STORAGE_SORT_KEY>() {
          public STORAGE_SORT_KEY findValueByNumber(int number) {
            return STORAGE_SORT_KEY.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scailo.sdk.StoragesScailoProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final STORAGE_SORT_KEY[] VALUES = values();

  public static STORAGE_SORT_KEY valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private STORAGE_SORT_KEY(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Scailo.STORAGE_SORT_KEY)
}

