// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vault_files.scailo.proto

package com.scailo.sdk;

public interface VaultFileAddChunkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Scailo.VaultFileAddChunkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The UUID of the file
   * </pre>
   *
   * <code>string uuid = 1 [json_name = "uuid", (.buf.validate.field) = { ... }</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * The UUID of the file
   * </pre>
   *
   * <code>string uuid = 1 [json_name = "uuid", (.buf.validate.field) = { ... }</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * Stores the sequence ID of this chunk
   * </pre>
   *
   * <code>uint64 sequence_id = 11 [json_name = "sequenceId", (.buf.validate.field) = { ... }</code>
   * @return The sequenceId.
   */
  long getSequenceId();

  /**
   * <pre>
   * Stores the content of the chunk
   * </pre>
   *
   * <code>bytes chunk = 12 [json_name = "chunk", (.buf.validate.field) = { ... }</code>
   * @return The chunk.
   */
  com.google.protobuf.ByteString getChunk();
}
