// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workflows_rules.scailo.proto

package com.scailo.sdk;

/**
 * <pre>
 *Stores all the possible values for when the rule should be triggered. Possible values are Success and Failure.
 * </pre>
 *
 * Protobuf enum {@code Scailo.WORKFLOW_RULE_EXECUTE_ON}
 */
public enum WORKFLOW_RULE_EXECUTE_ON
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Used only for filters
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_ANY_UNSPECIFIED = 0;</code>
   */
  WORKFLOW_RULE_EXECUTE_ON_ANY_UNSPECIFIED(0),
  /**
   * <pre>
   * Execute the rule when the transaction is successful
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_SUCCESS = 1;</code>
   */
  WORKFLOW_RULE_EXECUTE_ON_SUCCESS(1),
  /**
   * <pre>
   * Execute the rule when the transaction fails
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_FAILURE = 2;</code>
   */
  WORKFLOW_RULE_EXECUTE_ON_FAILURE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Used only for filters
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_ANY_UNSPECIFIED = 0;</code>
   */
  public static final int WORKFLOW_RULE_EXECUTE_ON_ANY_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Execute the rule when the transaction is successful
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_SUCCESS = 1;</code>
   */
  public static final int WORKFLOW_RULE_EXECUTE_ON_SUCCESS_VALUE = 1;
  /**
   * <pre>
   * Execute the rule when the transaction fails
   * </pre>
   *
   * <code>WORKFLOW_RULE_EXECUTE_ON_FAILURE = 2;</code>
   */
  public static final int WORKFLOW_RULE_EXECUTE_ON_FAILURE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WORKFLOW_RULE_EXECUTE_ON valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static WORKFLOW_RULE_EXECUTE_ON forNumber(int value) {
    switch (value) {
      case 0: return WORKFLOW_RULE_EXECUTE_ON_ANY_UNSPECIFIED;
      case 1: return WORKFLOW_RULE_EXECUTE_ON_SUCCESS;
      case 2: return WORKFLOW_RULE_EXECUTE_ON_FAILURE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WORKFLOW_RULE_EXECUTE_ON>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WORKFLOW_RULE_EXECUTE_ON> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WORKFLOW_RULE_EXECUTE_ON>() {
          public WORKFLOW_RULE_EXECUTE_ON findValueByNumber(int number) {
            return WORKFLOW_RULE_EXECUTE_ON.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scailo.sdk.WorkflowsRulesScailoProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final WORKFLOW_RULE_EXECUTE_ON[] VALUES = values();

  public static WORKFLOW_RULE_EXECUTE_ON valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WORKFLOW_RULE_EXECUTE_ON(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Scailo.WORKFLOW_RULE_EXECUTE_ON)
}

