//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: work_orders.scailo.proto

package com.scailo.sdk;

@kotlin.jvm.JvmName("-initializeworkOrderItemProspectiveInfoRequest")
public inline fun workOrderItemProspectiveInfoRequest(block: com.scailo.sdk.WorkOrderItemProspectiveInfoRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.WorkOrderItemProspectiveInfoRequest =
  com.scailo.sdk.WorkOrderItemProspectiveInfoRequestKt.Dsl._create(com.scailo.sdk.WorkOrderItemProspectiveInfoRequest.newBuilder()).apply { block() }._build()
public object WorkOrderItemProspectiveInfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.scailo.sdk.WorkOrderItemProspectiveInfoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.scailo.sdk.WorkOrderItemProspectiveInfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.scailo.sdk.WorkOrderItemProspectiveInfoRequest = _builder.build()

    /**
     * <pre>
     * Stores the work order ID
     * </pre>
     *
     * <code>uint64 work_order_id = 10 [json_name = "workOrderId", (.buf.validate.field) = { ... }</code>
     */
    public var workOrderId: kotlin.Long
      @JvmName("getWorkOrderId")
      get() = _builder.getWorkOrderId()
      @JvmName("setWorkOrderId")
      set(value) {
        _builder.setWorkOrderId(value)
      }
    /**
     * <pre>
     * Stores the work order ID
     * </pre>
     *
     * <code>uint64 work_order_id = 10 [json_name = "workOrderId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearWorkOrderId() {
      _builder.clearWorkOrderId()
    }

    /**
     * <pre>
     * Stores the family ID
     * </pre>
     *
     * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
     */
    public var familyId: kotlin.Long
      @JvmName("getFamilyId")
      get() = _builder.getFamilyId()
      @JvmName("setFamilyId")
      set(value) {
        _builder.setFamilyId(value)
      }
    /**
     * <pre>
     * Stores the family ID
     * </pre>
     *
     * <code>uint64 family_id = 11 [json_name = "familyId", (.buf.validate.field) = { ... }</code>
     */
    public fun clearFamilyId() {
      _builder.clearFamilyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.scailo.sdk.WorkOrderItemProspectiveInfoRequest.copy(block: com.scailo.sdk.WorkOrderItemProspectiveInfoRequestKt.Dsl.() -> kotlin.Unit): com.scailo.sdk.WorkOrderItemProspectiveInfoRequest =
  com.scailo.sdk.WorkOrderItemProspectiveInfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

